// Auto-curated V2 assignments for PRB02.
// Generated by npm run effects:v2 from fully parser-recognized canonical atoms.
// Review before copying into src/cards/effectCompiler_V2/assignments/<SET>_V2.ts.
import type { EffectAssignment_V2 } from '../../src/cards/effectCompiler_V2/types_V2';

export const PRB02_AUTO_ASSIGNMENTS_V2 = [
  {
    "assignmentId": "v2:auto:PRB02-001:0",
    "cardNumber": "PRB02-001",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Opponent's Turn] If your Leader has the {Navy} type, this Character gains +1000 power.",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "conditions": {
        "kind": "AND",
        "conditions": [
          {
            "kind": "PREDICATE",
            "left": {
              "kind": "CURRENT_TURN_PLAYER"
            },
            "operator": "EQUAL",
            "right": {
              "kind": "EFFECT_OPPONENT"
            }
          },
          {
            "kind": "PREDICATE",
            "left": {
              "kind": "COUNT",
              "selector": {
                "subject": "CARD",
                "controller": "PLAYER",
                "zones": [
                  "LEADER_AREA"
                ],
                "cardCategories": [
                  "LEADER"
                ],
                "types": {
                  "kind": "TYPE_INCLUDES_TEXT",
                  "values": [
                    "Navy"
                  ]
                },
                "quantity": {
                  "kind": "ANY_NUMBER"
                }
              }
            },
            "operator": "GREATER_OR_EQUAL",
            "right": {
              "kind": "NUMBER",
              "value": 1
            }
          }
        ]
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "MODIFY_POWER",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "propertyLayer": "CURRENT_VALUE",
          "operation": "ADD",
          "value": {
            "kind": "NUMBER",
            "value": 1000
          },
          "duration": {
            "kind": "PERMANENT"
          }
        },
        "actionId": "PRB02-001#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-001#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-001:1",
    "cardNumber": "PRB02-001",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[When Attacking] K.O. up to 1 of your opponent's Characters with 3000 base power or less. Then, if you have 6 or less cards in your hand, draw 1 card.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "WHEN_ATTACKING"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "KO_CARD",
              "selector": {
                "subject": "CARD",
                "controller": "OPPONENT",
                "zones": [
                  "CHARACTER_AREA"
                ],
                "cardCategories": [
                  "CHARACTER"
                ],
                "quantity": {
                  "kind": "UP_TO",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER",
                "power": {
                  "propertyLayer": "BASE",
                  "comparison": "EQUAL",
                  "value": {
                    "kind": "NUMBER",
                    "value": 3000
                  }
                }
              },
              "cause": "EFFECT"
            },
            "actionId": "PRB02-001#1.0"
          },
          {
            "kind": "IF",
            "condition": {
              "kind": "PREDICATE",
              "left": {
                "kind": "COUNT",
                "selector": {
                  "subject": "CARD",
                  "owner": "PLAYER",
                  "zones": [
                    "HAND"
                  ],
                  "quantity": {
                    "kind": "ANY_NUMBER"
                  }
                }
              },
              "operator": "LESS_OR_EQUAL",
              "right": {
                "kind": "NUMBER",
                "value": 6
              }
            },
            "then": {
              "kind": "ACTION",
              "action": {
                "type": "DRAW_CARD",
                "player": "PLAYER",
                "count": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "actionId": "PRB02-001#1.1"
            }
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-001#1.0",
      "PRB02-001#1.1"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-002:0",
    "cardNumber": "PRB02-002",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Once Per Turn] If this Character would be removed from the field by your opponent's effect, you may give this Character −2000 power during this turn instead.",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "CREATE_REPLACEMENT_EFFECT",
          "effect": {
            "id": "replacement:generated",
            "source": {
              "objectRef": "GENERATED_EFFECT",
              "owner": "PLAYER",
              "controller": "PLAYER",
              "sourceZone": "NONE"
            },
            "category": "REPLACEMENT",
            "applicationMode": "CONTINUOUS",
            "activationZones": [
              "LEADER_AREA",
              "CHARACTER_AREA",
              "STAGE_AREA"
            ],
            "optionality": "OPTIONAL",
            "resolution": {
              "kind": "ACTION",
              "action": {
                "type": "MODIFY_POWER",
                "selector": {
                  "subject": "CARD",
                  "relations": [
                    "THIS_CARD"
                  ],
                  "quantity": {
                    "kind": "EXACTLY",
                    "value": {
                      "kind": "NUMBER",
                      "value": 1
                    }
                  },
                  "chooser": "EFFECT_OWNER"
                },
                "propertyLayer": "CURRENT_VALUE",
                "operation": "SUBTRACT",
                "value": {
                  "kind": "NUMBER",
                  "value": 2000
                },
                "duration": {
                  "kind": "THIS_TURN"
                }
              }
            },
            "metadata": {
              "sourceCardNumber": "GENERATED",
              "effectIndex": 0,
              "printedText": "If this Character would be removed from the field by your opponent's effect, you may give this Character −2000 power during this turn instead.",
              "authoringStatus": "PARSED_ONLY"
            },
            "timing": {
              "kind": "CUSTOM_EVENT",
              "eventType": "CARD_WOULD_MOVE",
              "subject": {
                "subject": "CARD",
                "relations": [
                  "THIS_CARD"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "fromZone": "CHARACTER_AREA",
              "sourceSelector": {
                "subject": "EFFECT",
                "controller": "OPPONENT",
                "quantity": {
                  "kind": "ANY_NUMBER"
                }
              },
              "conditions": {
                "kind": "PREDICATE",
                "left": {
                  "kind": "MOVE_CAUSE"
                },
                "operator": "EQUAL",
                "right": {
                  "kind": "STRING",
                  "value": "EFFECT"
                }
              }
            }
          },
          "duration": {
            "kind": "THIS_TURN"
          }
        },
        "actionId": "PRB02-002#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-002#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-002:1",
    "cardNumber": "PRB02-002",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[When Attacking] Give up to 1 of your opponent's Characters −2000 power during this turn.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "WHEN_ATTACKING"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "MODIFY_POWER",
          "selector": {
            "subject": "CARD",
            "controller": "OPPONENT",
            "zones": [
              "CHARACTER_AREA"
            ],
            "cardCategories": [
              "CHARACTER"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "propertyLayer": "CURRENT_VALUE",
          "operation": "SUBTRACT",
          "value": {
            "kind": "NUMBER",
            "value": 2000
          },
          "duration": {
            "kind": "THIS_TURN"
          }
        },
        "actionId": "PRB02-002#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-002#1.0"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-003:0",
    "cardNumber": "PRB02-003",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "GRANT_KEYWORD",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "keyword": "BLOCKER",
          "duration": {
            "kind": "PERMANENT"
          }
        },
        "actionId": "PRB02-003#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-003#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-003:1",
    "cardNumber": "PRB02-003",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[On Play] You may trash 1 Character card with 6000 power or more from your hand: Draw 2 cards.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "activationCost": {
        "payments": [
          {
            "type": "TRASH_CARD_COST",
            "selector": {
              "subject": "CARD",
              "owner": "PLAYER",
              "zones": [
                "HAND"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "chooser": "EFFECT_OWNER",
              "power": {
                "propertyLayer": "CURRENT",
                "comparison": "AT_LEAST",
                "value": {
                  "kind": "NUMBER",
                  "value": 6000
                }
              }
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "DRAW_CARD",
          "player": "PLAYER",
          "count": {
            "kind": "NUMBER",
            "value": 2
          }
        },
        "actionId": "PRB02-003#1.1"
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-003#1.0",
      "PRB02-003#1.1"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-004:0",
    "cardNumber": "PRB02-004",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "GRANT_KEYWORD",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "keyword": "BLOCKER",
          "duration": {
            "kind": "PERMANENT"
          }
        },
        "actionId": "PRB02-004#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-004#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-004:1",
    "cardNumber": "PRB02-004",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[On Your Opponent's Attack] [Once Per Turn] Set up to 1 of your DON!! cards as active.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_OPPONENT_ATTACK"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "SET_DON_ACTIVE",
          "selector": {
            "subject": "DON",
            "owner": "PLAYER",
            "zones": [
              "COST_AREA"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          }
        },
        "actionId": "PRB02-004#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-004#1.0"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-005:0",
    "cardNumber": "PRB02-005",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": " [Your Turn] [On Play] If your Leader is multicolored and your opponent has 7 or less DON!! cards on their field, your opponent rests 1 of their active DON!! cards at the start of their next Main Phase.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "conditions": {
        "kind": "AND",
        "conditions": [
          {
            "kind": "PREDICATE",
            "left": {
              "kind": "CURRENT_TURN_PLAYER"
            },
            "operator": "EQUAL",
            "right": {
              "kind": "EFFECT_OWNER"
            }
          },
          {
            "kind": "PREDICATE",
            "left": {
              "kind": "COUNT",
              "selector": {
                "subject": "CARD",
                "controller": "PLAYER",
                "zones": [
                  "LEADER_AREA"
                ],
                "cardCategories": [
                  "LEADER"
                ],
                "colors": {
                  "kind": "HAS_ANY_COLOR",
                  "values": []
                },
                "quantity": {
                  "kind": "ANY_NUMBER"
                },
                "relations": [
                  "MULTICOLORED"
                ]
              }
            },
            "operator": "GREATER_OR_EQUAL",
            "right": {
              "kind": "NUMBER",
              "value": 1
            }
          }
        ]
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "CREATE_DELAYED_EFFECT",
          "effect": {
            "id": "delayed:opponent-rest-active-don-next-main",
            "source": {
              "objectRef": "GENERATED_EFFECT",
              "owner": "PLAYER",
              "controller": "PLAYER",
              "sourceZone": "NONE"
            },
            "category": "AUTO",
            "applicationMode": "ONE_SHOT",
            "activationZones": [
              "LEADER_AREA",
              "CHARACTER_AREA",
              "STAGE_AREA"
            ],
            "optionality": "MANDATORY",
            "resolution": {
              "kind": "ACTION",
              "action": {
                "type": "REST_DON",
                "selector": {
                  "subject": "DON",
                  "owner": "OPPONENT",
                  "zones": [
                    "COST_AREA"
                  ],
                  "states": [
                    "ACTIVE"
                  ],
                  "quantity": {
                    "kind": "EXACTLY",
                    "value": {
                      "kind": "NUMBER",
                      "value": 1
                    }
                  },
                  "chooser": "OPPONENT"
                }
              }
            },
            "metadata": {
              "sourceCardNumber": "GENERATED",
              "effectIndex": 0,
              "printedText": "If your Leader is multicolored and your opponent has 7 or less DON!! cards on their field, your opponent rests 1 of their active DON!! cards at the start of their next Main Phase.",
              "authoringStatus": "PARSED_ONLY"
            },
            "timing": {
              "kind": "CUSTOM_EVENT",
              "eventType": "PHASE_STARTED",
              "actor": "OPPONENT",
              "conditions": {
                "kind": "PREDICATE",
                "left": {
                  "kind": "PHASE"
                },
                "operator": "EQUAL",
                "right": {
                  "kind": "STRING",
                  "value": "MAIN_PHASE"
                }
              }
            }
          },
          "duration": {
            "kind": "UNTIL_END_OF_NEXT_TURN",
            "player": "OPPONENT"
          }
        },
        "actionId": "PRB02-005#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-005#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-006:0",
    "cardNumber": "PRB02-006",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Opponent's Turn] If this Character would be rested by your opponent's Character's effect, you may rest 1 of your other Characters instead.",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "conditions": {
        "kind": "PREDICATE",
        "left": {
          "kind": "CURRENT_TURN_PLAYER"
        },
        "operator": "EQUAL",
        "right": {
          "kind": "EFFECT_OPPONENT"
        }
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "CREATE_REPLACEMENT_EFFECT",
          "effect": {
            "id": "replacement:generated",
            "source": {
              "objectRef": "GENERATED_EFFECT",
              "owner": "PLAYER",
              "controller": "PLAYER",
              "sourceZone": "NONE"
            },
            "category": "REPLACEMENT",
            "applicationMode": "CONTINUOUS",
            "activationZones": [
              "LEADER_AREA",
              "CHARACTER_AREA",
              "STAGE_AREA"
            ],
            "optionality": "OPTIONAL",
            "resolution": {
              "kind": "ACTION",
              "action": {
                "type": "REST_CARD",
                "selector": {
                  "subject": "CARD",
                  "controller": "PLAYER",
                  "zones": [
                    "CHARACTER_AREA"
                  ],
                  "cardCategories": [
                    "CHARACTER"
                  ],
                  "quantity": {
                    "kind": "EXACTLY",
                    "value": {
                      "kind": "NUMBER",
                      "value": 1
                    }
                  },
                  "chooser": "EFFECT_OWNER"
                }
              }
            },
            "metadata": {
              "sourceCardNumber": "GENERATED",
              "effectIndex": 0,
              "printedText": "If this Character would be rested by your opponent's Character's effect, you may rest 1 of your other Characters instead.",
              "authoringStatus": "PARSED_ONLY"
            },
            "timing": {
              "kind": "CUSTOM_EVENT",
              "eventType": "CARD_WOULD_REST",
              "subject": {
                "subject": "CARD",
                "relations": [
                  "THIS_CARD"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "sourceSelector": {
                "subject": "EFFECT",
                "controller": "OPPONENT",
                "quantity": {
                  "kind": "ANY_NUMBER"
                }
              },
              "conditions": {
                "kind": "PREDICATE",
                "left": {
                  "kind": "REST_CAUSE"
                },
                "operator": "EQUAL",
                "right": {
                  "kind": "STRING",
                  "value": "EFFECT"
                }
              }
            }
          },
          "duration": {
            "kind": "PERMANENT"
          }
        },
        "actionId": "PRB02-006#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-006#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-006:1",
    "cardNumber": "PRB02-006",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[Blocker]",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "GRANT_KEYWORD",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "keyword": "BLOCKER",
          "duration": {
            "kind": "PERMANENT"
          }
        },
        "actionId": "PRB02-006#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-006#1.0"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-007:0",
    "cardNumber": "PRB02-007",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[On Play] Look at 5 cards from the top of your deck; reveal up to 1 {The Seven Warlords of the Sea} type card other than [Jinbe] and add it to your hand. Then, place the rest at the bottom of your deck in any order.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "LOOK_AT_CARDS",
              "player": "PLAYER",
              "source": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "DECK"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 5
                  }
                },
                "ordering": "DECK_ORDER"
              },
              "count": {
                "kind": "NUMBER",
                "value": 5
              }
            },
            "actionId": "PRB02-007#0.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "MOVE_CARD",
              "selector": {
                "subject": "CARD",
                "quantity": {
                  "kind": "UP_TO",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER",
                "types": {
                  "kind": "HAS_ANY_TYPE",
                  "values": [
                    "The Seven Warlords of the Sea"
                  ]
                },
                "names": [
                  {
                    "kind": "NAME_NOT",
                    "value": "Jinbe"
                  }
                ],
                "owner": "PLAYER",
                "zones": [
                  "DECK"
                ]
              },
              "to": {
                "zone": "HAND",
                "owner": "PLAYER"
              },
              "cause": "EFFECT"
            },
            "actionId": "PRB02-007#0.1"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "REORDER_CARDS",
              "selector": {
                "subject": "ACTION_RESULT",
                "relations": [
                  "REMAINDER_OF_PREVIOUS_SELECTION"
                ],
                "quantity": {
                  "kind": "ANY_NUMBER"
                }
              },
              "destination": {
                "zone": "DECK",
                "owner": "PLAYER",
                "position": "BOTTOM"
              },
              "orderChooser": "PLAYER"
            },
            "actionId": "PRB02-007#0.2"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-007#0.0",
      "PRB02-007#0.1",
      "PRB02-007#0.2"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-007:1",
    "cardNumber": "PRB02-007",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[When Attacking] Place up to 1 Character with a cost of 1 or less at the bottom of the owner's deck.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "WHEN_ATTACKING"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "MOVE_CARD",
          "selector": {
            "subject": "CARD",
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "to": {
            "zone": "DECK",
            "owner": "CARD_OWNER",
            "position": "BOTTOM"
          },
          "cause": "EFFECT"
        },
        "actionId": "PRB02-007#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-007#1.0"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-008:0",
    "cardNumber": "PRB02-008",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "GRANT_KEYWORD",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "keyword": "BLOCKER",
          "duration": {
            "kind": "PERMANENT"
          }
        },
        "actionId": "PRB02-008#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-008#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-008:1",
    "cardNumber": "PRB02-008",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[On K.O.] Draw 2 cards.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_KO"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "DRAW_CARD",
          "player": "PLAYER",
          "count": {
            "kind": "NUMBER",
            "value": 2
          }
        },
        "actionId": "PRB02-008#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-008#1.0"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-009:0",
    "cardNumber": "PRB02-009",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "This effect can be activated when this Character is rested by your opponent's effect. You may trash this Character and draw 2 cards.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "CUSTOM_EVENT",
        "eventType": "CARD_RESTED",
        "subject": {
          "subject": "CARD",
          "relations": [
            "THIS_CARD"
          ],
          "quantity": {
            "kind": "EXACTLY",
            "value": {
              "kind": "NUMBER",
              "value": 1
            }
          },
          "chooser": "EFFECT_OWNER"
        },
        "sourceSelector": {
          "subject": "EFFECT",
          "controller": "OPPONENT",
          "quantity": {
            "kind": "ANY_NUMBER"
          }
        },
        "conditions": {
          "kind": "PREDICATE",
          "left": {
            "kind": "REST_CAUSE"
          },
          "operator": "EQUAL",
          "right": {
            "kind": "STRING",
            "value": "EFFECT"
          }
        }
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "TRASH_CARD",
              "selector": {
                "subject": "CARD",
                "relations": [
                  "THIS_CARD"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "cause": "EFFECT"
            },
            "actionId": "PRB02-009#0.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "DRAW_CARD",
              "player": "PLAYER",
              "count": {
                "kind": "NUMBER",
                "value": 2
              }
            },
            "actionId": "PRB02-009#0.1"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-009#0.0",
      "PRB02-009#0.1"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-009:1",
    "cardNumber": "PRB02-009",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[Blocker]",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "GRANT_KEYWORD",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "keyword": "BLOCKER",
          "duration": {
            "kind": "PERMANENT"
          }
        },
        "actionId": "PRB02-009#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-009#1.0"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-010:0",
    "cardNumber": "PRB02-010",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[On Play] DON!! −2: If your Leader has the {Big Mom Pirates} type and your opponent has 6 or more DON!! cards on their field, draw 2 cards. Then, play up to 1 {Big Mom Pirates} type Character card with 6000 to 8000 power from your hand.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "activationCost": {
        "payments": [
          {
            "type": "DON_MINUS_COST",
            "count": {
              "kind": "NUMBER",
              "value": 2
            },
            "selectableZones": [
              "COST_AREA"
            ]
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "IF",
        "condition": {
          "kind": "PREDICATE",
          "left": {
            "kind": "COUNT",
            "selector": {
              "subject": "CARD",
              "controller": "PLAYER",
              "zones": [
                "LEADER_AREA"
              ],
              "cardCategories": [
                "LEADER"
              ],
              "types": {
                "kind": "TYPE_INCLUDES_TEXT",
                "values": [
                  "Big Mom Pirates"
                ]
              },
              "quantity": {
                "kind": "ANY_NUMBER"
              }
            }
          },
          "operator": "GREATER_OR_EQUAL",
          "right": {
            "kind": "NUMBER",
            "value": 1
          }
        },
        "then": {
          "kind": "SEQUENCE",
          "nodes": [
            {
              "kind": "ACTION",
              "action": {
                "type": "DRAW_CARD",
                "player": "PLAYER",
                "count": {
                  "kind": "NUMBER",
                  "value": 2
                }
              },
              "actionId": "PRB02-010#0.1"
            },
            {
              "kind": "ACTION",
              "action": {
                "type": "PLAY_CARD",
                "selector": {
                  "subject": "CARD",
                  "owner": "PLAYER",
                  "zones": [
                    "HAND"
                  ],
                  "quantity": {
                    "kind": "UP_TO",
                    "value": {
                      "kind": "NUMBER",
                      "value": 1
                    }
                  },
                  "chooser": "EFFECT_OWNER",
                  "types": {
                    "kind": "HAS_ANY_TYPE",
                    "values": [
                      "Big Mom Pirates"
                    ]
                  }
                },
                "player": "PLAYER"
              },
              "actionId": "PRB02-010#0.2"
            }
          ]
        }
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-010#0.0",
      "PRB02-010#0.1",
      "PRB02-010#0.2"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-011:0",
    "cardNumber": "PRB02-011",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Blocker] [On Play] If your Leader is multicolored, add up to 1 DON!! card from your DON!! deck and rest it.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "conditions": {
        "kind": "PREDICATE",
        "left": {
          "kind": "COUNT",
          "selector": {
            "subject": "CARD",
            "controller": "PLAYER",
            "zones": [
              "LEADER_AREA"
            ],
            "cardCategories": [
              "LEADER"
            ],
            "colors": {
              "kind": "HAS_ANY_COLOR",
              "values": []
            },
            "quantity": {
              "kind": "ANY_NUMBER"
            },
            "relations": [
              "MULTICOLORED"
            ]
          }
        },
        "operator": "GREATER_OR_EQUAL",
        "right": {
          "kind": "NUMBER",
          "value": 1
        }
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "GRANT_KEYWORD",
              "selector": {
                "subject": "CARD",
                "relations": [
                  "THIS_CARD"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "keyword": "BLOCKER",
              "duration": {
                "kind": "PERMANENT"
              }
            },
            "actionId": "PRB02-011#0.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "ADD_DON_FROM_DON_DECK",
              "player": "PLAYER",
              "count": {
                "kind": "NUMBER",
                "value": 1
              },
              "destination": "COST_AREA",
              "state": "RESTED"
            },
            "actionId": "PRB02-011#0.1"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-011#0.0",
      "PRB02-011#0.1"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-012:0",
    "cardNumber": "PRB02-012",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[On Play] Look at 5 cards from the top of your deck; reveal up to 1 {Straw Hat Crew} type card other than [Nami] and add it to your hand. Then, place the rest at the bottom of your deck in any order.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "LOOK_AT_CARDS",
              "player": "PLAYER",
              "source": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "DECK"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 5
                  }
                },
                "ordering": "DECK_ORDER"
              },
              "count": {
                "kind": "NUMBER",
                "value": 5
              }
            },
            "actionId": "PRB02-012#0.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "MOVE_CARD",
              "selector": {
                "subject": "CARD",
                "quantity": {
                  "kind": "UP_TO",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER",
                "types": {
                  "kind": "HAS_ANY_TYPE",
                  "values": [
                    "Straw Hat Crew"
                  ]
                },
                "names": [
                  {
                    "kind": "NAME_NOT",
                    "value": "Nami"
                  }
                ],
                "owner": "PLAYER",
                "zones": [
                  "DECK"
                ]
              },
              "to": {
                "zone": "HAND",
                "owner": "PLAYER"
              },
              "cause": "EFFECT"
            },
            "actionId": "PRB02-012#0.1"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "REORDER_CARDS",
              "selector": {
                "subject": "ACTION_RESULT",
                "relations": [
                  "REMAINDER_OF_PREVIOUS_SELECTION"
                ],
                "quantity": {
                  "kind": "ANY_NUMBER"
                }
              },
              "destination": {
                "zone": "DECK",
                "owner": "PLAYER",
                "position": "BOTTOM"
              },
              "orderChooser": "PLAYER"
            },
            "actionId": "PRB02-012#0.2"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-012#0.0",
      "PRB02-012#0.1",
      "PRB02-012#0.2"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-012:1",
    "cardNumber": "PRB02-012",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[Trigger] Play this card.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "TRIGGER"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "PLAY_CARD",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "player": "PLAYER"
        },
        "actionId": "PRB02-012#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-012#1.0"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-013:0",
    "cardNumber": "PRB02-013",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[On Play] If your Leader has the {Thriller Bark Pirates} type, play up to 1 Character card with a cost of 4 or less from your trash rested. Then, give up to 1 rested DON!! card to your Leader or 1 of your Characters.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "conditions": {
        "kind": "PREDICATE",
        "left": {
          "kind": "COUNT",
          "selector": {
            "subject": "CARD",
            "controller": "PLAYER",
            "zones": [
              "LEADER_AREA"
            ],
            "cardCategories": [
              "LEADER"
            ],
            "types": {
              "kind": "TYPE_INCLUDES_TEXT",
              "values": [
                "Thriller Bark Pirates"
              ]
            },
            "quantity": {
              "kind": "ANY_NUMBER"
            }
          }
        },
        "operator": "GREATER_OR_EQUAL",
        "right": {
          "kind": "NUMBER",
          "value": 1
        }
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "PLAY_CARD",
              "selector": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "TRASH"
                ],
                "quantity": {
                  "kind": "UP_TO",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER",
                "cost": {
                  "propertyLayer": "CURRENT",
                  "comparison": "AT_MOST",
                  "value": {
                    "kind": "NUMBER",
                    "value": 4
                  }
                }
              },
              "player": "PLAYER"
            },
            "actionId": "PRB02-013#0.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "GIVE_DON",
              "donSelector": {
                "subject": "DON",
                "owner": "PLAYER",
                "zones": [
                  "COST_AREA"
                ],
                "states": [
                  "RESTED"
                ],
                "quantity": {
                  "kind": "UP_TO",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "target": {
                "subject": "CARD",
                "controller": "PLAYER",
                "zones": [
                  "LEADER_AREA",
                  "CHARACTER_AREA"
                ],
                "cardCategories": [
                  "LEADER",
                  "CHARACTER"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              }
            },
            "actionId": "PRB02-013#0.1"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-013#0.0",
      "PRB02-013#0.1"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-014:0",
    "cardNumber": "PRB02-014",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "If you have 15 or more cards in your trash, give this card in your hand −3 cost.",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "conditions": {
        "kind": "PREDICATE",
        "left": {
          "kind": "COUNT",
          "selector": {
            "subject": "CARD",
            "owner": "PLAYER",
            "zones": [
              "TRASH"
            ],
            "quantity": {
              "kind": "ANY_NUMBER"
            }
          }
        },
        "operator": "GREATER_OR_EQUAL",
        "right": {
          "kind": "NUMBER",
          "value": 15
        }
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "MODIFY_COST",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "propertyLayer": "CURRENT_VALUE",
          "operation": "SUBTRACT",
          "value": {
            "kind": "NUMBER",
            "value": 3
          },
          "duration": {
            "kind": "PERMANENT"
          }
        },
        "actionId": "PRB02-014#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-014#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-014:1",
    "cardNumber": "PRB02-014",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "GRANT_KEYWORD",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "keyword": "BLOCKER",
          "duration": {
            "kind": "PERMANENT"
          }
        },
        "actionId": "PRB02-014#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-014#1.0"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-015:0",
    "cardNumber": "PRB02-015",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "If your Leader has the {Blackbeard Pirates} type, this Character gains [Blocker] and +4 cost.",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "conditions": {
        "kind": "PREDICATE",
        "left": {
          "kind": "COUNT",
          "selector": {
            "subject": "CARD",
            "controller": "PLAYER",
            "zones": [
              "LEADER_AREA"
            ],
            "cardCategories": [
              "LEADER"
            ],
            "types": {
              "kind": "TYPE_INCLUDES_TEXT",
              "values": [
                "Blackbeard Pirates"
              ]
            },
            "quantity": {
              "kind": "ANY_NUMBER"
            }
          }
        },
        "operator": "GREATER_OR_EQUAL",
        "right": {
          "kind": "NUMBER",
          "value": 1
        }
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "GRANT_KEYWORD",
              "selector": {
                "subject": "CARD",
                "relations": [
                  "THIS_CARD"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "keyword": "BLOCKER",
              "duration": {
                "kind": "PERMANENT"
              }
            },
            "actionId": "PRB02-015#0.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "MODIFY_COST",
              "selector": {
                "subject": "CARD",
                "relations": [
                  "THIS_CARD"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "propertyLayer": "CURRENT_VALUE",
              "operation": "ADD",
              "value": {
                "kind": "NUMBER",
                "value": 4
              },
              "duration": {
                "kind": "PERMANENT"
              }
            },
            "actionId": "PRB02-015#0.1"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-015#0.0",
      "PRB02-015#0.1"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-015:1",
    "cardNumber": "PRB02-015",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[On K.O.] If your Leader has the {Blackbeard Pirates} type, K.O. up to 1 of your opponent's Characters with a base cost of 4 or less.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_KO"
      },
      "conditions": {
        "kind": "PREDICATE",
        "left": {
          "kind": "COUNT",
          "selector": {
            "subject": "CARD",
            "controller": "PLAYER",
            "zones": [
              "LEADER_AREA"
            ],
            "cardCategories": [
              "LEADER"
            ],
            "types": {
              "kind": "TYPE_INCLUDES_TEXT",
              "values": [
                "Blackbeard Pirates"
              ]
            },
            "quantity": {
              "kind": "ANY_NUMBER"
            }
          }
        },
        "operator": "GREATER_OR_EQUAL",
        "right": {
          "kind": "NUMBER",
          "value": 1
        }
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "KO_CARD",
          "selector": {
            "subject": "CARD",
            "controller": "OPPONENT",
            "zones": [
              "CHARACTER_AREA"
            ],
            "cardCategories": [
              "CHARACTER"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER",
            "cost": {
              "propertyLayer": "CURRENT",
              "comparison": "AT_MOST",
              "value": {
                "kind": "NUMBER",
                "value": 4
              }
            }
          },
          "cause": "EFFECT"
        },
        "actionId": "PRB02-015#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-015#1.0"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-016:0",
    "cardNumber": "PRB02-016",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Activate: Main] You may rest this Character and add 1 card from the top or bottom of your Life cards to your hand: Up to 1 of your Leader or Character cards gains +3000 power during this turn.",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ACTIVATE_MAIN"
      },
      "activationCost": {
        "payments": [
          {
            "type": "REST_CARD_COST",
            "selector": {
              "subject": "CARD",
              "relations": [
                "THIS_CARD"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "chooser": "EFFECT_OWNER"
            }
          },
          {
            "type": "ADD_LIFE_TO_HAND_COST",
            "selector": {
              "subject": "CARD",
              "owner": "PLAYER",
              "zones": [
                "LIFE"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "ordering": "DECK_ORDER"
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "MODIFY_POWER",
          "selector": {
            "subject": "CARD",
            "controller": "PLAYER",
            "zones": [
              "LEADER_AREA",
              "CHARACTER_AREA"
            ],
            "cardCategories": [
              "LEADER",
              "CHARACTER"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "propertyLayer": "CURRENT_VALUE",
          "operation": "ADD",
          "value": {
            "kind": "NUMBER",
            "value": 3000
          },
          "duration": {
            "kind": "THIS_TURN"
          }
        },
        "actionId": "PRB02-016#0.1"
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-016#0.0",
      "PRB02-016#0.1"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-016:1",
    "cardNumber": "PRB02-016",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[Trigger] Rest up to 1 of your opponent's Characters with a cost of 4 or less.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "TRIGGER"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "REST_CARD",
          "selector": {
            "subject": "CARD",
            "controller": "OPPONENT",
            "zones": [
              "CHARACTER_AREA"
            ],
            "cardCategories": [
              "CHARACTER"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER",
            "cost": {
              "propertyLayer": "CURRENT",
              "comparison": "AT_MOST",
              "value": {
                "kind": "NUMBER",
                "value": 4
              }
            }
          }
        },
        "actionId": "PRB02-016#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-016#1.0"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-017:0",
    "cardNumber": "PRB02-017",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[On Play] You may trash 1 card with a [Trigger] from your hand: Your opponent's rested Leader or up to 1 of your opponent's Characters other than [Monkey.D.Luffy] cannot attack until the end of your opponent's next End Phase.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "activationCost": {
        "payments": [
          {
            "type": "TRASH_CARD_COST",
            "selector": {
              "subject": "CARD",
              "owner": "PLAYER",
              "zones": [
                "HAND"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "chooser": "EFFECT_OWNER"
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "PREVENT_ACTION",
          "selector": {
            "subject": "CARD",
            "controller": "OPPONENT",
            "zones": [
              "CHARACTER_AREA"
            ],
            "cardCategories": [
              "CHARACTER"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER",
            "names": [
              {
                "kind": "NAME_NOT",
                "value": "Monkey.D.Luffy"
              }
            ]
          },
          "action": "DECLARE_ATTACK",
          "duration": {
            "kind": "INSTANT"
          }
        },
        "actionId": "PRB02-017#0.1"
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-017#0.0",
      "PRB02-017#0.1"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-017:1",
    "cardNumber": "PRB02-017",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[Trigger] K.O. up to 1 of your opponent's Characters with a cost of 4 or less.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "TRIGGER"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "KO_CARD",
          "selector": {
            "subject": "CARD",
            "controller": "OPPONENT",
            "zones": [
              "CHARACTER_AREA"
            ],
            "cardCategories": [
              "CHARACTER"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER",
            "cost": {
              "propertyLayer": "CURRENT",
              "comparison": "AT_MOST",
              "value": {
                "kind": "NUMBER",
                "value": 4
              }
            }
          },
          "cause": "EFFECT"
        },
        "actionId": "PRB02-017#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-017#1.0"
    ]
  },
  {
    "assignmentId": "v2:auto:PRB02-018:0",
    "cardNumber": "PRB02-018",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[On Play] If you have a face-up Life card, play up to 1 [Sabo], [Portgas.D.Ace], or [Monkey.D.Luffy] with a cost of 2 from your hand or trash.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "PLAY_CARD",
          "selector": {
            "subject": "CARD",
            "owner": "PLAYER",
            "zones": [
              "HAND"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER",
            "names": [
              {
                "kind": "NAME_EXACT",
                "value": "Sabo"
              },
              {
                "kind": "NAME_EXACT",
                "value": "Portgas.D.Ace"
              },
              {
                "kind": "NAME_EXACT",
                "value": "Monkey.D.Luffy"
              }
            ]
          },
          "player": "PLAYER"
        },
        "actionId": "PRB02-018#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "PRB02-018#0.0"
    ]
  }
] satisfies readonly EffectAssignment_V2[];
