// Auto-curated V2 assignments for ST17.
// Generated by npm run effects:v2 from fully parser-recognized canonical atoms.
// Review before copying into src/cards/effectCompiler_V2/assignments/<SET>_V2.ts.
import type { EffectAssignment_V2 } from '../../src/cards/effectCompiler_V2/types_V2';

export const ST17_AUTO_ASSIGNMENTS_V2 = [
  {
    "assignmentId": "v2:auto:ST17-001:0",
    "cardNumber": "ST17-001",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[On Play] Reveal 1 card from the top of your deck. If that card is a {The Seven Warlords of the Sea} type card, draw 2 cards and place 1 card from your hand at the top of your deck.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "REVEAL_CARD",
              "selector": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "DECK"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "ordering": "DECK_ORDER"
              },
              "viewers": "BOTH_PLAYERS"
            },
            "actionId": "ST17-001#0.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "DRAW_CARD",
              "player": "PLAYER",
              "count": {
                "kind": "NUMBER",
                "value": 2
              }
            },
            "actionId": "ST17-001#0.1"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST17-001#0.0",
      "ST17-001#0.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST17-002:0",
    "cardNumber": "ST17-002",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[On Play] You may return 1 of your Characters to the owner's hand: If your Leader has the {The Seven Warlords of the Sea} type, return up to 1 Character with a cost of 4 or less to the owner's hand.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "activationCost": {
        "payments": [
          {
            "type": "RETURN_CARD_TO_HAND_COST",
            "selector": {
              "subject": "CARD",
              "controller": "PLAYER",
              "zones": [
                "CHARACTER_AREA"
              ],
              "cardCategories": [
                "CHARACTER"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "chooser": "EFFECT_OWNER"
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "IF",
        "condition": {
          "kind": "PREDICATE",
          "left": {
            "kind": "COUNT",
            "selector": {
              "subject": "CARD",
              "controller": "PLAYER",
              "zones": [
                "LEADER_AREA"
              ],
              "cardCategories": [
                "LEADER"
              ],
              "types": {
                "kind": "TYPE_INCLUDES_TEXT",
                "values": [
                  "The Seven Warlords of the Sea"
                ]
              },
              "quantity": {
                "kind": "ANY_NUMBER"
              }
            }
          },
          "operator": "GREATER_OR_EQUAL",
          "right": {
            "kind": "NUMBER",
            "value": 1
          }
        },
        "then": {
          "kind": "ACTION",
          "action": {
            "type": "MOVE_CARD",
            "selector": {
              "subject": "CARD",
              "zones": [
                "CHARACTER_AREA"
              ],
              "cardCategories": [
                "CHARACTER"
              ],
              "quantity": {
                "kind": "UP_TO",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "chooser": "EFFECT_OWNER",
              "cost": {
                "propertyLayer": "CURRENT",
                "comparison": "AT_MOST",
                "value": {
                  "kind": "NUMBER",
                  "value": 4
                }
              }
            },
            "to": {
              "zone": "HAND",
              "owner": "CARD_OWNER"
            },
            "cause": "EFFECT"
          },
          "actionId": "ST17-002#0.1"
        }
      }
    },
    "coveredAtomicEffectIds": [
      "ST17-002#0.0",
      "ST17-002#0.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST17-003:0",
    "cardNumber": "ST17-003",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[On Play] Look at 3 cards from the top of your deck and place them at the top of your deck in any order.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "LOOK_AT_CARDS",
              "player": "PLAYER",
              "source": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "DECK"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 3
                  }
                },
                "ordering": "DECK_ORDER"
              },
              "count": {
                "kind": "NUMBER",
                "value": 3
              }
            },
            "actionId": "ST17-003#0.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "MOVE_CARD",
              "selector": {
                "subject": "ACTION_RESULT",
                "relations": [
                  "REMAINDER_OF_PREVIOUS_SELECTION"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                }
              },
              "to": {
                "zone": "DECK",
                "owner": "PLAYER",
                "position": "TOP"
              },
              "cause": "EFFECT"
            },
            "actionId": "ST17-003#0.1"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST17-003#0.0",
      "ST17-003#0.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST17-004:0",
    "cardNumber": "ST17-004",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "GRANT_KEYWORD",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "keyword": "BLOCKER",
          "duration": {
            "kind": "PERMANENT"
          }
        },
        "actionId": "ST17-004#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST17-004#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST17-004:1",
    "cardNumber": "ST17-004",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[On Play] Look at 3 cards from the top of your deck and place them at the top or bottom of your deck in any order. Then, give up to 1 rested DON!! card to 1 of your {The Seven Warlords of the Sea} type Leader or Character cards.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "LOOK_AT_CARDS",
              "player": "PLAYER",
              "source": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "DECK"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 3
                  }
                },
                "ordering": "DECK_ORDER"
              },
              "count": {
                "kind": "NUMBER",
                "value": 3
              }
            },
            "actionId": "ST17-004#1.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "REORDER_CARDS",
              "selector": {
                "subject": "ACTION_RESULT",
                "relations": [
                  "SELECTED_PREVIOUSLY"
                ],
                "quantity": {
                  "kind": "ANY_NUMBER"
                }
              },
              "destination": {
                "zone": "DECK",
                "owner": "PLAYER",
                "position": "TOP"
              },
              "orderChooser": "PLAYER"
            },
            "actionId": "ST17-004#1.1"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "GIVE_DON",
              "donSelector": {
                "subject": "DON",
                "owner": "PLAYER",
                "zones": [
                  "COST_AREA"
                ],
                "states": [
                  "RESTED"
                ],
                "quantity": {
                  "kind": "UP_TO",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "target": {
                "subject": "CARD",
                "controller": "PLAYER",
                "zones": [
                  "LEADER_AREA",
                  "CHARACTER_AREA"
                ],
                "cardCategories": [
                  "LEADER",
                  "CHARACTER"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER",
                "types": {
                  "kind": "HAS_ANY_TYPE",
                  "values": [
                    "The Seven Warlords of the Sea"
                  ]
                }
              }
            },
            "actionId": "ST17-004#1.2"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST17-004#1.0",
      "ST17-004#1.1",
      "ST17-004#1.2"
    ]
  },
  {
    "assignmentId": "v2:auto:ST17-005:0",
    "cardNumber": "ST17-005",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Activate: Main] [Once Per Turn] You may place 1 card from your hand at the top of your deck: Give up to 2 rested DON!! cards to your Leader or 1 of your Characters.",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ACTIVATE_MAIN"
      },
      "activationCost": {
        "payments": [
          {
            "type": "RETURN_CARD_TO_DECK_COST",
            "position": "TOP",
            "selector": {
              "subject": "CARD",
              "owner": "PLAYER",
              "zones": [
                "HAND"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "chooser": "EFFECT_OWNER"
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "GIVE_DON",
          "donSelector": {
            "subject": "DON",
            "owner": "PLAYER",
            "zones": [
              "COST_AREA"
            ],
            "states": [
              "RESTED"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 2
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "target": {
            "subject": "CARD",
            "controller": "PLAYER",
            "zones": [
              "LEADER_AREA",
              "CHARACTER_AREA"
            ],
            "cardCategories": [
              "LEADER",
              "CHARACTER"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          }
        },
        "actionId": "ST17-005#0.1"
      }
    },
    "coveredAtomicEffectIds": [
      "ST17-005#0.0",
      "ST17-005#0.1"
    ]
  }
] satisfies readonly EffectAssignment_V2[];
