// Auto-curated V2 assignments for ST25.
// Generated by npm run effects:v2 from fully parser-recognized canonical atoms.
// Review before copying into src/cards/effectCompiler_V2/assignments/<SET>_V2.ts.
import type { EffectAssignment_V2 } from '../../src/cards/effectCompiler_V2/types_V2';

export const ST25_AUTO_ASSIGNMENTS_V2 = [
  {
    "assignmentId": "v2:auto:ST25-001:0",
    "cardNumber": "ST25-001",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "If you have 2 or more Characters with a base cost of 5 or more, this Character gains +1 cost.",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "MODIFY_COST",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "propertyLayer": "CURRENT_VALUE",
          "operation": "ADD",
          "value": {
            "kind": "NUMBER",
            "value": 1
          },
          "duration": {
            "kind": "PERMANENT"
          }
        },
        "actionId": "ST25-001#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST25-001#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST25-001:1",
    "cardNumber": "ST25-001",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[On Play] If your Leader is [Buggy], draw 3 cards and trash 2 cards from your hand.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "conditions": {
        "kind": "PREDICATE",
        "left": {
          "kind": "COUNT",
          "selector": {
            "subject": "CARD",
            "controller": "PLAYER",
            "zones": [
              "LEADER_AREA"
            ],
            "cardCategories": [
              "LEADER"
            ],
            "names": [
              {
                "kind": "NAME_EXACT",
                "value": "Buggy"
              }
            ],
            "quantity": {
              "kind": "ANY_NUMBER"
            }
          }
        },
        "operator": "GREATER_OR_EQUAL",
        "right": {
          "kind": "NUMBER",
          "value": 1
        }
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "DRAW_CARD",
              "player": "PLAYER",
              "count": {
                "kind": "NUMBER",
                "value": 3
              }
            },
            "actionId": "ST25-001#1.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "TRASH_CARD",
              "selector": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "HAND"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 2
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "cause": "EFFECT"
            },
            "actionId": "ST25-001#1.1"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST25-001#1.0",
      "ST25-001#1.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST25-002:0",
    "cardNumber": "ST25-002",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "If you have 2 or more Characters with a base cost of 5 or more, this Character gains [Blocker] and +1 cost.(After your opponent declares an attack, you may rest this card to make it the new target of the attack.)[Opponent's Turn] This Character gains +5000 power.",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "GRANT_KEYWORD",
              "selector": {
                "subject": "CARD",
                "relations": [
                  "THIS_CARD"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "keyword": "BLOCKER",
              "duration": {
                "kind": "PERMANENT"
              }
            },
            "actionId": "ST25-002#0.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "MODIFY_COST",
              "selector": {
                "subject": "CARD",
                "relations": [
                  "THIS_CARD"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "propertyLayer": "CURRENT_VALUE",
              "operation": "ADD",
              "value": {
                "kind": "NUMBER",
                "value": 1
              },
              "duration": {
                "kind": "PERMANENT"
              }
            },
            "actionId": "ST25-002#0.1"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "MODIFY_POWER",
              "selector": {
                "subject": "CARD",
                "relations": [
                  "THIS_CARD"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "propertyLayer": "CURRENT_VALUE",
              "operation": "ADD",
              "value": {
                "kind": "NUMBER",
                "value": 5000
              },
              "duration": {
                "kind": "PERMANENT"
              }
            },
            "actionId": "ST25-002#0.2"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST25-002#0.0",
      "ST25-002#0.1",
      "ST25-002#0.2"
    ]
  },
  {
    "assignmentId": "v2:auto:ST25-003:0",
    "cardNumber": "ST25-003",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[On Play] Draw 2 cards and trash 1 card from your hand. Then, play up to 1 {Cross Guild} type Character card with a cost of 4 or less from your hand.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "DRAW_CARD",
              "player": "PLAYER",
              "count": {
                "kind": "NUMBER",
                "value": 2
              }
            },
            "actionId": "ST25-003#0.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "TRASH_CARD",
              "selector": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "HAND"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "cause": "EFFECT"
            },
            "actionId": "ST25-003#0.1"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "PLAY_CARD",
              "selector": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "HAND"
                ],
                "quantity": {
                  "kind": "UP_TO",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER",
                "types": {
                  "kind": "HAS_ANY_TYPE",
                  "values": [
                    "Cross Guild"
                  ]
                },
                "cost": {
                  "propertyLayer": "CURRENT",
                  "comparison": "AT_MOST",
                  "value": {
                    "kind": "NUMBER",
                    "value": 4
                  }
                }
              },
              "player": "PLAYER"
            },
            "actionId": "ST25-003#0.2"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST25-003#0.0",
      "ST25-003#0.1",
      "ST25-003#0.2"
    ]
  },
  {
    "assignmentId": "v2:auto:ST25-003:1",
    "cardNumber": "ST25-003",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[Once Per Turn] If your {Cross Guild} type Character would be removed from the field by your opponent's effect, you may trash 1 card from your hand instead.",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "CREATE_REPLACEMENT_EFFECT",
          "effect": {
            "id": "replacement:generated",
            "source": {
              "objectRef": "GENERATED_EFFECT",
              "owner": "PLAYER",
              "controller": "PLAYER",
              "sourceZone": "NONE"
            },
            "category": "REPLACEMENT",
            "applicationMode": "CONTINUOUS",
            "activationZones": [
              "LEADER_AREA",
              "CHARACTER_AREA",
              "STAGE_AREA"
            ],
            "optionality": "OPTIONAL",
            "resolution": {
              "kind": "ACTION",
              "action": {
                "type": "TRASH_CARD",
                "selector": {
                  "subject": "CARD",
                  "owner": "PLAYER",
                  "zones": [
                    "HAND"
                  ],
                  "quantity": {
                    "kind": "EXACTLY",
                    "value": {
                      "kind": "NUMBER",
                      "value": 1
                    }
                  },
                  "chooser": "EFFECT_OWNER"
                },
                "cause": "EFFECT"
              }
            },
            "metadata": {
              "sourceCardNumber": "GENERATED",
              "effectIndex": 0,
              "printedText": "If your {Cross Guild} type Character would be removed from the field by your opponent's effect, you may trash 1 card from your hand instead.",
              "authoringStatus": "PARSED_ONLY"
            },
            "timing": {
              "kind": "CUSTOM_EVENT",
              "eventType": "CARD_WOULD_MOVE",
              "subject": {
                "subject": "CARD",
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER",
                "types": {
                  "kind": "HAS_ANY_TYPE",
                  "values": [
                    "Cross Guild"
                  ]
                }
              },
              "fromZone": "CHARACTER_AREA",
              "sourceSelector": {
                "subject": "EFFECT",
                "controller": "OPPONENT",
                "quantity": {
                  "kind": "ANY_NUMBER"
                }
              },
              "conditions": {
                "kind": "PREDICATE",
                "left": {
                  "kind": "MOVE_CAUSE"
                },
                "operator": "EQUAL",
                "right": {
                  "kind": "STRING",
                  "value": "EFFECT"
                }
              }
            }
          },
          "duration": {
            "kind": "PERMANENT"
          }
        },
        "actionId": "ST25-003#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST25-003#1.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST25-004:0",
    "cardNumber": "ST25-004",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Activate: Main] You may trash 1 card from your hand and trash this Character: If your Leader is [Buggy], play up to 1 {Cross Guild} type Character card with a cost of 6 or less from your hand.",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ACTIVATE_MAIN"
      },
      "activationCost": {
        "payments": [
          {
            "type": "TRASH_CARD_COST",
            "selector": {
              "subject": "CARD",
              "owner": "PLAYER",
              "zones": [
                "HAND"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "chooser": "EFFECT_OWNER"
            }
          },
          {
            "type": "TRASH_CARD_COST",
            "selector": {
              "subject": "CARD",
              "relations": [
                "THIS_CARD"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "chooser": "EFFECT_OWNER"
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "IF",
        "condition": {
          "kind": "PREDICATE",
          "left": {
            "kind": "COUNT",
            "selector": {
              "subject": "CARD",
              "controller": "PLAYER",
              "zones": [
                "LEADER_AREA"
              ],
              "cardCategories": [
                "LEADER"
              ],
              "names": [
                {
                  "kind": "NAME_EXACT",
                  "value": "Buggy"
                }
              ],
              "quantity": {
                "kind": "ANY_NUMBER"
              }
            }
          },
          "operator": "GREATER_OR_EQUAL",
          "right": {
            "kind": "NUMBER",
            "value": 1
          }
        },
        "then": {
          "kind": "ACTION",
          "action": {
            "type": "PLAY_CARD",
            "selector": {
              "subject": "CARD",
              "owner": "PLAYER",
              "zones": [
                "HAND"
              ],
              "quantity": {
                "kind": "UP_TO",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "chooser": "EFFECT_OWNER",
              "types": {
                "kind": "HAS_ANY_TYPE",
                "values": [
                  "Cross Guild"
                ]
              },
              "cost": {
                "propertyLayer": "CURRENT",
                "comparison": "AT_MOST",
                "value": {
                  "kind": "NUMBER",
                  "value": 6
                }
              }
            },
            "player": "PLAYER"
          },
          "actionId": "ST25-004#0.1"
        }
      }
    },
    "coveredAtomicEffectIds": [
      "ST25-004#0.0",
      "ST25-004#0.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST25-005:0",
    "cardNumber": "ST25-005",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "If you have 2 or more Characters with a base cost of 5 or more, this Character gains [Blocker] and +1 cost.(After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "GRANT_KEYWORD",
              "selector": {
                "subject": "CARD",
                "relations": [
                  "THIS_CARD"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "keyword": "BLOCKER",
              "duration": {
                "kind": "PERMANENT"
              }
            },
            "actionId": "ST25-005#0.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "MODIFY_COST",
              "selector": {
                "subject": "CARD",
                "relations": [
                  "THIS_CARD"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "propertyLayer": "CURRENT_VALUE",
              "operation": "ADD",
              "value": {
                "kind": "NUMBER",
                "value": 1
              },
              "duration": {
                "kind": "PERMANENT"
              }
            },
            "actionId": "ST25-005#0.1"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST25-005#0.0",
      "ST25-005#0.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST25-005:1",
    "cardNumber": "ST25-005",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[On K.O.] If your Leader is [Buggy] and you have 3 or less cards in your hand, draw 1 card.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_KO"
      },
      "conditions": {
        "kind": "PREDICATE",
        "left": {
          "kind": "COUNT",
          "selector": {
            "subject": "CARD",
            "controller": "PLAYER",
            "zones": [
              "LEADER_AREA"
            ],
            "cardCategories": [
              "LEADER"
            ],
            "names": [
              {
                "kind": "NAME_EXACT",
                "value": "Buggy"
              }
            ],
            "quantity": {
              "kind": "ANY_NUMBER"
            }
          }
        },
        "operator": "GREATER_OR_EQUAL",
        "right": {
          "kind": "NUMBER",
          "value": 1
        }
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "DRAW_CARD",
          "player": "PLAYER",
          "count": {
            "kind": "NUMBER",
            "value": 1
          }
        },
        "actionId": "ST25-005#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST25-005#1.0"
    ]
  }
] satisfies readonly EffectAssignment_V2[];
