/**
 * Regenerates public/audio/sfx/manifest.json from the cue registry.
 *
 * The manifest is the human-facing side of the audio contract: what each cue
 * is FOR, and whether it is still waiting on a real recording. The registry in
 * src/audio/cues.ts is the machine-facing side. This script keeps the two from
 * drifting — run it whenever a cue is added, removed, or repointed at a new
 * asset (`npm run audio:manifest`).
 *
 * Briefs are carried over by cue id, so the sound-design notes written by hand
 * survive every regeneration. A cue with no brief yet gets a placeholder one
 * loud enough to notice.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { SOUND_CUES, SOUND_CUE_IDS } from '../../src/audio/cues';

const MANIFEST_PATH = join(process.cwd(), 'public', 'audio', 'sfx', 'manifest.json');
/** Assets under this prefix are real recordings, not generated placeholders. */
const REAL_ASSET_PREFIX = '/audio/sfx/src/';

interface ManifestCue {
  id: string;
  file: string;
  durationMs: number;
  placeholder: boolean;
  brief: string;
}

interface Manifest {
  $comment: string;
  generatedAt: string;
  sampleRate: number;
  cues: ManifestCue[];
}

const previous = JSON.parse(readFileSync(MANIFEST_PATH, 'utf-8')) as Manifest;
const priorById = new Map(previous.cues.map((c) => [c.id, c]));

const cues: ManifestCue[] = SOUND_CUE_IDS.map((id) => {
  const def = SOUND_CUES[id];
  const prior = priorById.get(id);
  return {
    id,
    file: def.src,
    durationMs: prior?.durationMs ?? 0,
    placeholder: !def.src.startsWith(REAL_ASSET_PREFIX),
    brief: prior?.brief ?? `TODO: describe the ${id} cue in one line.`,
  };
});

const real = cues.filter((c) => !c.placeholder).length;

const manifest: Manifest = {
  $comment:
    'GENERATED by scripts/audio/manifest.ts (npm run audio:manifest) from src/audio/cues.ts. ' +
    'Cues with placeholder:false play a real recording from /audio/sfx/src/, shared across cues and ' +
    'pitch-shifted per cue via detuneBiasCents. Cues with placeholder:true still play a synthesised ' +
    'stand-in from scripts/audio/generate.py — replace the .ogg in place, keep the filename.',
  generatedAt: new Date().toISOString().slice(0, 10),
  sampleRate: previous.sampleRate,
  cues,
};

writeFileSync(MANIFEST_PATH, `${JSON.stringify(manifest, null, 2)}\n`, 'utf-8');
console.log(`manifest: ${cues.length} cues, ${real} on real assets, ${cues.length - real} still placeholders`);
