/**
 * Partial curation scanner — finds PARTIAL/deferred/NOTE markers in assignment files.
 *
 *   npm run scan:partials
 *   npm run scan:partials OP15 OP16
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  emptyPartialByKind,
  enrichPartialFindings,
  partialCardNumberSet,
  scanPartialCurations,
  type PartialCurationFinding,
} from '../../src/cards/devMetrics';
import type { CatalogCard } from '../../src/cards/devMetrics/types';
import { loadAssignmentSources } from '../shared/loadAssignmentSources';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const SETS_DIR = resolve(ROOT, 'public', 'cards', 'sets');
const OUT_CSV = resolve(ROOT, 'effect-partial-curation.csv');
const OUT_MD = resolve(ROOT, 'effect-partial-curation.md');

function csv(value: unknown): string {
  const s = value == null ? '' : String(value);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function loadCatalog(): Map<string, CatalogCard> {
  const byNumber = new Map<string, CatalogCard>();
  if (!existsSync(SETS_DIR)) return byNumber;
  for (const f of readdirSync(SETS_DIR)) {
    if (!f.endsWith('.json')) continue;
    for (const c of JSON.parse(readFileSync(join(SETS_DIR, f), 'utf8')) as CatalogCard[]) {
      byNumber.set(c.cardNumber, c);
    }
  }
  return byNumber;
}

function writeReports(findings: PartialCurationFinding[], setFilter: Set<string>): void {
  const filtered = setFilter.size > 0
    ? findings.filter((f) => setFilter.has(f.setCode.toUpperCase()) || (f.cardNumber && setFilter.has(f.setCode.toUpperCase())))
    : findings;

  const rows = ['cardNumber,set,name,kind,hasAssignment,isStale,sourceFile,line,note,effectText'];
  for (const f of filtered) {
    rows.push(
      [f.cardNumber, f.setCode, f.name ?? '', f.kind, f.hasAssignment, f.isStale, f.sourceFile, f.line, f.note, f.effectText ?? '']
        .map(csv)
        .join(','),
    );
  }
  writeFileSync(OUT_CSV, rows.join('\n') + '\n', 'utf8');

  const byKind = emptyPartialByKind();
  const partialCards = partialCardNumberSet(filtered);
  let stale = 0;
  let unassigned = 0;
  const bySet = new Map<string, number>();
  for (const f of filtered) {
    byKind[f.kind]++;
    if (f.isStale) stale++;
    if (f.kind === 'notImplemented' && !f.hasAssignment) unassigned++;
    if (f.cardNumber && f.hasAssignment && f.kind !== 'batchNote') {
      bySet.set(f.setCode, (bySet.get(f.setCode) ?? 0) + 1);
    }
  }

  const md: string[] = [];
  md.push('# Partial curation backlog', '');
  md.push(
    `_Generated by \`npm run scan:partials\`. ${filtered.length} marker comments; ${partialCards.size} assigned cards with incomplete clauses._`,
    '',
  );
  md.push('These cards are in `CURATED_EFFECT_PROGRAMS` but assignment comments still mark deferred/PARTIAL work. They do **not** appear in `npm run triage`.', '');
  md.push('| Metric | Count |', '| --- | ---: |');
  md.push(`| Assigned cards with partial markers | ${partialCards.size} |`);
  md.push(`| Total marker comments | ${filtered.length} |`);
  md.push(`| Stale "NOTE: not yet implemented" on assigned cards | ${stale} |`);
  md.push(`| Unassigned defer notes | ${unassigned} |`);
  md.push('');
  md.push('| Kind | Comments |', '| --- | ---: |');
  for (const kind of ['partial', 'deferred', 'dropped', 'notImplemented', 'batchNote'] as const) {
    md.push(`| ${kind} | ${byKind[kind]} |`);
  }
  md.push('');

  if (bySet.size > 0) {
    md.push('## By set (assigned partial cards)', '', '| Set | Cards |', '| --- | ---: |');
    for (const [set, n] of [...bySet.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))) {
      md.push(`| ${set} | ${n} |`);
    }
    md.push('');
  }

  const cardRows = filtered.filter((f) => f.cardNumber && f.hasAssignment && f.kind !== 'batchNote');
  md.push('## Assigned partial cards', '');
  if (cardRows.length === 0) {
    md.push('_None._', '');
  } else {
    md.push('| Card | Set | Kinds | Note (first) |', '| --- | --- | --- | --- |');
    const grouped = new Map<string, PartialCurationFinding[]>();
    for (const f of cardRows) {
      const key = f.cardNumber!;
      const list = grouped.get(key) ?? [];
      list.push(f);
      grouped.set(key, list);
    }
    for (const [cardNumber, list] of [...grouped.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
      const head = list[0];
      const kinds = [...new Set(list.map((f) => f.kind))].join(', ');
      const note = head.note.length > 120 ? head.note.slice(0, 117) + '…' : head.note;
      md.push(`| ${cardNumber} | ${head.setCode} | ${kinds} | ${note.replace(/\|/g, '\\|')} |`);
    }
    md.push('');
  }

  if (!existsSync(dirname(OUT_MD))) mkdirSync(dirname(OUT_MD), { recursive: true });
  writeFileSync(OUT_MD, md.join('\n'), 'utf8');

  console.log(`[partials] ${filtered.length} markers — ${partialCards.size} assigned cards with incomplete clauses`);
  console.log(`  stale notes     ${stale}`);
  console.log(`  unassigned defer ${unassigned}`);
  for (const kind of ['partial', 'deferred', 'dropped', 'notImplemented', 'batchNote'] as const) {
    console.log(`  ${kind.padEnd(14)} ${byKind[kind]}`);
  }
  console.log(`[partials] wrote ${OUT_CSV} and ${OUT_MD}`);
}

function main(): void {
  const setFilter = new Set(process.argv.slice(2).map((s) => s.toUpperCase()));
  const sources = loadAssignmentSources();
  const catalog = loadCatalog();
  const findings = enrichPartialFindings(scanPartialCurations(sources), catalog);
  const filtered = setFilter.size > 0
    ? findings.filter((f) => setFilter.has(f.setCode.toUpperCase()))
    : findings;
  writeReports(filtered, setFilter);
}

main();
