/**
 * Capability-aware triage worklist generator.
 *
 *   npm run triage
 *
 * Regenerates effect-triage.csv / effect-triage.md FRESH from current data:
 *   - skips cards already curated (CURATED_EFFECT_PROGRAMS) or static keyword-only,
 *     so a done card never reappears (the stale-triage problem);
 *   - runs remaining cards through the inert parser, then the capability triage
 *     classifier, to bucket each as expressible / needsPrimitive / defer with the
 *     mapped catalog primitives and the blocking reason(s).
 *
 * Buckets are authoring guidance, not runtime behavior. Nothing here executes
 * card logic.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseEffect } from '../../src/cards/effectParser';
import { isStaticEngineKeywordOnly } from '../../src/cards/effectParser/staticKeywordOnly';
import { CURATED_EFFECT_PROGRAMS } from '../../src/cards/effectTemplates';
import { classifyTriage, type Bucket } from '../../src/cards/effectTemplates/catalog/capability/triage';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const SETS_DIR = resolve(ROOT, 'public', 'cards', 'sets');
const OUT_CSV = resolve(ROOT, 'effect-triage.csv');
const OUT_MD = resolve(ROOT, 'effect-triage.md');

interface LocalCard {
  cardNumber: string;
  setCode: string;
  category: string;
  en: { name: string | null; effectText: string };
}

function csv(value: unknown): string {
  const s = value == null ? '' : String(value);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function main(): void {
  if (!existsSync(SETS_DIR)) {
    console.error(`[triage] no catalog at ${SETS_DIR} - run \`npm run build:assets\` first.`);
    process.exitCode = 1;
    return;
  }

  const cards: LocalCard[] = [];
  for (const f of readdirSync(SETS_DIR)) {
    if (f.endsWith('.json')) cards.push(...(JSON.parse(readFileSync(join(SETS_DIR, f), 'utf8')) as LocalCard[]));
  }
  cards.sort((a, b) => a.cardNumber.localeCompare(b.cardNumber));

  const rows: string[] = ['set,cardNumber,name,category,bucket,capabilities,unmappedOps,reasons,effectText'];
  const byBucket = new Map<Bucket, number>();
  const bySet = new Map<string, Record<Bucket, number>>();
  const reasonTally = new Map<string, number>();
  const capabilityTally = new Map<string, number>();
  let analyzed = 0;
  let curated = 0;

  for (const c of cards) {
    const text = c.en?.effectText ?? '';
    if (!text.trim()) continue;
    if (CURATED_EFFECT_PROGRAMS[c.cardNumber] || isStaticEngineKeywordOnly(text)) {
      curated++;
      continue;
    }

    const parsed = parseEffect(c.cardNumber, text);
    const verdict = classifyTriage(parsed, text);
    analyzed++;

    byBucket.set(verdict.bucket, (byBucket.get(verdict.bucket) ?? 0) + 1);
    const setRow = bySet.get(c.setCode) ?? { expressible: 0, needsPrimitive: 0, defer: 0 };
    setRow[verdict.bucket]++;
    bySet.set(c.setCode, setRow);
    for (const r of verdict.reasons) reasonTally.set(r, (reasonTally.get(r) ?? 0) + 1);
    for (const cap of verdict.capabilities) capabilityTally.set(cap, (capabilityTally.get(cap) ?? 0) + 1);

    rows.push(
      [c.setCode, c.cardNumber, c.en.name, c.category, verdict.bucket, verdict.capabilities.join('+'), verdict.unmappedOps.join('+'), verdict.reasons.join('+'), text]
        .map(csv)
        .join(','),
    );
  }

  writeFileSync(OUT_CSV, rows.join('\n') + '\n', 'utf8');

  const md: string[] = [];
  md.push('# Effect triage worklist', '');
  md.push(`_Generated by \`npm run triage\`. needsTemplate cards analyzed: ${analyzed} (skipped ${curated} curated)._`, '');
  md.push('| Bucket | Cards | Meaning |', '| --- | ---: | --- |');
  md.push(`| expressible | ${byBucket.get('expressible') ?? 0} | maps to existing primitives — curate now |`);
  md.push(`| needsPrimitive | ${byBucket.get('needsPrimitive') ?? 0} | one small addition unlocks it |`);
  md.push(`| defer | ${byBucket.get('defer') ?? 0} | needs real new engine capability |`);
  md.push('');

  md.push('## By set', '', '| Set | expressible | needsPrimitive | defer |', '| --- | ---: | ---: | ---: |');
  for (const [set, r] of [...bySet.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
    md.push(`| ${set} | ${r.expressible} | ${r.needsPrimitive} | ${r.defer} |`);
  }
  md.push('');

  md.push('## Top blocking reasons (demand-ranked primitive backlog)', '');
  for (const [r, n] of [...reasonTally.entries()].sort((a, b) => b[1] - a[1])) md.push(`- \`${r}\` — ${n}`);
  md.push('');

  md.push('## Most-used capabilities (among draftable cards)', '');
  for (const [cap, n] of [...capabilityTally.entries()].sort((a, b) => b[1] - a[1])) md.push(`- \`${cap}\` — ${n}`);
  md.push('');

  writeFileSync(OUT_MD, md.join('\n'), 'utf8');

  console.log(`[triage] analyzed ${analyzed} needsTemplate cards (skipped ${curated} curated).`);
  for (const b of ['expressible', 'needsPrimitive', 'defer'] as Bucket[]) console.log(`  ${b.padEnd(14)} ${byBucket.get(b) ?? 0}`);
  console.log(`[triage] wrote ${OUT_CSV} and ${OUT_MD}`);
}

main();
