// Auto-curated V2 assignments for ST22.
// Generated by npm run effects:v2 from fully parser-recognized canonical atoms.
// Review before copying into src/cards/effectCompiler_V2/assignments/<SET>_V2.ts.
import type { EffectAssignment_V2 } from '../../src/cards/effectCompiler_V2/types_V2';

export const ST22_AUTO_ASSIGNMENTS_V2 = [
  {
    "assignmentId": "v2:auto:ST22-001:0",
    "cardNumber": "ST22-001",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Activate: Main] [Once Per Turn] You may reveal 1 card with a type including \"Whitebeard Pirates\" from your hand: Draw 1 card and place the revealed card at the top of your deck.",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ACTIVATE_MAIN"
      },
      "activationCost": {
        "payments": [
          {
            "type": "REVEAL_CARD_COST",
            "selector": {
              "subject": "CARD",
              "owner": "PLAYER",
              "zones": [
                "HAND"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "chooser": "EFFECT_OWNER",
              "types": {
                "kind": "HAS_ANY_TYPE",
                "values": [
                  "Whitebeard Pirates"
                ]
              }
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "DRAW_CARD",
          "player": "PLAYER",
          "count": {
            "kind": "NUMBER",
            "value": 1
          }
        },
        "actionId": "ST22-001#0.1"
      }
    },
    "coveredAtomicEffectIds": [
      "ST22-001#0.0",
      "ST22-001#0.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST22-002:0",
    "cardNumber": "ST22-002",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[On Play] Look at 5 cards from the top of your deck; reveal up to 1 card with a type including \"Whitebeard Pirates\" other than [Izo] and add it to your hand. Then, place the rest at the bottom of your deck in any order.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "LOOK_AT_CARDS",
              "player": "PLAYER",
              "source": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "DECK"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 5
                  }
                },
                "ordering": "DECK_ORDER"
              },
              "count": {
                "kind": "NUMBER",
                "value": 5
              }
            },
            "actionId": "ST22-002#0.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "MOVE_CARD",
              "selector": {
                "quantity": {
                  "kind": "UP_TO",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER",
                "types": {
                  "kind": "HAS_ANY_TYPE",
                  "values": [
                    "Whitebeard Pirates"
                  ]
                },
                "names": [
                  {
                    "kind": "NAME_NOT",
                    "value": "Izo"
                  }
                ],
                "subject": "ACTION_RESULT",
                "relations": [
                  "SELECTED_PREVIOUSLY"
                ]
              },
              "to": {
                "zone": "HAND",
                "owner": "PLAYER"
              },
              "cause": "EFFECT"
            },
            "actionId": "ST22-002#0.1"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "REORDER_CARDS",
              "selector": {
                "subject": "ACTION_RESULT",
                "relations": [
                  "REMAINDER_OF_PREVIOUS_SELECTION"
                ],
                "quantity": {
                  "kind": "ANY_NUMBER"
                }
              },
              "destination": {
                "zone": "DECK",
                "owner": "PLAYER",
                "position": "BOTTOM"
              },
              "orderChooser": "PLAYER"
            },
            "actionId": "ST22-002#0.2"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST22-002#0.0",
      "ST22-002#0.1",
      "ST22-002#0.2"
    ]
  },
  {
    "assignmentId": "v2:auto:ST22-002:1",
    "cardNumber": "ST22-002",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[On Your Opponent's Attack] You may trash this Character: Draw 1 card and place 1 card from your hand at the bottom of your deck.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_OPPONENT_ATTACK"
      },
      "activationCost": {
        "payments": [
          {
            "type": "TRASH_CARD_COST",
            "selector": {
              "subject": "CARD",
              "relations": [
                "THIS_CARD"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "chooser": "EFFECT_OWNER"
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "DRAW_CARD",
          "player": "PLAYER",
          "count": {
            "kind": "NUMBER",
            "value": 1
          }
        },
        "actionId": "ST22-002#1.1"
      }
    },
    "coveredAtomicEffectIds": [
      "ST22-002#1.0",
      "ST22-002#1.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST22-003:0",
    "cardNumber": "ST22-003",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Double Attack] (This card deals 2 damage.)",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "GRANT_KEYWORD",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "keyword": "DOUBLE_ATTACK",
          "duration": {
            "kind": "PERMANENT"
          }
        },
        "actionId": "ST22-003#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST22-003#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST22-003:1",
    "cardNumber": "ST22-003",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[On Play] Reveal 1 card from the top of your deck. If that card's type includes \"Whitebeard Pirates\", draw 2 cards.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "REVEAL_CARD",
              "selector": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "DECK"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "ordering": "DECK_ORDER"
              },
              "viewers": "BOTH_PLAYERS"
            },
            "actionId": "ST22-003#1.0"
          },
          {
            "kind": "IF",
            "condition": {
              "kind": "PREDICATE",
              "left": {
                "kind": "COUNT",
                "selector": {
                  "subject": "ACTION_RESULT",
                  "relations": [
                    "REVEALED_PREVIOUSLY"
                  ],
                  "types": {
                    "kind": "TYPE_INCLUDES_TEXT",
                    "values": [
                      "Whitebeard Pirates"
                    ]
                  },
                  "quantity": {
                    "kind": "EXACTLY",
                    "value": {
                      "kind": "NUMBER",
                      "value": 1
                    }
                  }
                }
              },
              "operator": "GREATER_OR_EQUAL",
              "right": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "then": {
              "kind": "ACTION",
              "action": {
                "type": "DRAW_CARD",
                "player": "PLAYER",
                "count": {
                  "kind": "NUMBER",
                  "value": 2
                }
              },
              "actionId": "ST22-003#1.1"
            }
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST22-003#1.0",
      "ST22-003#1.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST22-005:0",
    "cardNumber": "ST22-005",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "If this Character would be removed from the field by your opponent's effect, you may trash 2 cards from your hand instead.",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "CREATE_REPLACEMENT_EFFECT",
          "effect": {
            "id": "replacement:generated",
            "source": {
              "objectRef": "GENERATED_EFFECT",
              "owner": "PLAYER",
              "controller": "PLAYER",
              "sourceZone": "NONE"
            },
            "category": "REPLACEMENT",
            "applicationMode": "CONTINUOUS",
            "activationZones": [
              "LEADER_AREA",
              "CHARACTER_AREA",
              "STAGE_AREA"
            ],
            "optionality": "OPTIONAL",
            "resolution": {
              "kind": "ACTION",
              "action": {
                "type": "TRASH_CARD",
                "selector": {
                  "subject": "CARD",
                  "owner": "PLAYER",
                  "zones": [
                    "HAND"
                  ],
                  "quantity": {
                    "kind": "EXACTLY",
                    "value": {
                      "kind": "NUMBER",
                      "value": 2
                    }
                  },
                  "chooser": "EFFECT_OWNER"
                },
                "cause": "EFFECT"
              }
            },
            "metadata": {
              "sourceCardNumber": "GENERATED",
              "effectIndex": 0,
              "printedText": "If this Character would be removed from the field by your opponent's effect, you may trash 2 cards from your hand instead.",
              "authoringStatus": "PARSED_ONLY"
            },
            "timing": {
              "kind": "CUSTOM_EVENT",
              "eventType": "CARD_WOULD_MOVE",
              "subject": {
                "subject": "CARD",
                "relations": [
                  "THIS_CARD"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "fromZone": "CHARACTER_AREA",
              "sourceSelector": {
                "subject": "EFFECT",
                "controller": "OPPONENT",
                "quantity": {
                  "kind": "ANY_NUMBER"
                }
              },
              "conditions": {
                "kind": "PREDICATE",
                "left": {
                  "kind": "MOVE_CAUSE"
                },
                "operator": "EQUAL",
                "right": {
                  "kind": "STRING",
                  "value": "EFFECT"
                }
              }
            }
          },
          "duration": {
            "kind": "PERMANENT"
          }
        },
        "actionId": "ST22-005#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST22-005#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST22-005:1",
    "cardNumber": "ST22-005",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[Activate: Main] [Once Per Turn] You may rest 3 of your DON!! cards and return 1 of your Characters other than this Character to the owner's hand: Set this Character as active.",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ACTIVATE_MAIN"
      },
      "activationCost": {
        "payments": [
          {
            "type": "REST_DON_COST",
            "count": {
              "kind": "NUMBER",
              "value": 3
            }
          },
          {
            "type": "RETURN_CARD_TO_HAND_COST",
            "selector": {
              "subject": "CARD",
              "controller": "PLAYER",
              "zones": [
                "CHARACTER_AREA"
              ],
              "cardCategories": [
                "CHARACTER"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "chooser": "EFFECT_OWNER",
              "relations": [
                "EXCLUDE_THIS_CARD"
              ]
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "SET_CARD_ACTIVE",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          }
        },
        "actionId": "ST22-005#1.1"
      }
    },
    "coveredAtomicEffectIds": [
      "ST22-005#1.0",
      "ST22-005#1.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST22-006:0",
    "cardNumber": "ST22-006",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[On Play] Reveal 1 card from the top of your deck. If that card's type includes \"Whitebeard Pirates\", draw 2 cards and trash 1 card from your hand.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "REVEAL_CARD",
              "selector": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "DECK"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "ordering": "DECK_ORDER"
              },
              "viewers": "BOTH_PLAYERS"
            },
            "actionId": "ST22-006#0.0"
          },
          {
            "kind": "IF",
            "condition": {
              "kind": "PREDICATE",
              "left": {
                "kind": "COUNT",
                "selector": {
                  "subject": "ACTION_RESULT",
                  "relations": [
                    "REVEALED_PREVIOUSLY"
                  ],
                  "types": {
                    "kind": "TYPE_INCLUDES_TEXT",
                    "values": [
                      "Whitebeard Pirates"
                    ]
                  },
                  "quantity": {
                    "kind": "EXACTLY",
                    "value": {
                      "kind": "NUMBER",
                      "value": 1
                    }
                  }
                }
              },
              "operator": "GREATER_OR_EQUAL",
              "right": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "then": {
              "kind": "SEQUENCE",
              "nodes": [
                {
                  "kind": "ACTION",
                  "action": {
                    "type": "DRAW_CARD",
                    "player": "PLAYER",
                    "count": {
                      "kind": "NUMBER",
                      "value": 2
                    }
                  },
                  "actionId": "ST22-006#0.1"
                },
                {
                  "kind": "ACTION",
                  "action": {
                    "type": "TRASH_CARD",
                    "selector": {
                      "subject": "CARD",
                      "owner": "PLAYER",
                      "zones": [
                        "HAND"
                      ],
                      "quantity": {
                        "kind": "EXACTLY",
                        "value": {
                          "kind": "NUMBER",
                          "value": 1
                        }
                      },
                      "chooser": "EFFECT_OWNER"
                    },
                    "cause": "EFFECT"
                  },
                  "actionId": "ST22-006#0.2"
                }
              ]
            }
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST22-006#0.0",
      "ST22-006#0.1",
      "ST22-006#0.2"
    ]
  },
  {
    "assignmentId": "v2:auto:ST22-007:0",
    "cardNumber": "ST22-007",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Activate: Main] [Once Per Turn] Reveal 1 card from the top of your deck. If that card's type includes \"Whitebeard Pirates\", give up to 1 rested DON!! card to your Leader or 1 of your Characters.",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ACTIVATE_MAIN"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "REVEAL_CARD",
              "selector": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "DECK"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "ordering": "DECK_ORDER"
              },
              "viewers": "BOTH_PLAYERS"
            },
            "actionId": "ST22-007#0.0"
          },
          {
            "kind": "IF",
            "condition": {
              "kind": "PREDICATE",
              "left": {
                "kind": "COUNT",
                "selector": {
                  "subject": "ACTION_RESULT",
                  "relations": [
                    "REVEALED_PREVIOUSLY"
                  ],
                  "types": {
                    "kind": "TYPE_INCLUDES_TEXT",
                    "values": [
                      "Whitebeard Pirates"
                    ]
                  },
                  "quantity": {
                    "kind": "EXACTLY",
                    "value": {
                      "kind": "NUMBER",
                      "value": 1
                    }
                  }
                }
              },
              "operator": "GREATER_OR_EQUAL",
              "right": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "then": {
              "kind": "ACTION",
              "action": {
                "type": "GIVE_DON",
                "donSelector": {
                  "subject": "DON",
                  "owner": "PLAYER",
                  "zones": [
                    "COST_AREA"
                  ],
                  "states": [
                    "RESTED"
                  ],
                  "quantity": {
                    "kind": "UP_TO",
                    "value": {
                      "kind": "NUMBER",
                      "value": 1
                    }
                  },
                  "chooser": "EFFECT_OWNER"
                },
                "target": {
                  "subject": "CARD",
                  "controller": "PLAYER",
                  "zones": [
                    "LEADER_AREA",
                    "CHARACTER_AREA"
                  ],
                  "cardCategories": [
                    "LEADER",
                    "CHARACTER"
                  ],
                  "quantity": {
                    "kind": "EXACTLY",
                    "value": {
                      "kind": "NUMBER",
                      "value": 1
                    }
                  },
                  "chooser": "EFFECT_OWNER"
                }
              },
              "actionId": "ST22-007#0.1"
            }
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST22-007#0.0",
      "ST22-007#0.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST22-009:0",
    "cardNumber": "ST22-009",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "GRANT_KEYWORD",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "keyword": "BLOCKER",
          "duration": {
            "kind": "PERMANENT"
          }
        },
        "actionId": "ST22-009#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST22-009#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST22-011:0",
    "cardNumber": "ST22-011",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": " [Your Turn] [On Play] You may reveal 2 cards with a type including \"Whitebeard Pirates\" from your hand: Up to 1 of your Leader with a type including \"Whitebeard Pirates\" gains +2000 power during this turn.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "conditions": {
        "kind": "PREDICATE",
        "left": {
          "kind": "CURRENT_TURN_PLAYER"
        },
        "operator": "EQUAL",
        "right": {
          "kind": "EFFECT_OWNER"
        }
      },
      "activationCost": {
        "payments": [
          {
            "type": "REVEAL_CARD_COST",
            "selector": {
              "subject": "CARD",
              "owner": "PLAYER",
              "zones": [
                "HAND"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 2
                }
              },
              "chooser": "EFFECT_OWNER",
              "types": {
                "kind": "HAS_ANY_TYPE",
                "values": [
                  "Whitebeard Pirates"
                ]
              }
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "MODIFY_POWER",
          "selector": {
            "subject": "CARD",
            "controller": "PLAYER",
            "zones": [
              "LEADER_AREA"
            ],
            "cardCategories": [
              "LEADER"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER",
            "types": {
              "kind": "HAS_ANY_TYPE",
              "values": [
                "Whitebeard Pirates"
              ]
            }
          },
          "propertyLayer": "CURRENT_VALUE",
          "operation": "ADD",
          "value": {
            "kind": "NUMBER",
            "value": 2000
          },
          "duration": {
            "kind": "THIS_TURN"
          }
        },
        "actionId": "ST22-011#0.1"
      }
    },
    "coveredAtomicEffectIds": [
      "ST22-011#0.0",
      "ST22-011#0.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST22-012:0",
    "cardNumber": "ST22-012",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Once Per Turn] If this Character would be K.O.'d by your opponent's effect, you may trash 1 card from your hand instead.",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "CREATE_REPLACEMENT_EFFECT",
          "effect": {
            "id": "replacement:generated",
            "source": {
              "objectRef": "GENERATED_EFFECT",
              "owner": "PLAYER",
              "controller": "PLAYER",
              "sourceZone": "NONE"
            },
            "category": "REPLACEMENT",
            "applicationMode": "CONTINUOUS",
            "activationZones": [
              "LEADER_AREA",
              "CHARACTER_AREA",
              "STAGE_AREA"
            ],
            "optionality": "OPTIONAL",
            "resolution": {
              "kind": "ACTION",
              "action": {
                "type": "TRASH_CARD",
                "selector": {
                  "subject": "CARD",
                  "owner": "PLAYER",
                  "zones": [
                    "HAND"
                  ],
                  "quantity": {
                    "kind": "EXACTLY",
                    "value": {
                      "kind": "NUMBER",
                      "value": 1
                    }
                  },
                  "chooser": "EFFECT_OWNER"
                },
                "cause": "EFFECT"
              }
            },
            "metadata": {
              "sourceCardNumber": "GENERATED",
              "effectIndex": 0,
              "printedText": "If this Character would be KO'd by your opponent's effect, you may trash 1 card from your hand instead.",
              "authoringStatus": "PARSED_ONLY"
            },
            "timing": {
              "kind": "CUSTOM_EVENT",
              "eventType": "CARD_WOULD_BE_KO",
              "subject": {
                "subject": "CARD",
                "relations": [
                  "THIS_CARD"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "sourceSelector": {
                "subject": "EFFECT",
                "controller": "OPPONENT",
                "quantity": {
                  "kind": "ANY_NUMBER"
                }
              },
              "conditions": {
                "kind": "PREDICATE",
                "left": {
                  "kind": "KO_CAUSE"
                },
                "operator": "EQUAL",
                "right": {
                  "kind": "STRING",
                  "value": "EFFECT"
                }
              }
            }
          },
          "duration": {
            "kind": "PERMANENT"
          }
        },
        "actionId": "ST22-012#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST22-012#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST22-012:1",
    "cardNumber": "ST22-012",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[When Attacking] Reveal 1 card from the top of your deck. If that card's type includes \"Whitebeard Pirates\", this Character gains +1000 power until the end of your opponent's next turn.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "WHEN_ATTACKING"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "REVEAL_CARD",
              "selector": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "DECK"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "ordering": "DECK_ORDER"
              },
              "viewers": "BOTH_PLAYERS"
            },
            "actionId": "ST22-012#1.0"
          },
          {
            "kind": "IF",
            "condition": {
              "kind": "PREDICATE",
              "left": {
                "kind": "COUNT",
                "selector": {
                  "subject": "ACTION_RESULT",
                  "relations": [
                    "REVEALED_PREVIOUSLY"
                  ],
                  "types": {
                    "kind": "TYPE_INCLUDES_TEXT",
                    "values": [
                      "Whitebeard Pirates"
                    ]
                  },
                  "quantity": {
                    "kind": "EXACTLY",
                    "value": {
                      "kind": "NUMBER",
                      "value": 1
                    }
                  }
                }
              },
              "operator": "GREATER_OR_EQUAL",
              "right": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "then": {
              "kind": "ACTION",
              "action": {
                "type": "MODIFY_POWER",
                "selector": {
                  "subject": "CARD",
                  "relations": [
                    "THIS_CARD"
                  ],
                  "quantity": {
                    "kind": "EXACTLY",
                    "value": {
                      "kind": "NUMBER",
                      "value": 1
                    }
                  },
                  "chooser": "EFFECT_OWNER"
                },
                "propertyLayer": "CURRENT_VALUE",
                "operation": "ADD",
                "value": {
                  "kind": "NUMBER",
                  "value": 1000
                },
                "duration": {
                  "kind": "UNTIL_END_OF_NEXT_TURN",
                  "player": "OPPONENT"
                }
              },
              "actionId": "ST22-012#1.1"
            }
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST22-012#1.0",
      "ST22-012#1.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST22-015:0",
    "cardNumber": "ST22-015",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Main] If your Leader's type includes \"Whitebeard Pirates\", play up to 1 [Edward.Newgate] from your hand. Then, you may add 1 card from the top or bottom of your Life cards to your hand. If you do, up to 1 of your Leader gains +2000 power until the end of your opponent's next turn.",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "EVENT_MAIN"
      },
      "conditions": {
        "kind": "PREDICATE",
        "left": {
          "kind": "COUNT",
          "selector": {
            "subject": "CARD",
            "controller": "PLAYER",
            "zones": [
              "LEADER_AREA"
            ],
            "cardCategories": [
              "LEADER"
            ],
            "types": {
              "kind": "TYPE_INCLUDES_TEXT",
              "values": [
                "Whitebeard Pirates"
              ]
            },
            "quantity": {
              "kind": "ANY_NUMBER"
            }
          }
        },
        "operator": "GREATER_OR_EQUAL",
        "right": {
          "kind": "NUMBER",
          "value": 1
        }
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "PLAY_CARD",
              "selector": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "HAND"
                ],
                "quantity": {
                  "kind": "UP_TO",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER",
                "names": [
                  {
                    "kind": "NAME_EXACT",
                    "value": "Edward.Newgate"
                  }
                ]
              },
              "player": "PLAYER"
            },
            "actionId": "ST22-015#0.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "MOVE_CARD",
              "selector": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "LIFE"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "ordering": "DECK_ORDER"
              },
              "to": {
                "zone": "HAND",
                "owner": "PLAYER"
              },
              "cause": "EFFECT"
            },
            "actionId": "ST22-015#0.1"
          },
          {
            "kind": "IF_ACTION_SUCCEEDED",
            "actionResult": "ST22-015#0.1",
            "then": {
              "kind": "ACTION",
              "action": {
                "type": "MODIFY_POWER",
                "selector": {
                  "subject": "CARD",
                  "controller": "PLAYER",
                  "zones": [
                    "LEADER_AREA"
                  ],
                  "cardCategories": [
                    "LEADER"
                  ],
                  "quantity": {
                    "kind": "UP_TO",
                    "value": {
                      "kind": "NUMBER",
                      "value": 1
                    }
                  },
                  "chooser": "EFFECT_OWNER"
                },
                "propertyLayer": "CURRENT_VALUE",
                "operation": "ADD",
                "value": {
                  "kind": "NUMBER",
                  "value": 2000
                },
                "duration": {
                  "kind": "UNTIL_END_OF_NEXT_TURN",
                  "player": "OPPONENT"
                }
              },
              "actionId": "ST22-015#0.2"
            }
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST22-015#0.0",
      "ST22-015#0.1",
      "ST22-015#0.2"
    ]
  },
  {
    "assignmentId": "v2:auto:ST22-016:0",
    "cardNumber": "ST22-016",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Counter] Reveal 1 card from the top of your deck. If that card's type includes \"Whitebeard Pirates\", up to 1 of your Leader or Character cards gains +4000 power during this battle.",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "EVENT_COUNTER"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "REVEAL_CARD",
              "selector": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "DECK"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "ordering": "DECK_ORDER"
              },
              "viewers": "BOTH_PLAYERS"
            },
            "actionId": "ST22-016#0.0"
          },
          {
            "kind": "IF",
            "condition": {
              "kind": "PREDICATE",
              "left": {
                "kind": "COUNT",
                "selector": {
                  "subject": "ACTION_RESULT",
                  "relations": [
                    "REVEALED_PREVIOUSLY"
                  ],
                  "types": {
                    "kind": "TYPE_INCLUDES_TEXT",
                    "values": [
                      "Whitebeard Pirates"
                    ]
                  },
                  "quantity": {
                    "kind": "EXACTLY",
                    "value": {
                      "kind": "NUMBER",
                      "value": 1
                    }
                  }
                }
              },
              "operator": "GREATER_OR_EQUAL",
              "right": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "then": {
              "kind": "ACTION",
              "action": {
                "type": "MODIFY_POWER",
                "selector": {
                  "subject": "CARD",
                  "controller": "PLAYER",
                  "zones": [
                    "LEADER_AREA",
                    "CHARACTER_AREA"
                  ],
                  "cardCategories": [
                    "LEADER",
                    "CHARACTER"
                  ],
                  "quantity": {
                    "kind": "UP_TO",
                    "value": {
                      "kind": "NUMBER",
                      "value": 1
                    }
                  },
                  "chooser": "EFFECT_OWNER"
                },
                "propertyLayer": "CURRENT_VALUE",
                "operation": "ADD",
                "value": {
                  "kind": "NUMBER",
                  "value": 4000
                },
                "duration": {
                  "kind": "THIS_BATTLE"
                }
              },
              "actionId": "ST22-016#0.1"
            }
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST22-016#0.0",
      "ST22-016#0.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST22-016:1",
    "cardNumber": "ST22-016",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[Trigger] Draw 1 card.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "TRIGGER"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "DRAW_CARD",
          "player": "PLAYER",
          "count": {
            "kind": "NUMBER",
            "value": 1
          }
        },
        "actionId": "ST22-016#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST22-016#1.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST22-017:0",
    "cardNumber": "ST22-017",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Main] You may reveal 2 cards with a type including \"Whitebeard Pirates\" from your hand: Draw 1 card. Then, place up to 1 Character with a cost of 5 or less at the bottom of the owner's deck.",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "EVENT_MAIN"
      },
      "activationCost": {
        "payments": [
          {
            "type": "REVEAL_CARD_COST",
            "selector": {
              "subject": "CARD",
              "owner": "PLAYER",
              "zones": [
                "HAND"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 2
                }
              },
              "chooser": "EFFECT_OWNER",
              "types": {
                "kind": "HAS_ANY_TYPE",
                "values": [
                  "Whitebeard Pirates"
                ]
              }
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "DRAW_CARD",
              "player": "PLAYER",
              "count": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "actionId": "ST22-017#0.1"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "MOVE_CARD",
              "selector": {
                "subject": "CARD",
                "zones": [
                  "CHARACTER_AREA"
                ],
                "cardCategories": [
                  "CHARACTER"
                ],
                "quantity": {
                  "kind": "UP_TO",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER",
                "cost": {
                  "propertyLayer": "CURRENT",
                  "comparison": "AT_MOST",
                  "value": {
                    "kind": "NUMBER",
                    "value": 5
                  }
                }
              },
              "to": {
                "zone": "DECK",
                "owner": "CARD_OWNER",
                "position": "BOTTOM"
              },
              "cause": "EFFECT"
            },
            "actionId": "ST22-017#0.2"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST22-017#0.0",
      "ST22-017#0.1",
      "ST22-017#0.2"
    ]
  },
  {
    "assignmentId": "v2:auto:ST22-017:1",
    "cardNumber": "ST22-017",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[Trigger] Return up to 1 Character with a cost of 3 or less to the owner's hand.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "TRIGGER"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "MOVE_CARD",
          "selector": {
            "subject": "CARD",
            "zones": [
              "CHARACTER_AREA"
            ],
            "cardCategories": [
              "CHARACTER"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER",
            "cost": {
              "propertyLayer": "CURRENT",
              "comparison": "AT_MOST",
              "value": {
                "kind": "NUMBER",
                "value": 3
              }
            }
          },
          "to": {
            "zone": "HAND",
            "owner": "CARD_OWNER"
          },
          "cause": "EFFECT"
        },
        "actionId": "ST22-017#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST22-017#1.0"
    ]
  }
] satisfies readonly EffectAssignment_V2[];
