/**
 * Effect runtime-template coverage tracker.
 *
 *   npm run coverage
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { computeEffectMetrics, type CatalogCard } from '../../src/cards/devMetrics';
import { loadAssignmentSources } from '../shared/loadAssignmentSources';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const SETS_DIR = resolve(ROOT, 'public', 'cards', 'sets');
const OUT_CSV = resolve(ROOT, 'effect-coverage.csv');
const OUT_MD = resolve(ROOT, 'effect-coverage.md');
const OUT_PARTIAL_CSV = resolve(ROOT, 'effect-partial-curation.csv');
const OUT_PARTIAL_MD = resolve(ROOT, 'effect-partial-curation.md');

function csv(value: unknown): string {
  const s = value == null ? '' : String(value);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function main(): void {
  if (!existsSync(SETS_DIR)) {
    console.error(`[coverage] no catalog at ${SETS_DIR} - run \`npm run build:assets\` first.`);
    process.exitCode = 1;
    return;
  }

  const cards: CatalogCard[] = [];
  for (const f of readdirSync(SETS_DIR)) {
    if (f.endsWith('.json')) cards.push(...(JSON.parse(readFileSync(join(SETS_DIR, f), 'utf8')) as CatalogCard[]));
  }

  const metrics = computeEffectMetrics(cards, { assignmentSources: loadAssignmentSources() });
  const rows = metrics.coverageRows;
  const withText = metrics.withEffectText;
  const { curated, needsTemplate, vanilla, curatedPct } = metrics.coverage;
  const partialCurated = metrics.partial.partialCuratedCards;
  const fullyCurated = curated - partialCurated;

  const csvRows = ['set,cardNumber,name,category,status,partialCurated,partialNoteCount,curatedAbilities,effectAbilities,runtimeTriggers,parserReview,effectText'];
  for (const r of rows) {
    if (r.status === 'vanilla') continue;
    csvRows.push(
      [
        r.setCode,
        r.cardNumber,
        r.name,
        r.category,
        r.status,
        r.partialCurated,
        r.partialNoteCount,
        r.curatedAbilities,
        r.effectAbilities,
        r.runtimeTriggers,
        r.parserReview,
        r.effectText,
      ]
        .map(csv)
        .join(','),
    );
  }
  writeFileSync(OUT_CSV, csvRows.join('\n') + '\n', 'utf8');

  const md: string[] = [];
  md.push('# Effect coverage', '');
  md.push(`_Generated by \`npm run coverage\`. ${rows.length} cards; ${withText} with effect text._`, '');
  md.push('| Status | Count |', '| --- | ---: |');
  md.push(`| curated | ${curated} |`);
  md.push(`| partialCurated (assigned, incomplete) | ${partialCurated} |`);
  md.push(`| fullyCurated | ${fullyCurated} |`);
  md.push(`| needsTemplate | ${needsTemplate} |`);
  md.push(`| vanilla | ${vanilla} |`);
  md.push('');
  md.push(`**Curated rate:** ${curatedPct}% of cards with effect text`, '');
  md.push(`**Fully curated rate:** ${withText > 0 ? Math.round((fullyCurated / withText) * 1000) / 10 : 0}% (excludes partial assignments)`, '');
  md.push('See also `effect-partial-curation.md` for the PARTIAL/deferred comment backlog.', '');
  md.push('## Needs template', '');
  const backlog = rows.filter((r) => r.status === 'needsTemplate');
  if (backlog.length === 0) {
    md.push('_None._', '');
  } else {
    md.push('| Card | Set | Effect |', '| --- | --- | --- |');
    for (const r of backlog) {
      const short = r.effectText.length > 120 ? r.effectText.slice(0, 117) + '…' : r.effectText;
      md.push(`| ${r.cardNumber} | ${r.setCode} | ${short.replace(/\|/g, '\\|')} |`);
    }
    md.push('');
  }

  if (!existsSync(dirname(OUT_MD))) mkdirSync(dirname(OUT_MD), { recursive: true });
  writeFileSync(OUT_MD, md.join('\n'), 'utf8');

  const partialRows = ['cardNumber,set,name,kind,hasAssignment,isStale,sourceFile,line,note,effectText'];
  for (const f of metrics.partialFindings) {
    partialRows.push(
      [f.cardNumber, f.setCode, f.name ?? '', f.kind, f.hasAssignment, f.isStale, f.sourceFile, f.line, f.note, f.effectText ?? '']
        .map(csv)
        .join(','),
    );
  }
  writeFileSync(OUT_PARTIAL_CSV, partialRows.join('\n') + '\n', 'utf8');

  const partialMd: string[] = [];
  partialMd.push('# Partial curation backlog', '');
  partialMd.push(`_Generated by \`npm run coverage\`. ${metrics.partial.findingCount} marker comments; ${partialCurated} assigned cards incomplete._`, '');
  partialMd.push('| Metric | Count |', '| --- | ---: |');
  partialMd.push(`| partialCurated cards | ${partialCurated} |`);
  partialMd.push(`| stale NOTE on assigned cards | ${metrics.partial.staleNotes} |`);
  partialMd.push(`| unassigned defer notes | ${metrics.partial.unassignedDeferNotes} |`);
  partialMd.push('');
  writeFileSync(OUT_PARTIAL_MD, partialMd.join('\n') + '\n', 'utf8');

  console.log(`[coverage] ${rows.length} cards — curated ${curated} (${partialCurated} partial), needsTemplate ${needsTemplate}, vanilla ${vanilla}`);
  console.log(`[coverage] fully curated ${fullyCurated} (${withText > 0 ? Math.round((fullyCurated / withText) * 1000) / 10 : 0}% of cards with text)`);
  console.log(`[coverage] wrote ${OUT_CSV}, ${OUT_MD}, ${OUT_PARTIAL_CSV}, ${OUT_PARTIAL_MD}`);
}

main();
