/**
 * Effect runtime-template coverage tracker.
 *
 *   npm run coverage
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { classifyCoverage, type CatalogCard, type CoverageRow } from '../../src/cards/devMetrics';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const SETS_DIR = resolve(ROOT, 'public', 'cards', 'sets');
const OUT_CSV = resolve(ROOT, 'effect-coverage.csv');
const OUT_MD = resolve(ROOT, 'effect-coverage.md');

function csv(value: unknown): string {
  const s = value == null ? '' : String(value);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function main(): void {
  if (!existsSync(SETS_DIR)) {
    console.error(`[coverage] no catalog at ${SETS_DIR} - run \`npm run build:assets\` first.`);
    process.exitCode = 1;
    return;
  }

  const cards: CatalogCard[] = [];
  for (const f of readdirSync(SETS_DIR)) {
    if (f.endsWith('.json')) cards.push(...(JSON.parse(readFileSync(join(SETS_DIR, f), 'utf8')) as CatalogCard[]));
  }
  cards.sort((a, b) => a.cardNumber.localeCompare(b.cardNumber));

  const rows: CoverageRow[] = cards.map(classifyCoverage);

  const curated = rows.filter((r) => r.status === 'curated').length;
  const needsTemplate = rows.filter((r) => r.status === 'needsTemplate').length;
  const vanilla = rows.filter((r) => r.status === 'vanilla').length;
  const withText = rows.filter((r) => r.effectText.trim()).length;

  const csvRows = ['set,cardNumber,name,category,status,curatedAbilities,effectAbilities,runtimeTriggers,parserReview,effectText'];
  for (const r of rows) {
    if (r.status === 'vanilla') continue;
    csvRows.push(
      [r.setCode, r.cardNumber, r.name, r.category, r.status, r.curatedAbilities, r.effectAbilities, r.runtimeTriggers, r.parserReview, r.effectText]
        .map(csv)
        .join(','),
    );
  }
  writeFileSync(OUT_CSV, csvRows.join('\n') + '\n', 'utf8');

  const md: string[] = [];
  md.push('# Effect coverage', '');
  md.push(`_Generated by \`npm run coverage\`. ${rows.length} cards; ${withText} with effect text._`, '');
  md.push('| Status | Count |', '| --- | ---: |');
  md.push(`| curated | ${curated} |`);
  md.push(`| needsTemplate | ${needsTemplate} |`);
  md.push(`| vanilla | ${vanilla} |`);
  md.push('');
  md.push(`**Curated rate:** ${withText > 0 ? Math.round((curated / withText) * 1000) / 10 : 0}% of cards with effect text`, '');
  md.push('## Needs template', '');
  const backlog = rows.filter((r) => r.status === 'needsTemplate');
  if (backlog.length === 0) {
    md.push('_None._', '');
  } else {
    md.push('| Card | Set | Effect |', '| --- | --- | --- |');
    for (const r of backlog) {
      const short = r.effectText.length > 120 ? r.effectText.slice(0, 117) + '…' : r.effectText;
      md.push(`| ${r.cardNumber} | ${r.setCode} | ${short.replace(/\|/g, '\\|')} |`);
    }
    md.push('');
  }

  if (!existsSync(dirname(OUT_MD))) mkdirSync(dirname(OUT_MD), { recursive: true });
  writeFileSync(OUT_MD, md.join('\n'), 'utf8');

  console.log(`[coverage] ${rows.length} cards — curated ${curated}, needsTemplate ${needsTemplate}, vanilla ${vanilla}`);
  console.log(`[coverage] wrote ${OUT_CSV} and ${OUT_MD}`);
}

main();
