/**
 * CAPABILITY.md generator.
 *
 *   npm run capability:doc
 *
 * Emits a single agent-/human-facing reference of everything the effect-template
 * catalog can express, straight from the typed capability registry
 * (src/cards/effectTemplates/catalog/capability/registry.ts) — so the doc can
 * never drift from the code. Read CAPABILITY.md before authoring a card instead
 * of grepping templateDefs/factories/effectIr/game.
 *
 * Output: CAPABILITY.md (repo root).
 */
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  COSTS,
  DURATIONS,
  EFFECT_PRIMITIVES,
  GATES,
  KEYWORDS,
  TIMINGS,
  type CapabilitySpec,
} from '../../src/cards/effectTemplates/catalog/capability/registry';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = resolve(ROOT, 'CAPABILITY.md');

const esc = (s: string): string => s.replace(/\|/g, '\\|');

function paramsCol(spec: CapabilitySpec): string {
  if (spec.params.length === 0) return '—';
  return spec.params
    .map((p) => `\`${p.name}${p.required ? '' : '?'}: ${p.type}\`${p.note ? ` (${p.note})` : ''}`)
    .join('<br>');
}

function specTable(title: string, intro: string, table: Record<string, CapabilitySpec>): string[] {
  const lines: string[] = [`## ${title}`, '', intro, ''];
  lines.push('| id | summary | params | covers | excludes | example |');
  lines.push('| --- | --- | --- | --- | --- | --- |');
  for (const spec of Object.values(table)) {
    const covers = spec.covers.map((c) => `"${esc(c)}"`).join('<br>');
    const excludes = spec.excludes?.length ? spec.excludes.map((c) => `"${esc(c)}"`).join('<br>') : '';
    const ex = spec.examples[0];
    lines.push(
      `| \`${spec.id}\` | ${esc(spec.summary)} | ${paramsCol(spec)} | ${covers} | ${excludes} | ${ex ? `${ex.cardNumber}: \`${esc(ex.snippet)}\`` : ''} |`,
    );
  }
  lines.push('');
  return lines;
}

function enumTable(title: string, table: Record<string, string>): string[] {
  const lines: string[] = [`## ${title}`, ''];
  lines.push('| id | meaning |');
  lines.push('| --- | --- |');
  for (const [id, meaning] of Object.entries(table)) lines.push(`| \`${id}\` | ${esc(meaning)} |`);
  lines.push('');
  return lines;
}

function main(): void {
  const out: string[] = [];
  out.push('# Effect-template capability reference', '');
  out.push('_Generated by `npm run capability:doc` from the typed capability registry. Do not edit by hand._', '');
  out.push(
    'This is the single source of truth for what a card assignment can express. Each row lists the ' +
      'exact params, the canonical card-text clauses it **covers**, what it explicitly **excludes** ' +
      '(route those to a new primitive or defer), and a real curated example to copy.',
    '',
  );
  out.push(
    `Totals: **${Object.keys(EFFECT_PRIMITIVES).length}** effect fns · **${Object.keys(GATES).length}** gates · ` +
      `**${Object.keys(COSTS).length}** cost kinds · **${Object.keys(TIMINGS).length}** timings · ` +
      `**${Object.keys(DURATIONS).length}** durations · **${Object.keys(KEYWORDS).length}** keywords.`,
    '',
  );
  out.push(
    '## How to author a card',
    '',
    '1. Segment the text by bracket tags (`[On Play]`, `[When Attacking]`, `[Activate: Main]`, `[DON!! xN]`, `[Trigger]`, `[Counter]`…) into abilities.',
    '2. For each ability pick a **timing**; put board preconditions in `gate`, `[DON!! xN]`/turn state in `condition`, and activation costs (`:` clause) in `cost` or as an optional leading function + `ifPrevious`.',
    '3. Map each effect clause to a **fn** below. If a clause matches an `excludes` entry or nothing at all, curate the mappable part and leave a `// PARTIAL:`/`// NOTE:` for the rest.',
    '',
  );

  out.push(...specTable('Effect functions', 'Placed in an ability\'s `functions: [...]`. All accept `ifPrevious`/`ifGate` for sequencing.', EFFECT_PRIMITIVES));
  out.push(...specTable('Gates (board-state preconditions)', 'Used in `params.gate: [...]` or `condition.gate: [...]`.', GATES));
  out.push(...specTable('Activation costs', 'Used in `params.cost: [...]`.', COSTS));
  out.push(...enumTable('Timings', TIMINGS));
  out.push(...enumTable('Durations', DURATIONS));
  out.push(...enumTable('Keywords', KEYWORDS));

  writeFileSync(OUT, out.join('\n') + '\n', 'utf8');
  console.log(`[capability:doc] wrote ${OUT}`);
}

main();
