/**
 * Curation audit — cross-checks every curated EffectProgram against its card's
 * printed effect text and flags LIKELY mis-mappings.
 *
 *   npm run audit:curation            # audit every set
 *   npm run audit:curation OP13       # only OP13
 *   npm run audit:curation OP13 EB03  # multiple sets
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CURATED_EFFECT_PROGRAMS } from '../../src/cards/effectTemplates';
import { auditCuratedCard, emptyAuditByCategory, type AuditCategory, type CatalogCard } from '../../src/cards/devMetrics';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const SETS_DIR = resolve(ROOT, 'public', 'cards', 'sets');
const OUT_CSV = resolve(ROOT, 'curation-audit.csv');
const OUT_MD = resolve(ROOT, 'curation-audit.md');

function csv(value: unknown): string {
  const s = value == null ? '' : String(value);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function main(): void {
  if (!existsSync(SETS_DIR)) {
    console.error(`[audit] no catalog at ${SETS_DIR} — run \`npm run build:assets\` first.`);
    process.exitCode = 1;
    return;
  }

  const setFilter = new Set(process.argv.slice(2).map((s) => s.toUpperCase()));

  const byNumber = new Map<string, CatalogCard>();
  for (const f of readdirSync(SETS_DIR)) {
    if (!f.endsWith('.json')) continue;
    for (const c of JSON.parse(readFileSync(join(SETS_DIR, f), 'utf8')) as CatalogCard[]) {
      byNumber.set(c.cardNumber, c);
    }
  }

  const findings = [];
  let scanned = 0;
  let missingCard = 0;

  for (const [cardNumber, program] of Object.entries(CURATED_EFFECT_PROGRAMS)) {
    const card = byNumber.get(cardNumber);
    if (!card) {
      missingCard++;
      continue;
    }
    if (setFilter.size > 0 && !setFilter.has(card.setCode.toUpperCase())) continue;
    if (!card.en?.effectText?.trim()) continue;
    scanned++;
    findings.push(...auditCuratedCard(card, program));
  }

  findings.sort((a, b) => a.cardNumber.localeCompare(b.cardNumber) || a.category.localeCompare(b.category));

  const rows = ['cardNumber,set,name,category,detail,effectText'];
  for (const f of findings) {
    rows.push([f.cardNumber, f.setCode, f.name, f.category, f.detail, f.effectText].map(csv).join(','));
  }
  writeFileSync(OUT_CSV, rows.join('\n') + '\n', 'utf8');

  const byCategory = emptyAuditByCategory();
  const bySet = new Map<string, number>();
  const flaggedCards = new Set<string>();
  for (const f of findings) {
    byCategory[f.category as AuditCategory]++;
    bySet.set(f.setCode, (bySet.get(f.setCode) ?? 0) + 1);
    flaggedCards.add(f.cardNumber);
  }

  const md: string[] = [];
  md.push('# Curation audit', '');
  md.push(
    `_Generated by \`npm run audit:curation${setFilter.size ? ' ' + [...setFilter].join(' ') : ''}\`. Scanned ${scanned} curated cards; ${flaggedCards.size} flagged (${findings.length} findings)._`,
    '',
  );
  md.push('Each finding = a literal or timing asserted by the curated IR that does NOT appear in the printed effect text. Flags are advisory; confirm before editing.', '');

  md.push('| Category | Findings | Meaning |', '| --- | ---: | --- |');
  md.push(`| type | ${byCategory.type} | a \`typeIncludes\`/gate type not found in text (likely wrong card) |`);
  md.push(`| name | ${byCategory.name} | a card-name literal not found in text |`);
  md.push(`| keyword | ${byCategory.keyword} | a granted keyword (Blocker/Rush/…) not found in text |`);
  md.push(`| timing | ${byCategory.timing} | a curated timing whose [tag] is absent from text |`);
  md.push('');

  if (bySet.size > 0) {
    md.push('## By set', '', '| Set | Findings |', '| --- | ---: |');
    for (const [set, n] of [...bySet.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))) {
      md.push(`| ${set} | ${n} |`);
    }
    md.push('');
  }

  md.push('## Findings', '');
  if (findings.length === 0) {
    md.push('_No mismatches found._', '');
  } else {
    md.push('| Card | Set | Category | Missing from text | Effect text |', '| --- | --- | --- | --- | --- |');
    for (const f of findings) {
      const shortText = f.effectText.length > 160 ? f.effectText.slice(0, 157) + '…' : f.effectText;
      md.push(
        `| ${f.cardNumber} | ${f.setCode} | ${f.category} | \`${f.detail}\` | ${shortText.replace(/\|/g, '\\|')} |`,
      );
    }
    md.push('');
  }

  if (!existsSync(dirname(OUT_MD))) mkdirSync(dirname(OUT_MD), { recursive: true });
  writeFileSync(OUT_MD, md.join('\n'), 'utf8');

  console.log(`[audit] scanned ${scanned} curated cards${setFilter.size ? ` (sets: ${[...setFilter].join(', ')})` : ''}.`);
  console.log(`  flagged cards  ${flaggedCards.size}`);
  for (const c of ['type', 'name', 'keyword', 'timing'] as AuditCategory[]) {
    console.log(`  ${c.padEnd(14)} ${byCategory[c]}`);
  }
  if (missingCard > 0) console.log(`  (skipped ${missingCard} curated programs with no matching set card)`);
  console.log(`[audit] wrote ${OUT_CSV} and ${OUT_MD}`);
}

main();
