// Auto-curated V2 assignments for ST29.
// Generated by npm run effects:v2 from fully parser-recognized canonical atoms.
// Review before copying into src/cards/effectCompiler_V2/assignments/<SET>_V2.ts.
import type { EffectAssignment_V2 } from '../../src/cards/effectCompiler_V2/types_V2';

export const ST29_AUTO_ASSIGNMENTS_V2 = [
  {
    "assignmentId": "v2:auto:ST29-001:0",
    "cardNumber": "ST29-001",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[When Attacking] If you have 2 or less Life cards, draw 1 card and trash 1 card from your hand.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "WHEN_ATTACKING"
      },
      "conditions": {
        "kind": "PREDICATE",
        "left": {
          "kind": "COUNT",
          "selector": {
            "subject": "CARD",
            "owner": "PLAYER",
            "zones": [
              "LIFE"
            ],
            "quantity": {
              "kind": "ANY_NUMBER"
            }
          }
        },
        "operator": "LESS_OR_EQUAL",
        "right": {
          "kind": "NUMBER",
          "value": 2
        }
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "DRAW_CARD",
              "player": "PLAYER",
              "count": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "actionId": "ST29-001#0.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "TRASH_CARD",
              "selector": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "HAND"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "cause": "EFFECT"
            },
            "actionId": "ST29-001#0.1"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST29-001#0.0",
      "ST29-001#0.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST29-002:1",
    "cardNumber": "ST29-002",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[When Attacking] Rest up to 1 of your opponent's Characters with a cost equal to or less than the number of your opponent's Life cards.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "WHEN_ATTACKING"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "REST_CARD",
          "selector": {
            "subject": "CARD",
            "controller": "OPPONENT",
            "zones": [
              "CHARACTER_AREA"
            ],
            "cardCategories": [
              "CHARACTER"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          }
        },
        "actionId": "ST29-002#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST29-002#1.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST29-003:0",
    "cardNumber": "ST29-003",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "If the number of your Life cards is equal to or less than the number of your opponent's Life cards, this Character gains +1000 power.",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "MODIFY_POWER",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "propertyLayer": "CURRENT_VALUE",
          "operation": "ADD",
          "value": {
            "kind": "NUMBER",
            "value": 1000
          },
          "duration": {
            "kind": "PERMANENT"
          }
        },
        "actionId": "ST29-003#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST29-003#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST29-003:1",
    "cardNumber": "ST29-003",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[Trigger] K.O. up to 1 of your opponent's Characters with a cost of 3 or less.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "TRIGGER"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "KO_CARD",
          "selector": {
            "subject": "CARD",
            "controller": "OPPONENT",
            "zones": [
              "CHARACTER_AREA"
            ],
            "cardCategories": [
              "CHARACTER"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER",
            "cost": {
              "propertyLayer": "CURRENT",
              "comparison": "AT_MOST",
              "value": {
                "kind": "NUMBER",
                "value": 3
              }
            }
          },
          "cause": "EFFECT"
        },
        "actionId": "ST29-003#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST29-003#1.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST29-004:0",
    "cardNumber": "ST29-004",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[On Play] Look at 4 cards from the top of your deck; reveal up to 1 {Straw Hat Crew} type card and add it to your hand. Then, place the rest at the bottom of your deck in any order.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "LOOK_AT_CARDS",
              "player": "PLAYER",
              "source": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "DECK"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 4
                  }
                },
                "ordering": "DECK_ORDER"
              },
              "count": {
                "kind": "NUMBER",
                "value": 4
              }
            },
            "actionId": "ST29-004#0.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "MOVE_CARD",
              "selector": {
                "quantity": {
                  "kind": "UP_TO",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER",
                "types": {
                  "kind": "HAS_ANY_TYPE",
                  "values": [
                    "Straw Hat Crew"
                  ]
                },
                "subject": "ACTION_RESULT",
                "relations": [
                  "SELECTED_PREVIOUSLY"
                ]
              },
              "to": {
                "zone": "HAND",
                "owner": "PLAYER"
              },
              "cause": "EFFECT"
            },
            "actionId": "ST29-004#0.1"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "REORDER_CARDS",
              "selector": {
                "subject": "ACTION_RESULT",
                "relations": [
                  "REMAINDER_OF_PREVIOUS_SELECTION"
                ],
                "quantity": {
                  "kind": "ANY_NUMBER"
                }
              },
              "destination": {
                "zone": "DECK",
                "owner": "PLAYER",
                "position": "BOTTOM"
              },
              "orderChooser": "PLAYER"
            },
            "actionId": "ST29-004#0.2"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST29-004#0.0",
      "ST29-004#0.1",
      "ST29-004#0.2"
    ]
  },
  {
    "assignmentId": "v2:auto:ST29-004:1",
    "cardNumber": "ST29-004",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[Trigger] You may trash 1 card from your hand: Play this card.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "TRIGGER"
      },
      "activationCost": {
        "payments": [
          {
            "type": "TRASH_CARD_COST",
            "selector": {
              "subject": "CARD",
              "owner": "PLAYER",
              "zones": [
                "HAND"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "chooser": "EFFECT_OWNER"
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "PLAY_CARD",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "player": "PLAYER"
        },
        "actionId": "ST29-004#1.1"
      }
    },
    "coveredAtomicEffectIds": [
      "ST29-004#1.0",
      "ST29-004#1.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST29-005:0",
    "cardNumber": "ST29-005",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Trigger] If your Leader is [Monkey.D.Luffy], play this card.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "TRIGGER"
      },
      "conditions": {
        "kind": "PREDICATE",
        "left": {
          "kind": "COUNT",
          "selector": {
            "subject": "CARD",
            "controller": "PLAYER",
            "zones": [
              "LEADER_AREA"
            ],
            "cardCategories": [
              "LEADER"
            ],
            "names": [
              {
                "kind": "NAME_EXACT",
                "value": "Monkey.D.Luffy"
              }
            ],
            "quantity": {
              "kind": "ANY_NUMBER"
            }
          }
        },
        "operator": "GREATER_OR_EQUAL",
        "right": {
          "kind": "NUMBER",
          "value": 1
        }
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "PLAY_CARD",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "player": "PLAYER"
        },
        "actionId": "ST29-005#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST29-005#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST29-007:0",
    "cardNumber": "ST29-007",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[On K.O.] You may add 1 card from the top or bottom of your Life cards to your hand: Add up to 1 card from your hand to the top of your Life cards.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_KO"
      },
      "activationCost": {
        "payments": [
          {
            "type": "ADD_LIFE_TO_HAND_COST",
            "selector": {
              "subject": "CARD",
              "owner": "PLAYER",
              "zones": [
                "LIFE"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "ordering": "DECK_ORDER"
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "ADD_CARD_TO_LIFE",
          "selector": {
            "subject": "CARD",
            "owner": "PLAYER",
            "zones": [
              "HAND"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "player": "PLAYER",
          "position": "TOP",
          "face": "FACE_DOWN"
        },
        "actionId": "ST29-007#0.1"
      }
    },
    "coveredAtomicEffectIds": [
      "ST29-007#0.0",
      "ST29-007#0.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST29-007:1",
    "cardNumber": "ST29-007",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[Trigger] Up to 1 of your [Monkey.D.Luffy] cards gains +2000 power during this turn.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "TRIGGER"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "MODIFY_POWER",
          "selector": {
            "subject": "CARD",
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER",
            "names": [
              {
                "kind": "NAME_EXACT",
                "value": "Monkey.D.Luffy"
              }
            ]
          },
          "propertyLayer": "CURRENT_VALUE",
          "operation": "ADD",
          "value": {
            "kind": "NUMBER",
            "value": 2000
          },
          "duration": {
            "kind": "THIS_TURN"
          }
        },
        "actionId": "ST29-007#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST29-007#1.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST29-008:0",
    "cardNumber": "ST29-008",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "If your {Egghead} type Character would be K.O.'d by your opponent's effect, you may turn 1 card from the top of your Life cards face-up instead.",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "CREATE_REPLACEMENT_EFFECT",
          "effect": {
            "id": "replacement:generated",
            "source": {
              "objectRef": "GENERATED_EFFECT",
              "owner": "PLAYER",
              "controller": "PLAYER",
              "sourceZone": "NONE"
            },
            "category": "REPLACEMENT",
            "applicationMode": "CONTINUOUS",
            "activationZones": [
              "LEADER_AREA",
              "CHARACTER_AREA",
              "STAGE_AREA"
            ],
            "optionality": "OPTIONAL",
            "resolution": {
              "kind": "ACTION",
              "action": {
                "type": "TURN_LIFE_FACE_UP",
                "selector": {
                  "subject": "CARD",
                  "owner": "PLAYER",
                  "zones": [
                    "LIFE"
                  ],
                  "quantity": {
                    "kind": "EXACTLY",
                    "value": {
                      "kind": "NUMBER",
                      "value": 1
                    }
                  },
                  "ordering": "DECK_ORDER"
                }
              }
            },
            "metadata": {
              "sourceCardNumber": "GENERATED",
              "effectIndex": 0,
              "printedText": "If your {Egghead} type Character would be KO'd by your opponent's effect, you may turn 1 card from the top of your Life cards face-up instead.",
              "authoringStatus": "PARSED_ONLY"
            },
            "timing": {
              "kind": "CUSTOM_EVENT",
              "eventType": "CARD_WOULD_BE_KO",
              "subject": {
                "subject": "CARD",
                "zones": [
                  "CHARACTER_AREA"
                ],
                "cardCategories": [
                  "CHARACTER"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER",
                "types": {
                  "kind": "HAS_ANY_TYPE",
                  "values": [
                    "Egghead"
                  ]
                }
              },
              "sourceSelector": {
                "subject": "EFFECT",
                "controller": "OPPONENT",
                "quantity": {
                  "kind": "ANY_NUMBER"
                }
              },
              "conditions": {
                "kind": "PREDICATE",
                "left": {
                  "kind": "KO_CAUSE"
                },
                "operator": "EQUAL",
                "right": {
                  "kind": "STRING",
                  "value": "EFFECT"
                }
              }
            }
          },
          "duration": {
            "kind": "PERMANENT"
          }
        },
        "actionId": "ST29-008#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST29-008#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST29-008:1",
    "cardNumber": "ST29-008",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[Trigger] If your Leader is [Monkey.D.Luffy], play this card.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "TRIGGER"
      },
      "conditions": {
        "kind": "PREDICATE",
        "left": {
          "kind": "COUNT",
          "selector": {
            "subject": "CARD",
            "controller": "PLAYER",
            "zones": [
              "LEADER_AREA"
            ],
            "cardCategories": [
              "LEADER"
            ],
            "names": [
              {
                "kind": "NAME_EXACT",
                "value": "Monkey.D.Luffy"
              }
            ],
            "quantity": {
              "kind": "ANY_NUMBER"
            }
          }
        },
        "operator": "GREATER_OR_EQUAL",
        "right": {
          "kind": "NUMBER",
          "value": 1
        }
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "PLAY_CARD",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "player": "PLAYER"
        },
        "actionId": "ST29-008#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST29-008#1.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST29-009:0",
    "cardNumber": "ST29-009",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "GRANT_KEYWORD",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "keyword": "BLOCKER",
          "duration": {
            "kind": "PERMANENT"
          }
        },
        "actionId": "ST29-009#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST29-009#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST29-009:1",
    "cardNumber": "ST29-009",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[Trigger] If your Leader is [Monkey.D.Luffy], play this card.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "TRIGGER"
      },
      "conditions": {
        "kind": "PREDICATE",
        "left": {
          "kind": "COUNT",
          "selector": {
            "subject": "CARD",
            "controller": "PLAYER",
            "zones": [
              "LEADER_AREA"
            ],
            "cardCategories": [
              "LEADER"
            ],
            "names": [
              {
                "kind": "NAME_EXACT",
                "value": "Monkey.D.Luffy"
              }
            ],
            "quantity": {
              "kind": "ANY_NUMBER"
            }
          }
        },
        "operator": "GREATER_OR_EQUAL",
        "right": {
          "kind": "NUMBER",
          "value": 1
        }
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "PLAY_CARD",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "player": "PLAYER"
        },
        "actionId": "ST29-009#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST29-009#1.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST29-011:0",
    "cardNumber": "ST29-011",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "GRANT_KEYWORD",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "keyword": "BLOCKER",
          "duration": {
            "kind": "PERMANENT"
          }
        },
        "actionId": "ST29-011#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST29-011#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST29-012:0",
    "cardNumber": "ST29-012",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Activate: Main] [Once Per Turn] Give up to 1 rested DON!! card to 1 of your [Monkey.D.Luffy] cards.",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ACTIVATE_MAIN"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "GIVE_DON",
          "donSelector": {
            "subject": "DON",
            "owner": "PLAYER",
            "zones": [
              "COST_AREA"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "target": {
            "subject": "CARD",
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER",
            "names": [
              {
                "kind": "NAME_EXACT",
                "value": "Monkey.D.Luffy"
              }
            ]
          }
        },
        "actionId": "ST29-012#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST29-012#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST29-012:1",
    "cardNumber": "ST29-012",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[Trigger] Play this card.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "TRIGGER"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "PLAY_CARD",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "player": "PLAYER"
        },
        "actionId": "ST29-012#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST29-012#1.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST29-013:0",
    "cardNumber": "ST29-013",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Trigger] K.O. up to 1 of your opponent's Characters with a cost equal to or less than the total of your and your opponent's Life cards.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "TRIGGER"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "KO_CARD",
          "selector": {
            "subject": "CARD",
            "controller": "OPPONENT",
            "zones": [
              "CHARACTER_AREA"
            ],
            "cardCategories": [
              "CHARACTER"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "cause": "EFFECT"
        },
        "actionId": "ST29-013#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST29-013#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST29-014:0",
    "cardNumber": "ST29-014",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Rush: Character] (This card can attack Characters on the turn in which it is played.)",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "GRANT_KEYWORD",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "keyword": "RUSH_CHARACTER",
          "duration": {
            "kind": "PERMANENT"
          }
        },
        "actionId": "ST29-014#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST29-014#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST29-014:1",
    "cardNumber": "ST29-014",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[Activate: Main] [Once Per Turn] You may trash 1 card with a [Trigger] from your hand: Draw 1 card and give up to 1 rested DON!! card to your Leader or 1 of your Characters.",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ACTIVATE_MAIN"
      },
      "activationCost": {
        "payments": [
          {
            "type": "TRASH_CARD_COST",
            "selector": {
              "subject": "CARD",
              "owner": "PLAYER",
              "zones": [
                "HAND"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "chooser": "EFFECT_OWNER"
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "DRAW_CARD",
              "player": "PLAYER",
              "count": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "actionId": "ST29-014#1.1"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "GIVE_DON",
              "donSelector": {
                "subject": "DON",
                "owner": "PLAYER",
                "zones": [
                  "COST_AREA"
                ],
                "states": [
                  "RESTED"
                ],
                "quantity": {
                  "kind": "UP_TO",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "target": {
                "subject": "CARD",
                "controller": "PLAYER",
                "zones": [
                  "LEADER_AREA",
                  "CHARACTER_AREA"
                ],
                "cardCategories": [
                  "LEADER",
                  "CHARACTER"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              }
            },
            "actionId": "ST29-014#1.2"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST29-014#1.0",
      "ST29-014#1.1",
      "ST29-014#1.2"
    ]
  },
  {
    "assignmentId": "v2:auto:ST29-015:0",
    "cardNumber": "ST29-015",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Counter] Up to 1 of your Leader or Character cards gains +2000 power during this battle. Then, if you have 1 or less Life cards, give up to 1 of your opponent's Leader or Character cards −2000 power during this turn.",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "EVENT_COUNTER"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "MODIFY_POWER",
              "selector": {
                "subject": "CARD",
                "controller": "PLAYER",
                "zones": [
                  "LEADER_AREA",
                  "CHARACTER_AREA"
                ],
                "cardCategories": [
                  "LEADER",
                  "CHARACTER"
                ],
                "quantity": {
                  "kind": "UP_TO",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "propertyLayer": "CURRENT_VALUE",
              "operation": "ADD",
              "value": {
                "kind": "NUMBER",
                "value": 2000
              },
              "duration": {
                "kind": "THIS_BATTLE"
              }
            },
            "actionId": "ST29-015#0.0"
          },
          {
            "kind": "IF",
            "condition": {
              "kind": "PREDICATE",
              "left": {
                "kind": "COUNT",
                "selector": {
                  "subject": "CARD",
                  "owner": "PLAYER",
                  "zones": [
                    "LIFE"
                  ],
                  "quantity": {
                    "kind": "ANY_NUMBER"
                  }
                }
              },
              "operator": "LESS_OR_EQUAL",
              "right": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "then": {
              "kind": "ACTION",
              "action": {
                "type": "MODIFY_POWER",
                "selector": {
                  "subject": "CARD",
                  "controller": "OPPONENT",
                  "zones": [
                    "LEADER_AREA",
                    "CHARACTER_AREA"
                  ],
                  "cardCategories": [
                    "LEADER",
                    "CHARACTER"
                  ],
                  "quantity": {
                    "kind": "UP_TO",
                    "value": {
                      "kind": "NUMBER",
                      "value": 1
                    }
                  },
                  "chooser": "EFFECT_OWNER"
                },
                "propertyLayer": "CURRENT_VALUE",
                "operation": "SUBTRACT",
                "value": {
                  "kind": "NUMBER",
                  "value": 2000
                },
                "duration": {
                  "kind": "THIS_TURN"
                }
              },
              "actionId": "ST29-015#0.1"
            }
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST29-015#0.0",
      "ST29-015#0.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST29-015:1",
    "cardNumber": "ST29-015",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[Trigger] Draw 1 card.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "TRIGGER"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "DRAW_CARD",
          "player": "PLAYER",
          "count": {
            "kind": "NUMBER",
            "value": 1
          }
        },
        "actionId": "ST29-015#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST29-015#1.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST29-016:0",
    "cardNumber": "ST29-016",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Main] Your [Monkey.D.Luffy] Leader gains [Unblockable] during this turn.(This card cannot be blocked.)",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "EVENT_MAIN"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "GRANT_KEYWORD",
          "selector": {
            "subject": "CARD",
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER",
            "names": [
              {
                "kind": "NAME_EXACT",
                "value": "Monkey.D.Luffy"
              }
            ]
          },
          "keyword": "UNBLOCKABLE",
          "duration": {
            "kind": "THIS_TURN"
          }
        },
        "actionId": "ST29-016#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST29-016#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST29-016:1",
    "cardNumber": "ST29-016",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[Counter] Your Leader gains +3000 power during this battle.",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "EVENT_COUNTER"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "MODIFY_POWER",
          "selector": {
            "subject": "CARD",
            "controller": "PLAYER",
            "zones": [
              "LEADER_AREA"
            ],
            "cardCategories": [
              "LEADER"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "propertyLayer": "CURRENT_VALUE",
          "operation": "ADD",
          "value": {
            "kind": "NUMBER",
            "value": 3000
          },
          "duration": {
            "kind": "THIS_BATTLE"
          }
        },
        "actionId": "ST29-016#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST29-016#1.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST29-017:0",
    "cardNumber": "ST29-017",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, if you have 2 or less Life cards, K.O. up to 1 of your opponent's Characters with a cost of 3 or less.",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "EVENT_COUNTER"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "MODIFY_POWER",
              "selector": {
                "subject": "CARD",
                "controller": "PLAYER",
                "zones": [
                  "LEADER_AREA",
                  "CHARACTER_AREA"
                ],
                "cardCategories": [
                  "LEADER",
                  "CHARACTER"
                ],
                "quantity": {
                  "kind": "UP_TO",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "propertyLayer": "CURRENT_VALUE",
              "operation": "ADD",
              "value": {
                "kind": "NUMBER",
                "value": 4000
              },
              "duration": {
                "kind": "THIS_BATTLE"
              }
            },
            "actionId": "ST29-017#0.0"
          },
          {
            "kind": "IF",
            "condition": {
              "kind": "PREDICATE",
              "left": {
                "kind": "COUNT",
                "selector": {
                  "subject": "CARD",
                  "owner": "PLAYER",
                  "zones": [
                    "LIFE"
                  ],
                  "quantity": {
                    "kind": "ANY_NUMBER"
                  }
                }
              },
              "operator": "LESS_OR_EQUAL",
              "right": {
                "kind": "NUMBER",
                "value": 2
              }
            },
            "then": {
              "kind": "ACTION",
              "action": {
                "type": "KO_CARD",
                "selector": {
                  "subject": "CARD",
                  "controller": "OPPONENT",
                  "zones": [
                    "CHARACTER_AREA"
                  ],
                  "cardCategories": [
                    "CHARACTER"
                  ],
                  "quantity": {
                    "kind": "UP_TO",
                    "value": {
                      "kind": "NUMBER",
                      "value": 1
                    }
                  },
                  "chooser": "EFFECT_OWNER",
                  "cost": {
                    "propertyLayer": "CURRENT",
                    "comparison": "AT_MOST",
                    "value": {
                      "kind": "NUMBER",
                      "value": 3
                    }
                  }
                },
                "cause": "EFFECT"
              },
              "actionId": "ST29-017#0.1"
            }
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST29-017#0.0",
      "ST29-017#0.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST29-017:1",
    "cardNumber": "ST29-017",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[Trigger] Draw 2 cards and trash 1 card from your hand.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "TRIGGER"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "DRAW_CARD",
              "player": "PLAYER",
              "count": {
                "kind": "NUMBER",
                "value": 2
              }
            },
            "actionId": "ST29-017#1.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "TRASH_CARD",
              "selector": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "HAND"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "cause": "EFFECT"
            },
            "actionId": "ST29-017#1.1"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST29-017#1.0",
      "ST29-017#1.1"
    ]
  }
] satisfies readonly EffectAssignment_V2[];
