/**
 * The sound cue catalogue — Layer 5 (presentation) only. Nothing here is game
 * state and nothing in /src/engine may import it.
 *
 * A cue is ONE gesture: something the player did, or something the rules did
 * that the player should hear. Engine log entries are mapped onto cues in
 * matchCues.ts; UI components fire them directly via playCue().
 *
 * Every asset currently in public/audio/sfx/ is a PLACEHOLDER generated by
 * scripts/audio/generate.py. Replacing a cue's sound means dropping a new
 * .ogg at the same path — no code change. See docs/09-audio-and-sound-design.md.
 */

/**
 * Mix buses. Each gets its own gain node so whole categories can be ducked or
 * trimmed without touching individual cues.
 *  - ui      menus, buttons, deck builder. Always allowed, even outside a match.
 *  - game    match flow: phases, card motion, DON!!, prompts.
 *  - battle  combat and card effects — the loudest, most transient layer.
 *  - stinger rare, deliberately dominant moments; ducks music while it plays.
 *  - music   looping beds.
 */
export type SoundBus = 'ui' | 'game' | 'battle' | 'stinger' | 'music';

/** When the asset is fetched. 'boot' at app start, 'match' when a board mounts, 'lazy' on first play. */
export type SoundPreloadGroup = 'boot' | 'match' | 'lazy';

export interface SoundCueDef {
  /** Public path of the asset. Stable contract: swap the file, keep the path. */
  src: string;
  bus: SoundBus;
  /** Static mix trim (0..1). This is the SOUND DESIGN level, not a user setting. */
  gain: number;
  /** Minimum gap between two plays of this cue; calls inside the window are dropped. */
  throttleMs: number;
  /** Cap on simultaneous voices for this one cue. */
  maxVoices: number;
  /** Higher survives when the global voice cap is reached. */
  priority: number;
  /** Per-play random detune (± cents) so repeats of the same cue don't machine-gun. */
  detuneCents: number;
  /** Duck the music bus to this factor while the cue plays (1 = no ducking). */
  duckMusicTo: number;
  loop: boolean;
  group: SoundPreloadGroup;
}

/** Defaults every cue starts from; each entry below overrides only what differs. */
const BASE = {
  gain: 0.8,
  throttleMs: 40,
  maxVoices: 3,
  priority: 5,
  detuneCents: 25,
  duckMusicTo: 1,
  loop: false,
  group: 'match',
} satisfies Omit<SoundCueDef, 'src' | 'bus'>;

function cue(src: string, bus: SoundBus, overrides: Partial<SoundCueDef> = {}): SoundCueDef {
  return { ...BASE, src, bus, ...overrides };
}

const ui = (name: string, o?: Partial<SoundCueDef>) => cue(`/audio/sfx/ui/${name}.ogg`, 'ui', { group: 'boot', ...o });
const game = (folder: string, name: string, o?: Partial<SoundCueDef>) => cue(`/audio/sfx/${folder}/${name}.ogg`, 'game', o);
const battle = (folder: string, name: string, o?: Partial<SoundCueDef>) => cue(`/audio/sfx/${folder}/${name}.ogg`, 'battle', o);

export const SOUND_CUES = {
  // ------------------------------------------------------------------- UI
  'ui.hover': ui('hover', { gain: 0.22, throttleMs: 55, priority: 1, maxVoices: 2 }),
  'ui.click': ui('click', { gain: 0.55, throttleMs: 45, priority: 4 }),
  'ui.confirm': ui('confirm', { gain: 0.7, priority: 6 }),
  'ui.back': ui('back', { gain: 0.55 }),
  'ui.toggle.on': ui('toggle-on', { gain: 0.55 }),
  'ui.toggle.off': ui('toggle-off', { gain: 0.55 }),
  'ui.tab': ui('tab', { gain: 0.45 }),
  'ui.modal.open': ui('modal-open', { gain: 0.5 }),
  'ui.modal.close': ui('modal-close', { gain: 0.45 }),
  'ui.error': ui('error', { gain: 0.6, throttleMs: 220, priority: 7 }),
  'ui.success': ui('success', { gain: 0.65, throttleMs: 200, priority: 7 }),
  'ui.notify': ui('notify', { gain: 0.55, throttleMs: 300 }),
  'ui.slider.tick': ui('slider-tick', { gain: 0.18, throttleMs: 70, priority: 1, maxVoices: 2 }),
  'ui.screen.transition': ui('screen-transition', { gain: 0.45, throttleMs: 250, maxVoices: 1 }),
  'ui.brand.stinger': ui('brand-stinger', { gain: 0.75, throttleMs: 2000, maxVoices: 1, priority: 9, duckMusicTo: 0.35 }),
  'ui.card.hover': ui('card-hover', { gain: 0.2, throttleMs: 60, priority: 1, maxVoices: 2 }),
  'ui.card.detail.open': ui('card-detail-open', { gain: 0.5 }),
  'ui.card.detail.close': ui('card-detail-close', { gain: 0.4 }),
  'ui.deck.add': ui('deck-add', { gain: 0.55, throttleMs: 55 }),
  'ui.deck.remove': ui('deck-remove', { gain: 0.5, throttleMs: 55 }),
  'ui.deck.save': ui('deck-save', { gain: 0.7, throttleMs: 400, priority: 7 }),
  'ui.deck.invalid': ui('deck-invalid', { gain: 0.6, throttleMs: 400, priority: 7 }),
  'ui.chat.send': ui('chat-send', { gain: 0.4, throttleMs: 120 }),
  'ui.chat.receive': ui('chat-receive', { gain: 0.45, throttleMs: 400 }),
  'ui.matchmaking.search': ui('matchmaking-search', { gain: 0.5, throttleMs: 1000, maxVoices: 1 }),
  'ui.matchmaking.found': ui('matchmaking-found', { gain: 0.8, throttleMs: 1500, maxVoices: 1, priority: 9, duckMusicTo: 0.4 }),
  'ui.rank.up': ui('rank-up', { gain: 0.85, throttleMs: 2000, maxVoices: 1, priority: 9, duckMusicTo: 0.3 }),
  'ui.unlock': ui('unlock', { gain: 0.75, throttleMs: 500, priority: 8 }),

  // ---------------------------------------------------------------- MATCH
  'match.start': game('match', 'start', { gain: 0.85, maxVoices: 1, priority: 9, duckMusicTo: 0.35 }),
  'match.rps.throw': game('match', 'rps-throw', { gain: 0.6 }),
  'match.rps.win': game('match', 'rps-win', { gain: 0.75, priority: 8 }),
  'match.rps.lose': game('match', 'rps-lose', { gain: 0.7, priority: 8 }),
  'match.mulligan.shuffle': game('match', 'mulligan-shuffle', { gain: 0.6, maxVoices: 1, throttleMs: 300 }),
  'match.deal': game('match', 'deal', { gain: 0.45, throttleMs: 20, maxVoices: 6, detuneCents: 60, priority: 3 }),
  'match.leader.reveal': game('match', 'leader-reveal', { gain: 0.85, maxVoices: 1, priority: 9, duckMusicTo: 0.4 }),
  'match.concede': game('match', 'concede', { gain: 0.7, maxVoices: 1, priority: 8 }),

  // ----------------------------------------------------------------- TURN
  'turn.begin.you': game('turn', 'begin-you', { gain: 0.7, maxVoices: 1, throttleMs: 400, priority: 8, duckMusicTo: 0.6 }),
  'turn.begin.opponent': game('turn', 'begin-opponent', { gain: 0.6, maxVoices: 1, throttleMs: 400, priority: 8, duckMusicTo: 0.6 }),

  // ---------------------------------------------------------------- PHASE
  'phase.refresh': game('phase', 'refresh', { gain: 0.45, maxVoices: 1, throttleMs: 300 }),
  'phase.draw': game('phase', 'draw', { gain: 0.45, maxVoices: 1, throttleMs: 300 }),
  'phase.don': game('phase', 'don', { gain: 0.5, maxVoices: 1, throttleMs: 300 }),
  'phase.main': game('phase', 'main', { gain: 0.45, maxVoices: 1, throttleMs: 300 }),
  'phase.end': game('phase', 'end', { gain: 0.45, maxVoices: 1, throttleMs: 300 }),

  // ----------------------------------------------------------------- CARD
  'card.draw': game('card', 'draw', { gain: 0.5, throttleMs: 25, maxVoices: 5, detuneCents: 55, priority: 4 }),
  'card.play.character': game('card', 'play-character', { gain: 0.7, detuneCents: 45, priority: 6 }),
  'card.play.stage': game('card', 'play-stage', { gain: 0.7, priority: 6 }),
  'card.play.event': game('card', 'play-event', { gain: 0.65, priority: 6 }),
  'card.move': game('card', 'move', { gain: 0.4, throttleMs: 25, maxVoices: 5, detuneCents: 60, priority: 3 }),
  'card.return.hand': game('card', 'return-hand', { gain: 0.55, detuneCents: 40 }),
  'card.trash': game('card', 'trash', { gain: 0.55, throttleMs: 25, maxVoices: 4, detuneCents: 50 }),
  'card.rest': game('card', 'rest', { gain: 0.45, throttleMs: 25, maxVoices: 4, detuneCents: 55, priority: 3 }),
  'card.setactive': game('card', 'setactive', { gain: 0.4, throttleMs: 25, maxVoices: 5, detuneCents: 60, priority: 2 }),
  'card.reveal': game('card', 'reveal', { gain: 0.6, detuneCents: 40, priority: 6 }),

  // ----------------------------------------------------------------- DECK
  'deck.shuffle': game('deck', 'shuffle', { gain: 0.55, maxVoices: 1, throttleMs: 400 }),

  // ------------------------------------------------------------------ DON
  'don.draw': game('don', 'draw', { gain: 0.55, throttleMs: 20, maxVoices: 6, detuneCents: 45, priority: 4 }),
  'don.attach': game('don', 'attach', { gain: 0.6, throttleMs: 25, maxVoices: 5, detuneCents: 45, priority: 5 }),
  'don.return': game('don', 'return', { gain: 0.5, throttleMs: 25, maxVoices: 4, detuneCents: 45 }),
  'don.rest': game('don', 'rest', { gain: 0.35, throttleMs: 20, maxVoices: 6, detuneCents: 70, priority: 2 }),
  'don.refresh': game('don', 'refresh', { gain: 0.55, maxVoices: 1, throttleMs: 300 }),

  // --------------------------------------------------------------- BATTLE
  'battle.attack.declare': battle('battle', 'attack-declare', { gain: 0.75, maxVoices: 2, priority: 7 }),
  'battle.attack.leader': battle('battle', 'attack-leader', { gain: 0.8, maxVoices: 2, priority: 8 }),
  'battle.blocker': battle('battle', 'blocker', { gain: 0.75, maxVoices: 2, priority: 7 }),
  'battle.counter.card': battle('battle', 'counter-card', { gain: 0.7, maxVoices: 3, detuneCents: 40, priority: 6 }),
  'battle.counter.event': battle('battle', 'counter-event', { gain: 0.75, maxVoices: 2, priority: 7 }),
  'battle.clash': battle('battle', 'clash', { gain: 0.8, maxVoices: 2, detuneCents: 35, priority: 7 }),
  'battle.nullified': battle('battle', 'nullified', { gain: 0.65, maxVoices: 2, priority: 6 }),
  'battle.ko': battle('battle', 'ko', { gain: 0.9, maxVoices: 2, detuneCents: 30, priority: 9, duckMusicTo: 0.6 }),
  'battle.life.take': battle('battle', 'life-take', { gain: 0.9, maxVoices: 2, throttleMs: 90, priority: 9, duckMusicTo: 0.55 }),
  'battle.trigger.reveal': battle('battle', 'trigger-reveal', { gain: 0.85, maxVoices: 1, priority: 9, duckMusicTo: 0.4 }),

  // --------------------------------------------------------------- EFFECT
  'effect.activate': battle('effect', 'activate', { gain: 0.55, throttleMs: 60, maxVoices: 3, detuneCents: 40, priority: 5 }),
  'effect.resolve': battle('effect', 'resolve', { gain: 0.4, throttleMs: 70, maxVoices: 3, detuneCents: 45, priority: 3 }),
  'effect.buff': battle('effect', 'buff', { gain: 0.6, throttleMs: 45, maxVoices: 4, detuneCents: 50 }),
  'effect.debuff': battle('effect', 'debuff', { gain: 0.6, throttleMs: 45, maxVoices: 4, detuneCents: 50 }),
  'effect.search': battle('effect', 'search', { gain: 0.55, maxVoices: 1, throttleMs: 300 }),
  'effect.negate': battle('effect', 'negate', { gain: 0.65, maxVoices: 2, priority: 7 }),

  // --------------------------------------------------------------- PROMPT
  'prompt.open': game('prompt', 'open', { gain: 0.55, maxVoices: 1, throttleMs: 150, priority: 7 }),
  'prompt.select': game('prompt', 'select', { gain: 0.4, throttleMs: 40, detuneCents: 55, priority: 4 }),
  'prompt.confirm': game('prompt', 'confirm', { gain: 0.55, priority: 6 }),
  'prompt.cancel': game('prompt', 'cancel', { gain: 0.5, priority: 6 }),

  // -------------------------------------------------------------- STINGER
  'stinger.life.critical': cue('/audio/sfx/stinger/life-critical.ogg', 'stinger', { gain: 0.8, maxVoices: 1, throttleMs: 5000, priority: 10, duckMusicTo: 0.3 }),
  'stinger.game.win': cue('/audio/sfx/stinger/game-win.ogg', 'stinger', { gain: 0.95, maxVoices: 1, throttleMs: 5000, priority: 10, duckMusicTo: 0.15 }),
  'stinger.game.lose': cue('/audio/sfx/stinger/game-lose.ogg', 'stinger', { gain: 0.9, maxVoices: 1, throttleMs: 5000, priority: 10, duckMusicTo: 0.15 }),

  // ---------------------------------------------------------------- MUSIC
  'music.menu': cue('/audio/main-menu-backsound.mp3', 'music', { gain: 1, loop: true, maxVoices: 1, group: 'lazy', priority: 0, detuneCents: 0 }),
  'music.battle': cue('/audio/sfx/music/battle.ogg', 'music', { gain: 1, loop: true, maxVoices: 1, group: 'lazy', priority: 0, detuneCents: 0 }),
  'music.battle.tense': cue('/audio/sfx/music/battle-tense.ogg', 'music', { gain: 1, loop: true, maxVoices: 1, group: 'lazy', priority: 0, detuneCents: 0 }),
  'music.victory': cue('/audio/sfx/music/victory.ogg', 'music', { gain: 1, loop: false, maxVoices: 1, group: 'lazy', priority: 0, detuneCents: 0 }),
  'music.defeat': cue('/audio/sfx/music/defeat.ogg', 'music', { gain: 1, loop: false, maxVoices: 1, group: 'lazy', priority: 0, detuneCents: 0 }),
} satisfies Record<string, SoundCueDef>;

export type SoundCueId = keyof typeof SOUND_CUES;

export const SOUND_CUE_IDS = Object.keys(SOUND_CUES) as SoundCueId[];

export function isSoundCueId(value: unknown): value is SoundCueId {
  return typeof value === 'string' && Object.prototype.hasOwnProperty.call(SOUND_CUES, value);
}

export function cuesInGroup(group: SoundPreloadGroup): SoundCueId[] {
  return SOUND_CUE_IDS.filter((id) => SOUND_CUES[id].group === group);
}

/** A cue scheduled relative to "now" — what matchCues.ts produces. */
export interface SoundCueEvent {
  cueId: SoundCueId;
  /** Milliseconds from the moment the batch is fired. */
  delayMs: number;
  /** Extra per-event trim on top of the cue's static gain (0..1). */
  gain?: number;
}
