// Auto-curated V2 assignments for ST13.
// Generated by npm run effects:v2 from fully parser-recognized canonical atoms.
// Review before copying into src/cards/effectCompiler_V2/assignments/<SET>_V2.ts.
import type { EffectAssignment_V2 } from '../../src/cards/effectCompiler_V2/types_V2';

export const ST13_AUTO_ASSIGNMENTS_V2 = [
  {
    "assignmentId": "v2:auto:ST13-001:0",
    "cardNumber": "ST13-001",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": " [DON!! x1] [Activate: Main] [Once Per Turn] You may add 1 of your Characters with a cost of 3 or more and 7000 power or more to the top of your Life cards face-up: Up to 1 of your Characters gains +2000 power until the start of your next turn.",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ACTIVATE_MAIN"
      },
      "conditions": {
        "kind": "PREDICATE",
        "left": {
          "kind": "ATTACHED_DON_COUNT",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          }
        },
        "operator": "GREATER_OR_EQUAL",
        "right": {
          "kind": "NUMBER",
          "value": 1
        }
      },
      "activationCost": {
        "payments": [
          {
            "type": "ADD_CARD_TO_LIFE_COST",
            "position": "TOP",
            "face": "FACE_UP",
            "selector": {
              "subject": "CARD",
              "controller": "PLAYER",
              "zones": [
                "CHARACTER_AREA"
              ],
              "cardCategories": [
                "CHARACTER"
              ],
              "cost": {
                "propertyLayer": "CURRENT",
                "comparison": "AT_LEAST",
                "value": {
                  "kind": "NUMBER",
                  "value": 3
                }
              },
              "power": {
                "propertyLayer": "CURRENT",
                "comparison": "AT_LEAST",
                "value": {
                  "kind": "NUMBER",
                  "value": 7000
                }
              },
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "chooser": "EFFECT_OWNER"
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "MODIFY_POWER",
          "selector": {
            "subject": "CARD",
            "controller": "PLAYER",
            "zones": [
              "CHARACTER_AREA"
            ],
            "cardCategories": [
              "CHARACTER"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "propertyLayer": "CURRENT_VALUE",
          "operation": "ADD",
          "value": {
            "kind": "NUMBER",
            "value": 2000
          },
          "duration": {
            "kind": "INSTANT"
          }
        },
        "actionId": "ST13-001#0.1"
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-001#0.0",
      "ST13-001#0.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-002:0",
    "cardNumber": "ST13-002",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": " [DON!! x2] [Activate: Main] [Once Per Turn] Look at 5 cards from the top of your deck and add up to 1 Character card with a cost of 5 to the top of your Life cards face-up. Then, place the rest at the bottom of your deck in any order.",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ACTIVATE_MAIN"
      },
      "conditions": {
        "kind": "PREDICATE",
        "left": {
          "kind": "ATTACHED_DON_COUNT",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          }
        },
        "operator": "GREATER_OR_EQUAL",
        "right": {
          "kind": "NUMBER",
          "value": 2
        }
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "LOOK_AT_CARDS",
              "player": "PLAYER",
              "source": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "DECK"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 5
                  }
                },
                "ordering": "DECK_ORDER"
              },
              "count": {
                "kind": "NUMBER",
                "value": 5
              }
            },
            "actionId": "ST13-002#0.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "ADD_CARD_TO_LIFE",
              "selector": {
                "subject": "CARD",
                "zones": [
                  "CHARACTER_AREA"
                ],
                "cardCategories": [
                  "CHARACTER"
                ],
                "quantity": {
                  "kind": "UP_TO",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "player": "CARD_OWNER",
              "position": "TOP",
              "face": "FACE_UP"
            },
            "actionId": "ST13-002#0.1"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "REORDER_CARDS",
              "selector": {
                "subject": "ACTION_RESULT",
                "relations": [
                  "REMAINDER_OF_PREVIOUS_SELECTION"
                ],
                "quantity": {
                  "kind": "ANY_NUMBER"
                }
              },
              "destination": {
                "zone": "DECK",
                "owner": "PLAYER",
                "position": "BOTTOM"
              },
              "orderChooser": "PLAYER"
            },
            "actionId": "ST13-002#0.2"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-002#0.0",
      "ST13-002#0.1",
      "ST13-002#0.2"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-002:1",
    "cardNumber": "ST13-002",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[End of Your Turn] Trash all your face-up Life cards.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "END_OF_YOUR_TURN"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "TRASH_CARD",
          "selector": {
            "subject": "CARD",
            "owner": "PLAYER",
            "zones": [
              "LIFE"
            ],
            "quantity": {
              "kind": "ALL"
            },
            "relations": [
              "FACE_UP"
            ]
          },
          "cause": "EFFECT"
        },
        "actionId": "ST13-002#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-002#1.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-003:0",
    "cardNumber": "ST13-003",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "Your face-up Life cards are placed at the bottom of your deck instead of being added to your hand, according to the rules.",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "CREATE_REPLACEMENT_EFFECT",
          "duration": {
            "kind": "PERMANENT"
          },
          "effect": {
            "id": "replacement:face-up-life-to-deck-bottom",
            "source": {
              "objectRef": "GENERATED_EFFECT",
              "owner": "PLAYER",
              "controller": "PLAYER",
              "sourceZone": "NONE"
            },
            "category": "REPLACEMENT",
            "applicationMode": "CONTINUOUS",
            "activationZones": [
              "LEADER_AREA"
            ],
            "optionality": "MANDATORY",
            "resolution": {
              "kind": "ACTION",
              "action": {
                "type": "MOVE_CARD",
                "selector": {
                  "subject": "CARD",
                  "owner": "PLAYER",
                  "zones": [
                    "LIFE"
                  ],
                  "relations": [
                    "FACE_UP"
                  ],
                  "quantity": {
                    "kind": "ANY_NUMBER"
                  }
                },
                "to": {
                  "zone": "DECK",
                  "owner": "PLAYER",
                  "position": "BOTTOM"
                },
                "cause": "RULE"
              }
            },
            "metadata": {
              "sourceCardNumber": "GENERATED",
              "effectIndex": 0,
              "printedText": "Your face-up Life cards are placed at the bottom of your deck instead of being added to your hand, according to the rules.",
              "authoringStatus": "PARSED_ONLY"
            }
          }
        },
        "actionId": "ST13-003#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-003#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-003:1",
    "cardNumber": "ST13-003",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[DON!! x2] [Activate: Main] [Once Per Turn] You may trash 1 card from your hand: If you have 0 Life cards, add up to 2 Character cards with a cost of 5 from your hand or trash to the top of your Life cards face-up.",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ACTIVATE_MAIN"
      },
      "conditions": {
        "kind": "PREDICATE",
        "left": {
          "kind": "ATTACHED_DON_COUNT",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          }
        },
        "operator": "GREATER_OR_EQUAL",
        "right": {
          "kind": "NUMBER",
          "value": 2
        }
      },
      "activationCost": {
        "payments": [
          {
            "type": "TRASH_CARD_COST",
            "selector": {
              "subject": "CARD",
              "owner": "PLAYER",
              "zones": [
                "HAND"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "chooser": "EFFECT_OWNER"
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "ADD_CARD_TO_LIFE",
          "selector": {
            "subject": "CARD",
            "owner": "PLAYER",
            "zones": [
              "HAND",
              "TRASH"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 2
              }
            },
            "chooser": "EFFECT_OWNER",
            "cost": {
              "propertyLayer": "CURRENT",
              "comparison": "EQUAL",
              "value": {
                "kind": "NUMBER",
                "value": 5
              }
            }
          },
          "player": "PLAYER",
          "position": "TOP",
          "face": "FACE_UP"
        },
        "actionId": "ST13-003#1.1"
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-003#1.0",
      "ST13-003#1.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-004:0",
    "cardNumber": "ST13-004",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[On Play] Add 1 card from the top of your deck to the top of your Life cards. Then, look at all your Life cards; place 1 card at the top of your deck and place the rest back in your Life area in any order.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "ADD_CARD_TO_LIFE",
              "selector": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "DECK"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "ordering": "DECK_ORDER"
              },
              "player": "PLAYER",
              "position": "TOP",
              "face": "FACE_DOWN"
            },
            "actionId": "ST13-004#0.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "LOOK_AT_LIFE",
              "player": "PLAYER",
              "count": {
                "kind": "COUNT",
                "selector": {
                  "subject": "CARD",
                  "owner": "PLAYER",
                  "zones": [
                    "LIFE"
                  ],
                  "quantity": {
                    "kind": "ANY_NUMBER"
                  }
                }
              },
              "position": "ALL"
            },
            "actionId": "ST13-004#0.1"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "MOVE_CARD",
              "selector": {
                "subject": "ACTION_RESULT",
                "relations": [
                  "SELECTED_PREVIOUSLY"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "to": {
                "zone": "DECK",
                "owner": "PLAYER",
                "position": "TOP"
              },
              "cause": "EFFECT"
            },
            "actionId": "ST13-004#0.2"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "REORDER_LIFE",
              "player": "PLAYER",
              "selector": {
                "subject": "ACTION_RESULT",
                "relations": [
                  "REMAINDER_OF_PREVIOUS_SELECTION"
                ],
                "quantity": {
                  "kind": "ANY_NUMBER"
                }
              },
              "orderChooser": "PLAYER"
            },
            "actionId": "ST13-004#0.3"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-004#0.0",
      "ST13-004#0.1",
      "ST13-004#0.2",
      "ST13-004#0.3"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-005:0",
    "cardNumber": "ST13-005",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "GRANT_KEYWORD",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "keyword": "BLOCKER",
          "duration": {
            "kind": "PERMANENT"
          }
        },
        "actionId": "ST13-005#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-005#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-005:1",
    "cardNumber": "ST13-005",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[On Play] You may trash 1 card from the top or bottom of your Life cards: Reveal up to 1 Character card with a cost of 5 from your hand and add it to the top of your Life cards face-down.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "activationCost": {
        "payments": [
          {
            "type": "TRASH_LIFE_COST",
            "selector": {
              "subject": "CARD",
              "owner": "PLAYER",
              "zones": [
                "LIFE"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "ordering": "DECK_ORDER",
              "chooser": "EFFECT_OWNER"
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "ADD_CARD_TO_LIFE",
          "selector": {
            "subject": "CARD",
            "owner": "PLAYER",
            "zones": [
              "HAND"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER",
            "cost": {
              "propertyLayer": "CURRENT",
              "comparison": "EQUAL",
              "value": {
                "kind": "NUMBER",
                "value": 5
              }
            }
          },
          "player": "PLAYER",
          "position": "TOP",
          "face": "FACE_DOWN"
        },
        "actionId": "ST13-005#1.1"
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-005#1.0",
      "ST13-005#1.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-006:0",
    "cardNumber": "ST13-006",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "GRANT_KEYWORD",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "keyword": "BLOCKER",
          "duration": {
            "kind": "PERMANENT"
          }
        },
        "actionId": "ST13-006#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-006#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-006:1",
    "cardNumber": "ST13-006",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[On Play] Play up to 1 each of [Sabo], [Portgas.D.Ace], and [Monkey.D.Luffy] with a cost of 2 from your hand.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "PLAY_CARD",
          "selector": {
            "subject": "CARD",
            "owner": "PLAYER",
            "zones": [
              "HAND"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER",
            "names": [
              {
                "kind": "NAME_EXACT",
                "value": "Sabo"
              },
              {
                "kind": "NAME_EXACT",
                "value": "Portgas.D.Ace"
              },
              {
                "kind": "NAME_EXACT",
                "value": "Monkey.D.Luffy"
              }
            ],
            "cost": {
              "propertyLayer": "CURRENT",
              "comparison": "EQUAL",
              "value": {
                "kind": "NUMBER",
                "value": 2
              }
            }
          },
          "player": "PLAYER"
        },
        "actionId": "ST13-006#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-006#1.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-007:0",
    "cardNumber": "ST13-007",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Activate: Main] You may trash this Character: Reveal 1 card from the top of your Life cards. If that card is a [Sabo] with a cost of 5, you may play that card. If you do, up to 1 of your Leader gains +2000 power until the end of your opponent's next turn.",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ACTIVATE_MAIN"
      },
      "activationCost": {
        "payments": [
          {
            "type": "TRASH_CARD_COST",
            "selector": {
              "subject": "CARD",
              "relations": [
                "THIS_CARD"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "chooser": "EFFECT_OWNER"
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "REVEAL_CARD",
              "selector": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "LIFE"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "ordering": "DECK_ORDER"
              },
              "viewers": "BOTH_PLAYERS"
            },
            "actionId": "ST13-007#0.1"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "PLAY_CARD",
              "selector": {
                "subject": "ACTION_RESULT",
                "relations": [
                  "SELECTED_PREVIOUSLY"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                }
              },
              "player": "PLAYER"
            },
            "actionId": "ST13-007#0.2"
          },
          {
            "kind": "IF_ACTION_SUCCEEDED",
            "actionResult": "ST13-007#0.2",
            "then": {
              "kind": "ACTION",
              "action": {
                "type": "MODIFY_POWER",
                "selector": {
                  "subject": "CARD",
                  "controller": "PLAYER",
                  "zones": [
                    "LEADER_AREA"
                  ],
                  "cardCategories": [
                    "LEADER"
                  ],
                  "quantity": {
                    "kind": "UP_TO",
                    "value": {
                      "kind": "NUMBER",
                      "value": 1
                    }
                  },
                  "chooser": "EFFECT_OWNER"
                },
                "propertyLayer": "CURRENT_VALUE",
                "operation": "ADD",
                "value": {
                  "kind": "NUMBER",
                  "value": 2000
                },
                "duration": {
                  "kind": "UNTIL_END_OF_NEXT_TURN",
                  "player": "OPPONENT"
                }
              },
              "actionId": "ST13-007#0.3"
            }
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-007#0.0",
      "ST13-007#0.1",
      "ST13-007#0.2",
      "ST13-007#0.3"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-008:0",
    "cardNumber": "ST13-008",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[On Play] You may trash 1 card from the top or bottom of your Life cards: K.O. up to 1 of your opponent's Characters with a cost of 5 or less.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "activationCost": {
        "payments": [
          {
            "type": "TRASH_LIFE_COST",
            "selector": {
              "subject": "CARD",
              "owner": "PLAYER",
              "zones": [
                "LIFE"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "ordering": "DECK_ORDER",
              "chooser": "EFFECT_OWNER"
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "KO_CARD",
          "selector": {
            "subject": "CARD",
            "controller": "OPPONENT",
            "zones": [
              "CHARACTER_AREA"
            ],
            "cardCategories": [
              "CHARACTER"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER",
            "cost": {
              "propertyLayer": "CURRENT",
              "comparison": "AT_MOST",
              "value": {
                "kind": "NUMBER",
                "value": 5
              }
            }
          },
          "cause": "EFFECT"
        },
        "actionId": "ST13-008#0.1"
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-008#0.0",
      "ST13-008#0.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-009:0",
    "cardNumber": "ST13-009",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[On Play] You may turn 1 of your face-up Life cards face-down: If your opponent has 7 or more cards in their hand, trash up to 1 card from the top of your opponent's Life cards.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "activationCost": {
        "payments": [
          {
            "type": "TURN_LIFE_FACE_DOWN_COST",
            "selector": {
              "subject": "CARD",
              "owner": "PLAYER",
              "zones": [
                "LIFE"
              ],
              "states": [
                "ACTIVE"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "chooser": "EFFECT_OWNER"
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "IF",
        "condition": {
          "kind": "PREDICATE",
          "left": {
            "kind": "COUNT",
            "selector": {
              "subject": "CARD",
              "owner": "OPPONENT",
              "zones": [
                "HAND"
              ],
              "quantity": {
                "kind": "ANY_NUMBER"
              }
            }
          },
          "operator": "GREATER_OR_EQUAL",
          "right": {
            "kind": "NUMBER",
            "value": 7
          }
        },
        "then": {
          "kind": "ACTION",
          "action": {
            "type": "TRASH_LIFE",
            "player": "OPPONENT",
            "position": "TOP",
            "count": {
              "kind": "NUMBER",
              "value": 1
            },
            "activateTrigger": false
          },
          "actionId": "ST13-009#0.1"
        }
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-009#0.0",
      "ST13-009#0.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-010:0",
    "cardNumber": "ST13-010",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Activate: Main] You may trash this Character: Reveal 1 card from the top of your Life cards. If that card is a [Portgas.D.Ace] with a cost of 5, you may play that card. If you do, up to 1 of your Leader gains +2000 power until the end of your opponent's next turn.",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ACTIVATE_MAIN"
      },
      "activationCost": {
        "payments": [
          {
            "type": "TRASH_CARD_COST",
            "selector": {
              "subject": "CARD",
              "relations": [
                "THIS_CARD"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "chooser": "EFFECT_OWNER"
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "REVEAL_CARD",
              "selector": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "LIFE"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "ordering": "DECK_ORDER"
              },
              "viewers": "BOTH_PLAYERS"
            },
            "actionId": "ST13-010#0.1"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "PLAY_CARD",
              "selector": {
                "subject": "ACTION_RESULT",
                "relations": [
                  "SELECTED_PREVIOUSLY"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                }
              },
              "player": "PLAYER"
            },
            "actionId": "ST13-010#0.2"
          },
          {
            "kind": "IF_ACTION_SUCCEEDED",
            "actionResult": "ST13-010#0.2",
            "then": {
              "kind": "ACTION",
              "action": {
                "type": "MODIFY_POWER",
                "selector": {
                  "subject": "CARD",
                  "controller": "PLAYER",
                  "zones": [
                    "LEADER_AREA"
                  ],
                  "cardCategories": [
                    "LEADER"
                  ],
                  "quantity": {
                    "kind": "UP_TO",
                    "value": {
                      "kind": "NUMBER",
                      "value": 1
                    }
                  },
                  "chooser": "EFFECT_OWNER"
                },
                "propertyLayer": "CURRENT_VALUE",
                "operation": "ADD",
                "value": {
                  "kind": "NUMBER",
                  "value": 2000
                },
                "duration": {
                  "kind": "UNTIL_END_OF_NEXT_TURN",
                  "player": "OPPONENT"
                }
              },
              "actionId": "ST13-010#0.3"
            }
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-010#0.0",
      "ST13-010#0.1",
      "ST13-010#0.2",
      "ST13-010#0.3"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-011:0",
    "cardNumber": "ST13-011",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[On Play] If you have 2 or less Life cards, this Character gains [Rush].(This card can attack on the turn in which it is played.)",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "conditions": {
        "kind": "PREDICATE",
        "left": {
          "kind": "COUNT",
          "selector": {
            "subject": "CARD",
            "owner": "PLAYER",
            "zones": [
              "LIFE"
            ],
            "quantity": {
              "kind": "ANY_NUMBER"
            }
          }
        },
        "operator": "LESS_OR_EQUAL",
        "right": {
          "kind": "NUMBER",
          "value": 2
        }
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "GRANT_KEYWORD",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "keyword": "RUSH",
          "duration": {
            "kind": "INSTANT"
          }
        },
        "actionId": "ST13-011#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-011#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-012:0",
    "cardNumber": "ST13-012",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[On Play] You may add 1 card from the top or bottom of your Life cards to your hand: Look at all of your Life cards and place them back in your Life area in any order.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "activationCost": {
        "payments": [
          {
            "type": "ADD_LIFE_TO_HAND_COST",
            "selector": {
              "subject": "CARD",
              "owner": "PLAYER",
              "zones": [
                "LIFE"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "ordering": "DECK_ORDER"
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "LOOK_AT_LIFE",
              "player": "PLAYER",
              "count": {
                "kind": "COUNT",
                "selector": {
                  "subject": "CARD",
                  "owner": "PLAYER",
                  "zones": [
                    "LIFE"
                  ],
                  "quantity": {
                    "kind": "ANY_NUMBER"
                  }
                }
              },
              "position": "ALL"
            },
            "actionId": "ST13-012#0.1"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "REORDER_LIFE",
              "player": "PLAYER",
              "selector": {
                "subject": "ACTION_RESULT",
                "relations": [
                  "REMAINDER_OF_PREVIOUS_SELECTION"
                ],
                "quantity": {
                  "kind": "ANY_NUMBER"
                }
              },
              "orderChooser": "PLAYER"
            },
            "actionId": "ST13-012#0.2"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-012#0.0",
      "ST13-012#0.1",
      "ST13-012#0.2"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-013:0",
    "cardNumber": "ST13-013",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[On Play] Look at 5 cards from the top of your deck; reveal up to 1 [Sabo], [Portgas.D.Ace], or [Monkey.D.Luffy] with a cost of 5 or less and add it to your hand. Then, place the rest at the bottom of your deck in any order.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "LOOK_AT_CARDS",
              "player": "PLAYER",
              "source": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "DECK"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 5
                  }
                },
                "ordering": "DECK_ORDER"
              },
              "count": {
                "kind": "NUMBER",
                "value": 5
              }
            },
            "actionId": "ST13-013#0.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "MOVE_CARD",
              "selector": {
                "quantity": {
                  "kind": "UP_TO",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER",
                "names": [
                  {
                    "kind": "NAME_EXACT",
                    "value": "Sabo"
                  },
                  {
                    "kind": "NAME_EXACT",
                    "value": "Portgas.D.Ace"
                  },
                  {
                    "kind": "NAME_EXACT",
                    "value": "Monkey.D.Luffy"
                  }
                ],
                "cost": {
                  "propertyLayer": "CURRENT",
                  "comparison": "AT_MOST",
                  "value": {
                    "kind": "NUMBER",
                    "value": 5
                  }
                },
                "subject": "ACTION_RESULT",
                "relations": [
                  "SELECTED_PREVIOUSLY"
                ]
              },
              "to": {
                "zone": "HAND",
                "owner": "PLAYER"
              },
              "cause": "EFFECT"
            },
            "actionId": "ST13-013#0.1"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "REORDER_CARDS",
              "selector": {
                "subject": "ACTION_RESULT",
                "relations": [
                  "REMAINDER_OF_PREVIOUS_SELECTION"
                ],
                "quantity": {
                  "kind": "ANY_NUMBER"
                }
              },
              "destination": {
                "zone": "DECK",
                "owner": "PLAYER",
                "position": "BOTTOM"
              },
              "orderChooser": "PLAYER"
            },
            "actionId": "ST13-013#0.2"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-013#0.0",
      "ST13-013#0.1",
      "ST13-013#0.2"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-014:0",
    "cardNumber": "ST13-014",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Activate: Main] You may trash this Character: Reveal 1 card from the top of your Life cards. If that card is a [Monkey.D.Luffy] with a cost of 5, you may play that card. If you do, up to 1 of your Leader gains +2000 power until the end of your opponent's next turn.",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ACTIVATE_MAIN"
      },
      "activationCost": {
        "payments": [
          {
            "type": "TRASH_CARD_COST",
            "selector": {
              "subject": "CARD",
              "relations": [
                "THIS_CARD"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "chooser": "EFFECT_OWNER"
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "REVEAL_CARD",
              "selector": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "LIFE"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "ordering": "DECK_ORDER"
              },
              "viewers": "BOTH_PLAYERS"
            },
            "actionId": "ST13-014#0.1"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "PLAY_CARD",
              "selector": {
                "subject": "ACTION_RESULT",
                "relations": [
                  "SELECTED_PREVIOUSLY"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                }
              },
              "player": "PLAYER"
            },
            "actionId": "ST13-014#0.2"
          },
          {
            "kind": "IF_ACTION_SUCCEEDED",
            "actionResult": "ST13-014#0.2",
            "then": {
              "kind": "ACTION",
              "action": {
                "type": "MODIFY_POWER",
                "selector": {
                  "subject": "CARD",
                  "controller": "PLAYER",
                  "zones": [
                    "LEADER_AREA"
                  ],
                  "cardCategories": [
                    "LEADER"
                  ],
                  "quantity": {
                    "kind": "UP_TO",
                    "value": {
                      "kind": "NUMBER",
                      "value": 1
                    }
                  },
                  "chooser": "EFFECT_OWNER"
                },
                "propertyLayer": "CURRENT_VALUE",
                "operation": "ADD",
                "value": {
                  "kind": "NUMBER",
                  "value": 2000
                },
                "duration": {
                  "kind": "UNTIL_END_OF_NEXT_TURN",
                  "player": "OPPONENT"
                }
              },
              "actionId": "ST13-014#0.3"
            }
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-014#0.0",
      "ST13-014#0.1",
      "ST13-014#0.2",
      "ST13-014#0.3"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-015:0",
    "cardNumber": "ST13-015",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Activate: Main] [Once Per Turn] This Character gains +2000 power until the start of your next turn. Then, if you have 1 or more Life cards, draw 1 card and trash 1 card from the top of your Life cards.",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ACTIVATE_MAIN"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "MODIFY_POWER",
              "selector": {
                "subject": "CARD",
                "relations": [
                  "THIS_CARD"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "propertyLayer": "CURRENT_VALUE",
              "operation": "ADD",
              "value": {
                "kind": "NUMBER",
                "value": 2000
              },
              "duration": {
                "kind": "INSTANT"
              }
            },
            "actionId": "ST13-015#0.0"
          },
          {
            "kind": "IF",
            "condition": {
              "kind": "PREDICATE",
              "left": {
                "kind": "COUNT",
                "selector": {
                  "subject": "CARD",
                  "owner": "PLAYER",
                  "zones": [
                    "LIFE"
                  ],
                  "quantity": {
                    "kind": "ANY_NUMBER"
                  }
                }
              },
              "operator": "GREATER_OR_EQUAL",
              "right": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "then": {
              "kind": "SEQUENCE",
              "nodes": [
                {
                  "kind": "ACTION",
                  "action": {
                    "type": "DRAW_CARD",
                    "player": "PLAYER",
                    "count": {
                      "kind": "NUMBER",
                      "value": 1
                    }
                  },
                  "actionId": "ST13-015#0.1"
                },
                {
                  "kind": "ACTION",
                  "action": {
                    "type": "TRASH_LIFE",
                    "player": "PLAYER",
                    "position": "TOP",
                    "count": {
                      "kind": "NUMBER",
                      "value": 1
                    },
                    "activateTrigger": false
                  },
                  "actionId": "ST13-015#0.2"
                }
              ]
            }
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-015#0.0",
      "ST13-015#0.1",
      "ST13-015#0.2"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-016:0",
    "cardNumber": "ST13-016",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Rush] (This card can attack on the turn in which it is played.)",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "GRANT_KEYWORD",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "keyword": "RUSH",
          "duration": {
            "kind": "PERMANENT"
          }
        },
        "actionId": "ST13-016#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-016#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-016:1",
    "cardNumber": "ST13-016",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[On Play] Look at all your Life cards; place 1 at the top of your deck and place the rest back in your Life area in any order.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "LOOK_AT_LIFE",
              "player": "PLAYER",
              "count": {
                "kind": "COUNT",
                "selector": {
                  "subject": "CARD",
                  "owner": "PLAYER",
                  "zones": [
                    "LIFE"
                  ],
                  "quantity": {
                    "kind": "ANY_NUMBER"
                  }
                }
              },
              "position": "ALL"
            },
            "actionId": "ST13-016#1.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "MOVE_CARD",
              "selector": {
                "subject": "ACTION_RESULT",
                "relations": [
                  "SELECTED_PREVIOUSLY"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "to": {
                "zone": "DECK",
                "owner": "PLAYER",
                "position": "TOP"
              },
              "cause": "EFFECT"
            },
            "actionId": "ST13-016#1.1"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "REORDER_LIFE",
              "player": "PLAYER",
              "selector": {
                "subject": "ACTION_RESULT",
                "relations": [
                  "REMAINDER_OF_PREVIOUS_SELECTION"
                ],
                "quantity": {
                  "kind": "ANY_NUMBER"
                }
              },
              "orderChooser": "PLAYER"
            },
            "actionId": "ST13-016#1.2"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-016#1.0",
      "ST13-016#1.1",
      "ST13-016#1.2"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-017:0",
    "cardNumber": "ST13-017",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, look at all your Life cards and place them back in your Life area in any order.",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "EVENT_COUNTER"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "MODIFY_POWER",
              "selector": {
                "subject": "CARD",
                "controller": "PLAYER",
                "zones": [
                  "LEADER_AREA",
                  "CHARACTER_AREA"
                ],
                "cardCategories": [
                  "LEADER",
                  "CHARACTER"
                ],
                "quantity": {
                  "kind": "UP_TO",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "propertyLayer": "CURRENT_VALUE",
              "operation": "ADD",
              "value": {
                "kind": "NUMBER",
                "value": 4000
              },
              "duration": {
                "kind": "THIS_BATTLE"
              }
            },
            "actionId": "ST13-017#0.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "LOOK_AT_LIFE",
              "player": "PLAYER",
              "count": {
                "kind": "COUNT",
                "selector": {
                  "subject": "CARD",
                  "owner": "PLAYER",
                  "zones": [
                    "LIFE"
                  ],
                  "quantity": {
                    "kind": "ANY_NUMBER"
                  }
                }
              },
              "position": "ALL"
            },
            "actionId": "ST13-017#0.1"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "REORDER_LIFE",
              "player": "PLAYER",
              "selector": {
                "subject": "ACTION_RESULT",
                "relations": [
                  "REMAINDER_OF_PREVIOUS_SELECTION"
                ],
                "quantity": {
                  "kind": "ANY_NUMBER"
                }
              },
              "orderChooser": "PLAYER"
            },
            "actionId": "ST13-017#0.2"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-017#0.0",
      "ST13-017#0.1",
      "ST13-017#0.2"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-017:1",
    "cardNumber": "ST13-017",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[Trigger] You may add 1 card from the top or bottom of your Life cards to your hand: Add up to 1 card from your hand to the top of your Life cards.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "TRIGGER"
      },
      "activationCost": {
        "payments": [
          {
            "type": "ADD_LIFE_TO_HAND_COST",
            "selector": {
              "subject": "CARD",
              "owner": "PLAYER",
              "zones": [
                "LIFE"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "ordering": "DECK_ORDER"
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "ADD_CARD_TO_LIFE",
          "selector": {
            "subject": "CARD",
            "owner": "PLAYER",
            "zones": [
              "HAND"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "player": "PLAYER",
          "position": "TOP",
          "face": "FACE_DOWN"
        },
        "actionId": "ST13-017#1.1"
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-017#1.0",
      "ST13-017#1.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-018:0",
    "cardNumber": "ST13-018",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Counter] Up to 1 of your Leader or Character cards gains +2000 power during this battle. Then, if you have 0 Life cards, draw 1 card.",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "EVENT_COUNTER"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "MODIFY_POWER",
              "selector": {
                "subject": "CARD",
                "controller": "PLAYER",
                "zones": [
                  "LEADER_AREA",
                  "CHARACTER_AREA"
                ],
                "cardCategories": [
                  "LEADER",
                  "CHARACTER"
                ],
                "quantity": {
                  "kind": "UP_TO",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "propertyLayer": "CURRENT_VALUE",
              "operation": "ADD",
              "value": {
                "kind": "NUMBER",
                "value": 2000
              },
              "duration": {
                "kind": "THIS_BATTLE"
              }
            },
            "actionId": "ST13-018#0.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "DRAW_CARD",
              "player": "PLAYER",
              "count": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "actionId": "ST13-018#0.1"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-018#0.0",
      "ST13-018#0.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-018:1",
    "cardNumber": "ST13-018",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[Trigger] You may add 1 card from the top or bottom of your Life cards to your hand: Add up to 1 card from your hand to the top of your Life cards.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "TRIGGER"
      },
      "activationCost": {
        "payments": [
          {
            "type": "ADD_LIFE_TO_HAND_COST",
            "selector": {
              "subject": "CARD",
              "owner": "PLAYER",
              "zones": [
                "LIFE"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "ordering": "DECK_ORDER"
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "ADD_CARD_TO_LIFE",
          "selector": {
            "subject": "CARD",
            "owner": "PLAYER",
            "zones": [
              "HAND"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "player": "PLAYER",
          "position": "TOP",
          "face": "FACE_DOWN"
        },
        "actionId": "ST13-018#1.1"
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-018#1.0",
      "ST13-018#1.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-019:0",
    "cardNumber": "ST13-019",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Main] Look at 5 cards from the top of your deck; reveal up to 1 [Sabo], [Portgas.D.Ace], or [Monkey.D.Luffy] with a cost of 5 or less and add it to your hand. Then, place the rest at the bottom of your deck in any order.",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "EVENT_MAIN"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "LOOK_AT_CARDS",
              "player": "PLAYER",
              "source": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "DECK"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 5
                  }
                },
                "ordering": "DECK_ORDER"
              },
              "count": {
                "kind": "NUMBER",
                "value": 5
              }
            },
            "actionId": "ST13-019#0.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "MOVE_CARD",
              "selector": {
                "quantity": {
                  "kind": "UP_TO",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER",
                "names": [
                  {
                    "kind": "NAME_EXACT",
                    "value": "Sabo"
                  },
                  {
                    "kind": "NAME_EXACT",
                    "value": "Portgas.D.Ace"
                  },
                  {
                    "kind": "NAME_EXACT",
                    "value": "Monkey.D.Luffy"
                  }
                ],
                "cost": {
                  "propertyLayer": "CURRENT",
                  "comparison": "AT_MOST",
                  "value": {
                    "kind": "NUMBER",
                    "value": 5
                  }
                },
                "subject": "ACTION_RESULT",
                "relations": [
                  "SELECTED_PREVIOUSLY"
                ]
              },
              "to": {
                "zone": "HAND",
                "owner": "PLAYER"
              },
              "cause": "EFFECT"
            },
            "actionId": "ST13-019#0.1"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "REORDER_CARDS",
              "selector": {
                "subject": "ACTION_RESULT",
                "relations": [
                  "REMAINDER_OF_PREVIOUS_SELECTION"
                ],
                "quantity": {
                  "kind": "ANY_NUMBER"
                }
              },
              "destination": {
                "zone": "DECK",
                "owner": "PLAYER",
                "position": "BOTTOM"
              },
              "orderChooser": "PLAYER"
            },
            "actionId": "ST13-019#0.2"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-019#0.0",
      "ST13-019#0.1",
      "ST13-019#0.2"
    ]
  },
  {
    "assignmentId": "v2:auto:ST13-019:1",
    "cardNumber": "ST13-019",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[Trigger] Activate this card's [Main] effect.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "TRIGGER"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "ACTIVATE_EVENT",
          "selector": {
            "subject": "CARD",
            "relations": [
              "THIS_CARD"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "player": "PLAYER"
        },
        "actionId": "ST13-019#1.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST13-019#1.0"
    ]
  }
] satisfies readonly EffectAssignment_V2[];
