// Auto-curated V2 assignments for ST15.
// Generated by npm run effects:v2 from fully parser-recognized canonical atoms.
// Review before copying into src/cards/effectCompiler_V2/assignments/<SET>_V2.ts.
import type { EffectAssignment_V2 } from '../../src/cards/effectCompiler_V2/types_V2';

export const ST15_AUTO_ASSIGNMENTS_V2 = [
  {
    "assignmentId": "v2:auto:ST15-001:0",
    "cardNumber": "ST15-001",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[When Attacking] If your Leader is [Edward.Newgate], you cannot add Life cards to your hand using your own effects during this turn.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "WHEN_ATTACKING"
      },
      "conditions": {
        "kind": "PREDICATE",
        "left": {
          "kind": "COUNT",
          "selector": {
            "subject": "CARD",
            "controller": "PLAYER",
            "zones": [
              "LEADER_AREA"
            ],
            "cardCategories": [
              "LEADER"
            ],
            "names": [
              {
                "kind": "NAME_EXACT",
                "value": "Edward.Newgate"
              }
            ],
            "quantity": {
              "kind": "ANY_NUMBER"
            }
          }
        },
        "operator": "GREATER_OR_EQUAL",
        "right": {
          "kind": "NUMBER",
          "value": 1
        }
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "PREVENT_ZONE_CHANGE",
          "selector": {
            "subject": "CARD",
            "owner": "PLAYER",
            "zones": [
              "LIFE"
            ],
            "quantity": {
              "kind": "ANY_NUMBER"
            }
          },
          "action": "ADD_LIFE_TO_HAND_BY_OWN_EFFECT",
          "sourceSelector": {
            "subject": "EFFECT",
            "controller": "PLAYER",
            "quantity": {
              "kind": "ANY_NUMBER"
            }
          },
          "duration": {
            "kind": "THIS_TURN"
          }
        },
        "actionId": "ST15-001#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST15-001#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST15-002:0",
    "cardNumber": "ST15-002",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[On Play] Give up to 1 rested DON!! card to your Leader or 1 of your Characters.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "GIVE_DON",
          "donSelector": {
            "subject": "DON",
            "owner": "PLAYER",
            "zones": [
              "COST_AREA"
            ],
            "states": [
              "RESTED"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          },
          "target": {
            "subject": "CARD",
            "controller": "PLAYER",
            "zones": [
              "LEADER_AREA",
              "CHARACTER_AREA"
            ],
            "cardCategories": [
              "LEADER",
              "CHARACTER"
            ],
            "quantity": {
              "kind": "EXACTLY",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER"
          }
        },
        "actionId": "ST15-002#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "ST15-002#0.0"
    ]
  },
  {
    "assignmentId": "v2:auto:ST15-002:1",
    "cardNumber": "ST15-002",
    "effectIndex": 1,
    "status": "ASSIGNED",
    "printedText": "[Activate: Main] You may rest this Character: K.O. up to 1 of your opponent's Characters with 5000 power or less.",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ACTIVATE_MAIN"
      },
      "activationCost": {
        "payments": [
          {
            "type": "REST_CARD_COST",
            "selector": {
              "subject": "CARD",
              "relations": [
                "THIS_CARD"
              ],
              "quantity": {
                "kind": "EXACTLY",
                "value": {
                  "kind": "NUMBER",
                  "value": 1
                }
              },
              "chooser": "EFFECT_OWNER"
            }
          }
        ],
        "optionalPayment": "REQUIRED_TO_ACTIVATE",
        "executionPolicy": "VERIFY_ALL_THEN_PAY_IN_ORDER"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "KO_CARD",
          "selector": {
            "subject": "CARD",
            "controller": "OPPONENT",
            "zones": [
              "CHARACTER_AREA"
            ],
            "cardCategories": [
              "CHARACTER"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER",
            "power": {
              "propertyLayer": "CURRENT",
              "comparison": "AT_MOST",
              "value": {
                "kind": "NUMBER",
                "value": 5000
              }
            }
          },
          "cause": "EFFECT"
        },
        "actionId": "ST15-002#1.1"
      }
    },
    "coveredAtomicEffectIds": [
      "ST15-002#1.0",
      "ST15-002#1.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST15-003:0",
    "cardNumber": "ST15-003",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)[Opponent's Turn] When this Character is K.O.'d by an effect, up to 1 of your Leader gains +2000 power during this turn.",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "GRANT_KEYWORD",
              "selector": {
                "subject": "CARD",
                "relations": [
                  "THIS_CARD"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "keyword": "BLOCKER",
              "duration": {
                "kind": "PERMANENT"
              }
            },
            "actionId": "ST15-003#0.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "MODIFY_POWER",
              "selector": {
                "subject": "CARD",
                "relations": [
                  "THIS_CARD"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "propertyLayer": "CURRENT_VALUE",
              "operation": "ADD",
              "value": {
                "kind": "NUMBER",
                "value": 2000
              },
              "duration": {
                "kind": "THIS_TURN"
              }
            },
            "actionId": "ST15-003#0.1"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST15-003#0.0",
      "ST15-003#0.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST15-004:0",
    "cardNumber": "ST15-004",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[On Play] If your Leader's type includes \"Whitebeard Pirates\", give up to 1 of your opponent's Characters −2000 power during this turn. Then, add 1 card from the top of your Life cards to your hand.",
    "effect": {
      "category": "AUTO",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA",
        "HAND",
        "LIFE",
        "TRASH"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_PLAY"
      },
      "conditions": {
        "kind": "PREDICATE",
        "left": {
          "kind": "COUNT",
          "selector": {
            "subject": "CARD",
            "controller": "PLAYER",
            "zones": [
              "LEADER_AREA"
            ],
            "cardCategories": [
              "LEADER"
            ],
            "types": {
              "kind": "TYPE_INCLUDES_TEXT",
              "values": [
                "Whitebeard Pirates"
              ]
            },
            "quantity": {
              "kind": "ANY_NUMBER"
            }
          }
        },
        "operator": "GREATER_OR_EQUAL",
        "right": {
          "kind": "NUMBER",
          "value": 1
        }
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "MODIFY_POWER",
              "selector": {
                "subject": "CARD",
                "controller": "OPPONENT",
                "zones": [
                  "CHARACTER_AREA"
                ],
                "cardCategories": [
                  "CHARACTER"
                ],
                "quantity": {
                  "kind": "UP_TO",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "propertyLayer": "CURRENT_VALUE",
              "operation": "SUBTRACT",
              "value": {
                "kind": "NUMBER",
                "value": 2000
              },
              "duration": {
                "kind": "THIS_TURN"
              }
            },
            "actionId": "ST15-004#0.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "MOVE_CARD",
              "selector": {
                "subject": "CARD",
                "owner": "PLAYER",
                "zones": [
                  "LIFE"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "ordering": "DECK_ORDER"
              },
              "to": {
                "zone": "HAND",
                "owner": "PLAYER"
              },
              "cause": "EFFECT"
            },
            "actionId": "ST15-004#0.1"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST15-004#0.0",
      "ST15-004#0.1"
    ]
  },
  {
    "assignmentId": "v2:auto:ST15-005:0",
    "cardNumber": "ST15-005",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "If your Leader's type includes \"Whitebeard Pirates\", this Character gains [Rush].(This card can attack on the turn in which it is played.)[Once Per Turn] If this Character would be removed from the field by your opponent's effect, you may give this Character −2000 power during this turn instead.",
    "effect": {
      "category": "PERMANENT",
      "applicationMode": "CONTINUOUS",
      "activationZones": [
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ON_ENTER_PLAY"
      },
      "conditions": {
        "kind": "PREDICATE",
        "left": {
          "kind": "COUNT",
          "selector": {
            "subject": "CARD",
            "controller": "PLAYER",
            "zones": [
              "LEADER_AREA"
            ],
            "cardCategories": [
              "LEADER"
            ],
            "types": {
              "kind": "TYPE_INCLUDES_TEXT",
              "values": [
                "Whitebeard Pirates"
              ]
            },
            "quantity": {
              "kind": "ANY_NUMBER"
            }
          }
        },
        "operator": "GREATER_OR_EQUAL",
        "right": {
          "kind": "NUMBER",
          "value": 1
        }
      },
      "optionality": "OPTIONAL",
      "resolution": {
        "kind": "SEQUENCE",
        "nodes": [
          {
            "kind": "ACTION",
            "action": {
              "type": "GRANT_KEYWORD",
              "selector": {
                "subject": "CARD",
                "relations": [
                  "THIS_CARD"
                ],
                "quantity": {
                  "kind": "EXACTLY",
                  "value": {
                    "kind": "NUMBER",
                    "value": 1
                  }
                },
                "chooser": "EFFECT_OWNER"
              },
              "keyword": "RUSH",
              "duration": {
                "kind": "PERMANENT"
              }
            },
            "actionId": "ST15-005#0.0"
          },
          {
            "kind": "ACTION",
            "action": {
              "type": "CREATE_REPLACEMENT_EFFECT",
              "effect": {
                "id": "replacement:generated",
                "source": {
                  "objectRef": "GENERATED_EFFECT",
                  "owner": "PLAYER",
                  "controller": "PLAYER",
                  "sourceZone": "NONE"
                },
                "category": "REPLACEMENT",
                "applicationMode": "CONTINUOUS",
                "activationZones": [
                  "LEADER_AREA",
                  "CHARACTER_AREA",
                  "STAGE_AREA"
                ],
                "optionality": "OPTIONAL",
                "resolution": {
                  "kind": "ACTION",
                  "action": {
                    "type": "MODIFY_POWER",
                    "selector": {
                      "subject": "CARD",
                      "relations": [
                        "THIS_CARD"
                      ],
                      "quantity": {
                        "kind": "EXACTLY",
                        "value": {
                          "kind": "NUMBER",
                          "value": 1
                        }
                      },
                      "chooser": "EFFECT_OWNER"
                    },
                    "propertyLayer": "CURRENT_VALUE",
                    "operation": "SUBTRACT",
                    "value": {
                      "kind": "NUMBER",
                      "value": 2000
                    },
                    "duration": {
                      "kind": "THIS_TURN"
                    }
                  }
                },
                "metadata": {
                  "sourceCardNumber": "GENERATED",
                  "effectIndex": 0,
                  "printedText": "[Once Per Turn] If this Character would be removed from the field by your opponent's effect, you may give this Character −2000 power during this turn instead.",
                  "authoringStatus": "PARSED_ONLY"
                },
                "timing": {
                  "kind": "CUSTOM_EVENT",
                  "eventType": "CARD_WOULD_MOVE",
                  "subject": {
                    "subject": "CARD",
                    "relations": [
                      "THIS_CARD"
                    ],
                    "quantity": {
                      "kind": "EXACTLY",
                      "value": {
                        "kind": "NUMBER",
                        "value": 1
                      }
                    },
                    "chooser": "EFFECT_OWNER"
                  },
                  "fromZone": "CHARACTER_AREA",
                  "sourceSelector": {
                    "subject": "EFFECT",
                    "controller": "OPPONENT",
                    "quantity": {
                      "kind": "ANY_NUMBER"
                    }
                  },
                  "conditions": {
                    "kind": "PREDICATE",
                    "left": {
                      "kind": "MOVE_CAUSE"
                    },
                    "operator": "EQUAL",
                    "right": {
                      "kind": "STRING",
                      "value": "EFFECT"
                    }
                  }
                }
              },
              "duration": {
                "kind": "THIS_TURN"
              }
            },
            "actionId": "ST15-005#0.1"
          }
        ]
      }
    },
    "coveredAtomicEffectIds": [
      "ST15-005#0.0",
      "ST15-005#0.1"
    ]
  }
] satisfies readonly EffectAssignment_V2[];
