import type {
  Action_V2,
  CostAction_V2,
  ModifierExpression_V2,
  ResolutionNode_V2,
} from '../../cards/effectCompiler_V2/types_V2';

export type PrimitiveRuntimeStatus_V2 =
  | 'implemented'
  | 'bridge-only'
  | 'planned';

export interface PrimitiveDefinition_V2 {
  kind: string;
  status: PrimitiveRuntimeStatus_V2;
  remark: string;
}

export const ACTION_PRIMITIVES_V2: Record<Action_V2['type'], PrimitiveDefinition_V2> = {
  DRAW_CARD: { kind: 'DRAW_CARD', status: 'implemented', remark: 'Native V2 fixed-count draw support is available.' },
  LOOK_AT_CARDS: { kind: 'LOOK_AT_CARDS', status: 'implemented', remark: 'Native V2 look buffer and remainder tracking is available.' },
  SELECT: { kind: 'SELECT', status: 'implemented', remark: 'Native V2 selector resolution and selection binding support is available.' },
  REVEAL_CARD: { kind: 'REVEAL_CARD', status: 'implemented', remark: 'Native V2 reveal support is available for concrete selectors.' },
  REORDER_CARDS: { kind: 'REORDER_CARDS', status: 'implemented', remark: 'Native V2 look-buffer remainder reorder support is available.' },
  SHUFFLE_ZONE: { kind: 'SHUFFLE_ZONE', status: 'implemented', remark: 'Native V2 seeded zone shuffle support is available.' },
  MOVE_CARD: { kind: 'MOVE_CARD', status: 'implemented', remark: 'Native V2 generic zone movement support is available for concrete selectors.' },
  PLAY_CARD: { kind: 'PLAY_CARD', status: 'implemented', remark: 'Native V2 Character/Stage play support is available for concrete selectors.' },
  ACTIVATE_EVENT: { kind: 'ACTIVATE_EVENT', status: 'implemented', remark: 'Native V2 activation records are available and nested Event abilities resolve when runtime context is provided.' },
  TRASH_CARD: { kind: 'TRASH_CARD', status: 'implemented', remark: 'Native V2 trash movement support is available for concrete selectors.' },
  KO_CARD: { kind: 'KO_CARD', status: 'implemented', remark: 'Native V2 direct K.O.-to-trash support is available for concrete selectors.' },
  ADD_CARD_TO_LIFE: { kind: 'ADD_CARD_TO_LIFE', status: 'implemented', remark: 'Native V2 add-to-life support is available for concrete selectors.' },
  TAKE_LIFE_TO_HAND: { kind: 'TAKE_LIFE_TO_HAND', status: 'bridge-only', remark: 'Maps to V1 top-life-to-hand for fixed counts.' },
  TRASH_LIFE: { kind: 'TRASH_LIFE', status: 'implemented', remark: 'Native V2 fixed-count Life trash support is available.' },
  TAKE_DAMAGE: { kind: 'TAKE_DAMAGE', status: 'implemented', remark: 'Native V2 direct life-damage processing support is available.' },
  LOOK_AT_LIFE: { kind: 'LOOK_AT_LIFE', status: 'implemented', remark: 'Native V2 Life look-buffer sidecar support is available.' },
  REORDER_LIFE: { kind: 'REORDER_LIFE', status: 'implemented', remark: 'Native V2 Life reorder support is available for concrete looked-card bindings.' },
  TURN_LIFE_FACE_UP: { kind: 'TURN_LIFE_FACE_UP', status: 'implemented', remark: 'Native V2 Life face-up support is available for concrete selectors.' },
  TURN_LIFE_FACE_DOWN: { kind: 'TURN_LIFE_FACE_DOWN', status: 'implemented', remark: 'Native V2 Life face-down support is available for concrete selectors.' },
  REST_CARD: { kind: 'REST_CARD', status: 'implemented', remark: 'Native V2 rest support is available for concrete selectors.' },
  REST_MIXED_TARGETS: { kind: 'REST_MIXED_TARGETS', status: 'implemented', remark: 'Native V2 shared-quantity rest support is available for mixed card/DON selector branches.' },
  SET_CARD_ACTIVE: { kind: 'SET_CARD_ACTIVE', status: 'implemented', remark: 'Native V2 set-active support is available for concrete selectors.' },
  TURN_CARD_FACE_UP: { kind: 'TURN_CARD_FACE_UP', status: 'implemented', remark: 'Native V2 generic card face-up mutation support is available.' },
  TURN_CARD_FACE_DOWN: { kind: 'TURN_CARD_FACE_DOWN', status: 'implemented', remark: 'Native V2 generic card face-down mutation support is available.' },
  ADD_DON_FROM_DON_DECK: { kind: 'ADD_DON_FROM_DON_DECK', status: 'implemented', remark: 'Native V2 fixed-count DON ramp support is available.' },
  GIVE_DON: { kind: 'GIVE_DON', status: 'implemented', remark: 'Native V2 DON attachment support is available for concrete selectors.' },
  DETACH_DON: { kind: 'DETACH_DON', status: 'implemented', remark: 'Native V2 attached-DON detach-to-cost-area support is available.' },
  REST_DON: { kind: 'REST_DON', status: 'implemented', remark: 'Native V2 DON rest support is available for concrete selectors.' },
  SET_DON_ACTIVE: { kind: 'SET_DON_ACTIVE', status: 'implemented', remark: 'Native V2 DON set-active support is available for concrete selectors.' },
  RETURN_DON_TO_DON_DECK: { kind: 'RETURN_DON_TO_DON_DECK', status: 'implemented', remark: 'Native V2 DON deck return support is available for concrete selectors.' },
  MOVE_DON_TO_COST_AREA: { kind: 'MOVE_DON_TO_COST_AREA', status: 'implemented', remark: 'Native V2 DON move-to-cost-area support detaches given DON and preserves requested active/rested state.' },
  MODIFY_POWER: { kind: 'MODIFY_POWER', status: 'implemented', remark: 'Native V2 serializable power-modifier registration support is available.' },
  MODIFY_COST: { kind: 'MODIFY_COST', status: 'implemented', remark: 'Native V2 serializable cost-modifier registration support is available.' },
  MODIFY_COUNTER: { kind: 'MODIFY_COUNTER', status: 'implemented', remark: 'Native V2 serializable counter-modifier registration support is available.' },
  MODIFY_LIFE_VALUE: { kind: 'MODIFY_LIFE_VALUE', status: 'implemented', remark: 'Native V2 serializable life-value modifier registration support is available.' },
  MODIFY_DAMAGE: { kind: 'MODIFY_DAMAGE', status: 'implemented', remark: 'Native V2 serializable damage modifier registration and direct-damage consumption support is available.' },
  SWAP_POWER: { kind: 'SWAP_POWER', status: 'implemented', remark: 'Native V2 power-swap support registers paired serializable power SET modifiers.' },
  MODIFY_NAME: { kind: 'MODIFY_NAME', status: 'implemented', remark: 'Native V2 serializable name modifier registration and selector matching support is available.' },
  MODIFY_COLOR: { kind: 'MODIFY_COLOR', status: 'implemented', remark: 'Native V2 serializable color modifier registration and selector matching support is available.' },
  MODIFY_TYPE: { kind: 'MODIFY_TYPE', status: 'implemented', remark: 'Native V2 serializable type modifier registration and selector matching support is available.' },
  MODIFY_ATTRIBUTE: { kind: 'MODIFY_ATTRIBUTE', status: 'implemented', remark: 'Native V2 serializable attribute modifier registration and selector matching support is available.' },
  MODIFY_BASE_EFFECT_STATUS: { kind: 'MODIFY_BASE_EFFECT_STATUS', status: 'implemented', remark: 'Native V2 serializable base-effect status modifier registration and selector matching support is available.' },
  GRANT_KEYWORD: { kind: 'GRANT_KEYWORD', status: 'implemented', remark: 'Native V2 serializable keyword-grant registration support is available.' },
  REMOVE_KEYWORD: { kind: 'REMOVE_KEYWORD', status: 'implemented', remark: 'Native V2 serializable keyword-removal registration support is available.' },
  ADD_EFFECT: { kind: 'ADD_EFFECT', status: 'implemented', remark: 'Native V2 serializable gained-effect registration and dispatch support is available.' },
  REMOVE_GAINED_EFFECT: { kind: 'REMOVE_GAINED_EFFECT', status: 'implemented', remark: 'Native V2 serializable gained-effect removal support is available.' },
  INVALIDATE_EFFECTS: { kind: 'INVALIDATE_EFFECTS', status: 'implemented', remark: 'Native V2 serializable effect-invalidation sidecar support is available.' },
  VALIDATE_EFFECTS: { kind: 'VALIDATE_EFFECTS', status: 'implemented', remark: 'Native V2 serializable effect-validation sidecar support is available.' },
  COPY_EFFECT: { kind: 'COPY_EFFECT', status: 'implemented', remark: 'Native V2 source-card effect copying is available through gained-effect sidecars when runtime canonical effects are present.' },
  CREATE_DELAYED_EFFECT: { kind: 'CREATE_DELAYED_EFFECT', status: 'implemented', remark: 'Native V2 serializable delayed-effect registration support is available.' },
  CREATE_REPLACEMENT_EFFECT: { kind: 'CREATE_REPLACEMENT_EFFECT', status: 'implemented', remark: 'Native V2 serializable replacement-effect registration support is available.' },
  PREVENT_ACTION: { kind: 'PREVENT_ACTION', status: 'implemented', remark: 'Native V2 serializable action-prevention registration support is available.' },
  ALLOW_ACTION: { kind: 'ALLOW_ACTION', status: 'implemented', remark: 'Native V2 serializable permission registration support is available.' },
  PREVENT_SELECTION: { kind: 'PREVENT_SELECTION', status: 'implemented', remark: 'Native V2 serializable selection-prevention registration and prompt/SELECT filtering support is available.' },
  PREVENT_ZONE_CHANGE: { kind: 'PREVENT_ZONE_CHANGE', status: 'implemented', remark: 'Native V2 serializable zone-change prevention registration support is available.' },
  MODIFY_VALID_TARGETS: { kind: 'MODIFY_VALID_TARGETS', status: 'implemented', remark: 'Native V2 restriction-only valid-target filtering is available for prompted action targets.' },
  MODIFY_PLAY_PERMISSION: { kind: 'MODIFY_PLAY_PERMISSION', status: 'implemented', remark: 'Native V2 serializable play-permission registration support is available.' },
  DECLARE_ATTACK: { kind: 'DECLARE_ATTACK', status: 'implemented', remark: 'Native V2 effect-emitted attack declaration support is available for concrete selectors.' },
  CHANGE_ATTACK_TARGET: { kind: 'CHANGE_ATTACK_TARGET', status: 'implemented', remark: 'Native V2 current-battle target redirection support is available.' },
  ACTIVATE_BLOCKER: { kind: 'ACTIVATE_BLOCKER', status: 'implemented', remark: 'Native V2 effect-emitted blocker activation support is available for concrete selectors.' },
  CANCEL_ATTACK: { kind: 'CANCEL_ATTACK', status: 'implemented', remark: 'Native V2 current-battle cancellation support is available.' },
  END_BATTLE: { kind: 'END_BATTLE', status: 'implemented', remark: 'Native V2 current-battle termination support is available.' },
  DEAL_DAMAGE: { kind: 'DEAL_DAMAGE', status: 'implemented', remark: 'Native V2 direct damage primitive support is available.' },
  SET_DAMAGE: { kind: 'SET_DAMAGE', status: 'implemented', remark: 'Native V2 fixed damage-setting action support is available.' },
  SKIP_BATTLE_STEP: { kind: 'SKIP_BATTLE_STEP', status: 'implemented', remark: 'Native V2 block/counter/damage battle-step skip support is available.' },
  PLAYER_WINS: { kind: 'PLAYER_WINS', status: 'implemented', remark: 'Native V2 card-effect game-over support is available.' },
  PLAYER_LOSES: { kind: 'PLAYER_LOSES', status: 'implemented', remark: 'Native V2 card-effect game-over support is available.' },
  PLAYER_CHOOSES: { kind: 'PLAYER_CHOOSES', status: 'implemented', remark: 'Native V2 serializable choice-prompt sidecar support is available.' },
  OPPONENT_CHOOSES: { kind: 'OPPONENT_CHOOSES', status: 'implemented', remark: 'Native V2 serializable opponent choice-prompt sidecar support is available.' },
  MODIFY_DEFEAT_CONDITION: { kind: 'MODIFY_DEFEAT_CONDITION', status: 'implemented', remark: 'Native V2 serializable defeat-condition registration support is available.' },
  MODIFY_VICTORY_CONDITION: { kind: 'MODIFY_VICTORY_CONDITION', status: 'implemented', remark: 'Native V2 serializable victory-condition registration support is available.' },
  MODIFY_DECK_CONSTRUCTION: { kind: 'MODIFY_DECK_CONSTRUCTION', status: 'implemented', remark: 'Native V2 serializable deck-construction registration support is available.' },
  MODIFY_STARTING_SETUP: { kind: 'MODIFY_STARTING_SETUP', status: 'implemented', remark: 'Native V2 serializable setup-modifier registration support is available.' },
  MODIFY_AREA_CAPACITY: { kind: 'MODIFY_AREA_CAPACITY', status: 'implemented', remark: 'Native V2 serializable area-capacity modifier registration support is available.' },
  MODIFY_RULE_PERMISSION: { kind: 'MODIFY_RULE_PERMISSION', status: 'implemented', remark: 'Native V2 serializable rule-permission registration support is available.' },
  RAW_UNCOVERED_ACTION: { kind: 'RAW_UNCOVERED_ACTION', status: 'planned', remark: 'Explicitly unresolved authoring escape hatch.' },
};

export const COST_PRIMITIVES_V2: Record<CostAction_V2['type'], PrimitiveDefinition_V2> = {
  REST_DON_COST: { kind: 'REST_DON_COST', status: 'implemented', remark: 'Native V2 fixed-count DON rest payment support is available.' },
  DON_MINUS_COST: { kind: 'DON_MINUS_COST', status: 'implemented', remark: 'Native V2 fixed-count DON minus payment support is available.' },
  REST_CARD_COST: { kind: 'REST_CARD_COST', status: 'implemented', remark: 'Native V2 selector-based rest payment support is available.' },
  TRASH_CARD_COST: { kind: 'TRASH_CARD_COST', status: 'implemented', remark: 'Native V2 selector-based trash payment support is available.' },
  KO_CARD_COST: { kind: 'KO_CARD_COST', status: 'implemented', remark: 'Native V2 selector-based K.O. payment support is available.' },
  MODIFY_POWER_COST: { kind: 'MODIFY_POWER_COST', status: 'implemented', remark: 'Native V2 selector-based temporary power payment support is available.' },
  GIVE_DON_COST: { kind: 'GIVE_DON_COST', status: 'implemented', remark: 'Native V2 DON attachment payment support is available.' },
  PLAY_CARD_COST: { kind: 'PLAY_CARD_COST', status: 'implemented', remark: 'Native V2 selector-based play payment support is available.' },
  RETURN_CARD_TO_HAND_COST: { kind: 'RETURN_CARD_TO_HAND_COST', status: 'implemented', remark: 'Native V2 selector-based hand-return payment support is available.' },
  RETURN_CARD_TO_DECK_COST: { kind: 'RETURN_CARD_TO_DECK_COST', status: 'implemented', remark: 'Native V2 ordered selector-payment deck return support is available.' },
  RETURN_CARD_TO_DECK_AND_SHUFFLE_COST: { kind: 'RETURN_CARD_TO_DECK_AND_SHUFFLE_COST', status: 'implemented', remark: 'Native V2 selector-based deck return plus seeded shuffle payment support is available.' },
  RETURN_DON_TO_DON_DECK_COST: { kind: 'RETURN_DON_TO_DON_DECK_COST', status: 'implemented', remark: 'Native V2 selector-based DON deck return payment support is available.' },
  RETURN_DON_TO_COST_AREA_COST: { kind: 'RETURN_DON_TO_COST_AREA_COST', status: 'implemented', remark: 'Native V2 attached-DON return to cost area payment support is available.' },
  ADD_CARD_TO_LIFE_COST: { kind: 'ADD_CARD_TO_LIFE_COST', status: 'implemented', remark: 'Native V2 selector-based add-to-life payment support is available.' },
  ADD_LIFE_TO_HAND_COST: { kind: 'ADD_LIFE_TO_HAND_COST', status: 'implemented', remark: 'Native V2 life-to-hand payment support is available.' },
  TRASH_LIFE_COST: { kind: 'TRASH_LIFE_COST', status: 'implemented', remark: 'Native V2 life-trash payment support is available.' },
  TURN_LIFE_FACE_UP_COST: { kind: 'TURN_LIFE_FACE_UP_COST', status: 'implemented', remark: 'Native V2 life face-up payment support is available.' },
  TURN_LIFE_FACE_DOWN_COST: { kind: 'TURN_LIFE_FACE_DOWN_COST', status: 'implemented', remark: 'Native V2 life face-down payment support is available.' },
  REVEAL_CARD_COST: { kind: 'REVEAL_CARD_COST', status: 'implemented', remark: 'Native V2 reveal payment support is available.' },
  CHOOSE_ONE_COST: { kind: 'CHOOSE_ONE_COST', status: 'implemented', remark: 'Native V2 selected-option payment support is available through CostPaymentSelection_V2.' },
  RAW_COST: { kind: 'RAW_COST', status: 'planned', remark: 'Parser recognized an unresolved textual cost.' },
};

export const NODE_PRIMITIVES_V2: Record<ResolutionNode_V2['kind'], PrimitiveDefinition_V2> = {
  ACTION: { kind: 'ACTION', status: 'implemented', remark: 'Dispatches to an action primitive.' },
  SEQUENCE: { kind: 'SEQUENCE', status: 'implemented', remark: 'Ordered child resolution.' },
  OPTIONAL: { kind: 'OPTIONAL', status: 'implemented', remark: 'Native V2 optional-resolution YES/NO prompt and resume support is available.' },
  IF: { kind: 'IF', status: 'implemented', remark: 'Native V2 condition evaluator support is available for supported predicates.' },
  IF_ACTION_SUCCEEDED: { kind: 'IF_ACTION_SUCCEEDED', status: 'implemented', remark: 'Depends on action-result bindings.' },
  CHOOSE: { kind: 'CHOOSE', status: 'implemented', remark: 'Native V2 serializable choice-prompt sidecar support is available.' },
  FOR_EACH: { kind: 'FOR_EACH', status: 'implemented', remark: 'Native V2 iterator binding support is available for non-suspending nodes.' },
  REPEAT: { kind: 'REPEAT', status: 'implemented', remark: 'Native V2 numeric expression loop support is available for non-suspending nodes.' },
  REPLACEMENT: { kind: 'REPLACEMENT', status: 'implemented', remark: 'Native V2 replacement wrapper registration support is available.' },
  DELAY: { kind: 'DELAY', status: 'implemented', remark: 'Native V2 delayed wrapper registration support is available.' },
  CREATE_CONTINUOUS_EFFECT: { kind: 'CREATE_CONTINUOUS_EFFECT', status: 'implemented', remark: 'Native V2 continuous stat/keyword/permission modifier registration support is available when the node carries a selector.' },
  NO_OP: { kind: 'NO_OP', status: 'implemented', remark: 'Explicit no-op.' },
};

export const MODIFIER_PRIMITIVES_V2: Record<ModifierExpression_V2['type'], PrimitiveDefinition_V2> = {
  STAT_MODIFIER: { kind: 'STAT_MODIFIER', status: 'implemented', remark: 'Native V2 continuous stat modifier registration support is available through CREATE_CONTINUOUS_EFFECT with a selector.' },
  EFFECT_MODIFIER: { kind: 'EFFECT_MODIFIER', status: 'implemented', remark: 'Native V2 continuous keyword modifier registration support is available through CREATE_CONTINUOUS_EFFECT with a selector.' },
  PERMISSION_MODIFIER: { kind: 'PERMISSION_MODIFIER', status: 'implemented', remark: 'Native V2 continuous permission modifier registration support is available through CREATE_CONTINUOUS_EFFECT with a selector.' },
  RULE_MODIFIER: { kind: 'RULE_MODIFIER', status: 'implemented', remark: 'Native V2 rule modifiers are preserved in serializable permission sidecars for supported rule-action primitives.' },
};
