// Auto-curated V2 assignments for PRB01.
// Generated by npm run effects:v2 from fully parser-recognized canonical atoms.
// Review before copying into src/cards/effectCompiler_V2/assignments/<SET>_V2.ts.
import type { EffectAssignment_V2 } from '../../src/cards/effectCompiler_V2/types_V2';

export const PRB01_AUTO_ASSIGNMENTS_V2 = [
  {
    "assignmentId": "v2:auto:PRB01-001:0",
    "cardNumber": "PRB01-001",
    "effectIndex": 0,
    "status": "ASSIGNED",
    "printedText": "[Activate: Main] [Once Per Turn] Up to 1 of your Characters without an [On Play] effect and with a cost of 8 or less gains [Rush] during this turn. (This card can attack on the turn in which it is played.)",
    "effect": {
      "category": "ACTIVATE",
      "applicationMode": "ONE_SHOT",
      "activationZones": [
        "HAND",
        "LEADER_AREA",
        "CHARACTER_AREA",
        "STAGE_AREA"
      ],
      "timing": {
        "kind": "STANDARD_TIMING",
        "timing": "ACTIVATE_MAIN"
      },
      "optionality": "MANDATORY",
      "resolution": {
        "kind": "ACTION",
        "action": {
          "type": "GRANT_KEYWORD",
          "selector": {
            "subject": "CARD",
            "controller": "PLAYER",
            "zones": [
              "CHARACTER_AREA"
            ],
            "cardCategories": [
              "CHARACTER"
            ],
            "quantity": {
              "kind": "UP_TO",
              "value": {
                "kind": "NUMBER",
                "value": 1
              }
            },
            "chooser": "EFFECT_OWNER",
            "cost": {
              "propertyLayer": "CURRENT",
              "comparison": "AT_MOST",
              "value": {
                "kind": "NUMBER",
                "value": 8
              }
            }
          },
          "keyword": "RUSH",
          "duration": {
            "kind": "THIS_TURN"
          }
        },
        "actionId": "PRB01-001#0.0"
      }
    },
    "coveredAtomicEffectIds": [
      "PRB01-001#0.0"
    ]
  }
] satisfies readonly EffectAssignment_V2[];
